// Strings for the four Damage screens and their forms. The English follows the
// website's damage pages (Hatim/src/pages/damage), labels included.

export const DAMAGE_COPY = {
  en: {
    title: 'Damage',
    backToMenu: 'Back to menu',
    back: 'Back',
    close: 'Close',
    loadError: 'Could not load damage.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    optional: 'Optional',
    select: 'Select',
    date: 'Date',
    notes: 'Notes',
    sections: { overview: 'Overview', entries: 'Entries', receive: 'Receive', transactions: 'Transactions' },
    periods: { all: 'All time', thisMonth: 'This month', lastMonth: 'Last month', thisYear: 'This year' },
    periodLabel: 'Period',
    pcs: (shown: string) => `${shown} pcs`,
    showMore: 'Show more',

    sources: {
      own_stock: { label: 'Own stock', sub: 'Broke here' },
      supplier: { label: 'Came damaged', sub: 'From the supplier' },
    },
    actions: {
      repair: { label: 'Repair', sub: 'Fix and bring back' },
      return: { label: 'Return', sub: 'Back to the supplier' },
      exchange: { label: 'Change', sub: 'Swap for a new one' },
    },
    results: {
      repaired: { label: 'Repaired', sub: 'Goes back in stock' },
      replaced: { label: 'Replaced', sub: 'A new piece, goes in stock' },
      scrapped: { label: 'Scrapped', sub: 'Beyond saving, written off' },
    },
    statuses: { pending: 'Out', partial: 'Partly back', completed: 'Settled' },

    piecesDamaged: 'Pieces damaged',
    inPeriod: 'in this period',
    valueOut: 'Value off the shelf',
    atCost: 'at what it cost, not list price',
    stillOut: 'Still out',
    notBack: 'not back yet',
    netCost: 'Net cost of damage',
    netHint: 'repairs + write-offs, less refunds',
    repairsPaid: 'Repairs paid',
    writtenOff: 'Written off',
    recovered: 'Recovered',
    latest: 'Latest entries',
    nothingInPeriod: 'Nothing damaged in this period.',

    searchEntries: 'Doc no, supplier or product',
    searchLabel: 'Search',
    countEntries: (n: number, shown: string) => (n === 1 ? '1 entry' : `${shown} entries`),
    recordDamage: 'Record damage',
    items: 'Products',
    line: (qty: string, each: string, total: string) => `${qty} × ${each} = ${total}`,
    backOf: (back: string, qty: string) => `${back} of ${qty} back`,
    receive: 'Receive',
    deleteEntry: 'Delete entry',
    deleteTitle: (doc: string) => `Delete ${doc}?`,
    deleteText: 'The stock it took goes back where it came from.',
    recorded: 'Damage recorded - stock updated',
    deleted: 'Entry deleted',

    whereFrom: 'Where it broke',
    whatNext: 'What happens next',
    supplierRequired: 'Supplier *',
    supplierOptional: 'Supplier',
    supplierNotNeeded: 'Not needed for an own-stock repair.',
    chooseSupplier: 'Choose supplier',
    searchSuppliers: 'Search suppliers',
    noSuppliers: 'No suppliers yet.',
    errSupplier: 'Choose the supplier this is going back to',
    addProduct: 'Add product',
    chooseProduct: 'Choose product',
    searchProducts: 'Search products',
    noProductMatch: 'No product matches.',
    qty: 'Qty *',
    unitCost: 'Unit cost (৳)',
    unitCostHint: 'Leave blank to use what it cost (FIFO).',
    removeLine: 'Remove',
    errItems: 'Add at least one product',
    errQty: 'Enter a whole number above 0',
    errCost: 'Enter a valid amount',
    stockNote: 'Saving takes these off sellable stock right away.',

    piecesOut: (n: number, shown: string) => (n === 1 ? '1 piece still out' : `${shown} pieces still out`),
    searchReceive: 'Doc no, product or supplier',
    nothingOut: 'Nothing is out.',
    sent: (date: string) => `Sent ${date}`,
    out: 'Out',
    backLabel: 'Back',
    still: 'Still out',
    unitCostLabel: 'Unit cost',
    receiveTitle: 'Receive',
    howMany: 'How many came back *',
    whatCame: 'What came back',
    backInStock: (n: string, each: string) => `${n} piece(s) go back into sellable stock at ${each} each.`,
    writeOffNote: (amount: string) => `${amount} is written off as a loss. Nothing goes back into stock.`,
    receivedBy: 'Received by',
    receivedByPlaceholder: 'Who took delivery',
    errBack: (n: string) => `Only ${n} still to come back on this line`,
    receivedToast: 'Received - back in stock',
    writtenOffToast: 'Written off',

    paidOut: 'Paid out',
    netShort: 'Net cost',
    searchMoney: 'Doc no, category or account',
    noCash: 'No cash moved',
    addMoney: 'Add transaction',
    kinds: {
      repair_cost: { label: 'Repair cost', sub: 'Money out' },
      supplier_refund: { label: 'Supplier refund', sub: 'Money in' },
    },
    whichEntry: 'Which damage *',
    chooseEntry: 'Choose the entry',
    amount: 'Amount (৳) *',
    account: 'Account *',
    chooseAccount: 'Where the money moved',
    errEntry: 'Which damage entry is this for?',
    errAmount: 'Enter an amount more than 0',
    errAccount: 'Choose the account the money moved through',
    moneySaved: 'Saved',
    noMoney: 'No damage transactions in this period.',
  },
  bn: {
    title: 'ড্যামেজ',
    backToMenu: 'মেনুতে ফিরুন',
    back: 'ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'ড্যামেজের হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    optional: 'ঐচ্ছিক',
    select: 'বাছাই করুন',
    date: 'তারিখ',
    notes: 'নোট',
    sections: { overview: 'ওভারভিউ', entries: 'এন্ট্রি', receive: 'ফেরত নিন', transactions: 'লেনদেন' },
    periods: { all: 'সব সময়', thisMonth: 'এই মাস', lastMonth: 'গত মাস', thisYear: 'এই বছর' },
    periodLabel: 'সময়',
    pcs: (shown: string) => `${shown} পিস`,
    showMore: 'আরও দেখুন',

    sources: {
      own_stock: { label: 'নিজের স্টক', sub: 'এখানে নষ্ট হয়েছে' },
      supplier: { label: 'নষ্ট অবস্থায় এসেছে', sub: 'সাপ্লায়ার থেকে' },
    },
    actions: {
      repair: { label: 'মেরামত', sub: 'সারিয়ে ফেরত' },
      return: { label: 'ফেরত', sub: 'সাপ্লায়ারকে ফেরত' },
      exchange: { label: 'বদল', sub: 'নতুনটার সাথে বদল' },
    },
    results: {
      repaired: { label: 'মেরামত হয়েছে', sub: 'স্টকে ফিরবে' },
      replaced: { label: 'বদলে নতুন', sub: 'নতুন পিস, স্টকে যাবে' },
      scrapped: { label: 'বাতিল', sub: 'আর কাজে লাগবে না, ক্ষতি' },
    },
    statuses: { pending: 'বাইরে', partial: 'কিছু ফেরত', completed: 'নিষ্পত্তি' },

    piecesDamaged: 'নষ্ট পিস',
    inPeriod: 'এই সময়ে',
    valueOut: 'স্টক থেকে বেরোনো মূল্য',
    atCost: 'কেনা দামে, তালিকার দামে না',
    stillOut: 'এখনো বাইরে',
    notBack: 'এখনো ফেরেনি',
    netCost: 'ড্যামেজের নিট খরচ',
    netHint: 'মেরামত + ক্ষতি − ফেরত টাকা',
    repairsPaid: 'মেরামতে দেওয়া',
    writtenOff: 'ক্ষতি হিসেবে লেখা',
    recovered: 'ফেরত এসেছে',
    latest: 'সাম্প্রতিক এন্ট্রি',
    nothingInPeriod: 'এই সময়ে কিছু নষ্ট হয়নি।',

    searchEntries: 'ডক নং, সাপ্লায়ার বা পণ্য',
    searchLabel: 'খুঁজুন',
    countEntries: (_n: number, shown: string) => `${shown}টি এন্ট্রি`,
    recordDamage: 'ড্যামেজ লিখুন',
    items: 'পণ্য',
    line: (qty: string, each: string, total: string) => `${qty} × ${each} = ${total}`,
    backOf: (back: string, qty: string) => `${qty}টির মধ্যে ${back}টি ফেরত`,
    receive: 'ফেরত নিন',
    deleteEntry: 'এন্ট্রি মুছুন',
    deleteTitle: (doc: string) => `${doc} মুছবেন?`,
    deleteText: 'এটা যে স্টক নিয়েছিল তা আবার ফিরে যাবে।',
    recorded: 'ড্যামেজ লেখা হয়েছে — স্টক আপডেট হয়েছে',
    deleted: 'এন্ট্রি মুছে ফেলা হয়েছে',

    whereFrom: 'কোথায় নষ্ট',
    whatNext: 'এরপর কী হবে',
    supplierRequired: 'সাপ্লায়ার *',
    supplierOptional: 'সাপ্লায়ার',
    supplierNotNeeded: 'নিজের স্টক মেরামতে লাগে না।',
    chooseSupplier: 'সাপ্লায়ার বাছুন',
    searchSuppliers: 'সাপ্লায়ার খুঁজুন',
    noSuppliers: 'এখনো কোনো সাপ্লায়ার নেই।',
    errSupplier: 'কোন সাপ্লায়ারের কাছে যাচ্ছে বেছে নিন',
    addProduct: 'পণ্য যোগ করুন',
    chooseProduct: 'পণ্য বাছুন',
    searchProducts: 'পণ্য খুঁজুন',
    noProductMatch: 'কোনো পণ্য মেলেনি।',
    qty: 'পরিমাণ *',
    unitCost: 'প্রতিটির দাম (৳)',
    unitCostHint: 'খালি রাখলে কেনা দাম (FIFO) বসবে।',
    removeLine: 'সরান',
    errItems: 'অন্তত একটা পণ্য যোগ করুন',
    errQty: '০-এর বেশি পূর্ণ সংখ্যা লিখুন',
    errCost: 'সঠিক পরিমাণ লিখুন',
    stockNote: 'সেভ করলে এগুলো সাথে সাথে বিক্রিযোগ্য স্টক থেকে বাদ যাবে।',

    piecesOut: (_n: number, shown: string) => `${shown}টি পিস এখনো বাইরে`,
    searchReceive: 'ডক নং, পণ্য বা সাপ্লায়ার',
    nothingOut: 'কিছুই বাইরে নেই।',
    sent: (date: string) => `পাঠানো ${date}`,
    out: 'গেছে',
    backLabel: 'ফিরেছে',
    still: 'বাকি',
    unitCostLabel: 'প্রতিটির দাম',
    receiveTitle: 'ফেরত নিন',
    howMany: 'কতগুলো ফিরেছে *',
    whatCame: 'কী অবস্থায় ফিরেছে',
    backInStock: (n: string, each: string) => `${n}টি পিস ${each} দরে আবার বিক্রিযোগ্য স্টকে যাবে।`,
    writeOffNote: (amount: string) => `${amount} ক্ষতি হিসেবে লেখা হবে। স্টকে কিছু ফিরবে না।`,
    receivedBy: 'কে বুঝে নিয়েছেন',
    receivedByPlaceholder: 'যিনি মাল বুঝে নিয়েছেন',
    errBack: (n: string) => `এই লাইনে মাত্র ${n}টি ফেরত বাকি`,
    receivedToast: 'ফেরত নেওয়া হয়েছে — স্টকে ফিরেছে',
    writtenOffToast: 'ক্ষতি হিসেবে লেখা হয়েছে',

    paidOut: 'দেওয়া হয়েছে',
    netShort: 'নিট খরচ',
    searchMoney: 'ডক নং, খাত বা অ্যাকাউন্ট',
    noCash: 'টাকা নড়েনি',
    addMoney: 'লেনদেন যোগ করুন',
    kinds: {
      repair_cost: { label: 'মেরামত খরচ', sub: 'টাকা গেছে' },
      supplier_refund: { label: 'সাপ্লায়ার ফেরত', sub: 'টাকা এসেছে' },
    },
    whichEntry: 'কোন ড্যামেজ *',
    chooseEntry: 'এন্ট্রি বাছুন',
    amount: 'পরিমাণ (৳) *',
    account: 'অ্যাকাউন্ট *',
    chooseAccount: 'কোন অ্যাকাউন্টে টাকা নড়েছে',
    errEntry: 'কোন ড্যামেজ এন্ট্রির জন্য?',
    errAmount: '০-এর বেশি পরিমাণ লিখুন',
    errAccount: 'কোন অ্যাকাউন্টে টাকা নড়েছে বেছে নিন',
    moneySaved: 'সেভ হয়েছে',
    noMoney: 'এই সময়ে কোনো ড্যামেজ লেনদেন নেই।',
  },
};

