// Strings for Support - the tickets, a ticket's conversation and the new
// ticket sheet - in the website's SupportTickets and GuidelineVideos words.

export const SUPPORT_COPY = {
  en: {
    title: 'Support Ticket',
    backToMenu: 'Back to menu',
    back: 'Back',
    close: 'Close',
    cancel: 'Cancel',
    retry: 'Try again',
    loadError: 'Failed to load your tickets.',
    intro: 'Ask us anything - the answer comes back here.',
    statuses: { open: 'Waiting for reply', answered: 'Answered', solved: 'Solved' },
    noTickets: 'No tickets yet. Ask here when something goes wrong - our answer comes back to this page.',
    newTicket: 'New ticket',
    whatsApp: 'Or chat on WhatsApp',
    videosTitle: 'Guideline Video',
    videosText: 'Videos are being added here soon. Until then, ask anything through a support ticket.',
    noSubject: 'No subject',
    you: 'You',
    support: 'Support',
    typing: 'Support is typing…',
    solvedNote: 'Marked solved. Writing again opens it back up.',
    replyPlaceholder: 'Write a reply',
    send: 'Send',
    sending: 'Sending…',
    errReply: 'Write a message first',
    subject: 'Subject',
    subjectPlaceholder: 'Optional',
    message: 'Your question *',
    messagePlaceholder: 'What went wrong, and where?',
    errMessage: 'Write your question first',
    submit: 'Submit',
    submitted: 'Ticket submitted',
  },
  bn: {
    title: 'সাপোর্ট টিকেট',
    backToMenu: 'মেনুতে ফিরুন',
    back: 'ফিরুন',
    close: 'বন্ধ করুন',
    cancel: 'বাতিল',
    retry: 'আবার চেষ্টা করুন',
    loadError: 'টিকেট আনা যায়নি।',
    intro: 'সমস্যা জানান, উত্তর এখানেই পাবেন।',
    statuses: { open: 'উত্তরের অপেক্ষায়', answered: 'উত্তর দেওয়া হয়েছে', solved: 'সমাধান হয়েছে' },
    noTickets: 'এখনো কোনো টিকেট নেই। সমস্যা হলে এখান থেকে জানান - আমরা উত্তর দিলে এখানেই দেখতে পাবেন।',
    newTicket: 'নতুন টিকেট',
    whatsApp: 'অথবা হোয়াটসঅ্যাপে কথা বলুন',
    videosTitle: 'গাইডলাইন ভিডিও',
    videosText: 'ভিডিওগুলো শিগগিরই এখানে যোগ করা হবে। ততক্ষণ কিছু জানার থাকলে সাপোর্ট টিকেট থেকে জিজ্ঞেস করুন।',
    noSubject: 'বিষয় নেই',
    you: 'আপনি',
    support: 'সাপোর্ট',
    typing: 'সাপোর্ট লিখছে…',
    solvedNote: 'সমাধান হয়েছে বলে চিহ্নিত। আবার লিখলে টিকেটটা খুলে যাবে।',
    replyPlaceholder: 'উত্তর লিখুন',
    send: 'পাঠান',
    sending: 'পাঠানো হচ্ছে…',
    errReply: 'কিছু লিখুন',
    subject: 'বিষয়',
    subjectPlaceholder: 'ঐচ্ছিক',
    message: 'আপনার প্রশ্ন *',
    messagePlaceholder: 'কী সমস্যা হয়েছে, কোথায়?',
    errMessage: 'আপনার সমস্যাটি লিখুন',
    submit: 'জমা দিন',
    submitted: 'টিকেট জমা হয়েছে',
  },
};
