import { bnDigits } from '@/context/LanguageContext';

// Strings for the four Loan screens. The Bangla is the Figma file's own where
// it draws a Bangla version (LoanAddBn, LoanTxnProfitBn, LoanStatementBn); the
// rest follows those frames' words - পাওনা, দেনা, পেয়েছি, দিয়েছি, মূল টাকা, লাভ.

export const LOAN_COPY = {
  en: {
    title: 'Loans',
    backToMenu: 'Back to menu',
    close: 'Close',
    loadError: 'Could not load the loans.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    optional: 'Optional',
    select: 'Select',
    sections: { overview: 'Overview', people: 'Bank / Person', transactions: 'Transactions', statement: 'Statement' },
    side: { pawna: 'Pawna', dena: 'Dena', balanced: 'Balanced' },
    sideLong: { pawna: 'Pawna · they owe us', dena: 'Dena · we owe them', balanced: 'Balanced · nothing due' },
    call: (name: string, phone: string) => `Call ${name}, ${phone}`,
    options: (name: string) => `Options for ${name}`,

    // Overview
    totalDena: 'Total Dena',
    youOweThem: 'You owe them',
    totalPawna: 'Total Pawna',
    theyOweYou: 'They owe you',
    totalPaid: 'Total paid',
    paymentMade: 'Payment made',
    totalReceived: 'Total received',
    cashReceived: 'Cash received',
    netBalance: 'Net balance',
    netSide: { pawna: 'Pawna (+)', dena: 'Dena (−)', balanced: 'Balanced' },
    activeAccounts: 'Active accounts',
    totalActive: 'Total active',
    outstandingTitle: 'Outstanding by bank / person',
    sendSms: 'Send SMS',
    searchLabel: 'Search by name or phone',
    searchPlaceholder: 'Name or phone',
    sortLabel: 'Sort',
    sorts: { high: 'Balance ↓', low: 'Balance ↑', name: 'Name A–Z' },
    noMatch: (q: string) => `No bank or person matches “${q}”.`,
    noPeopleYet: 'No banks or people yet.',
    opening: 'Opening',
    receive: 'Receive',
    payment: 'Payment',
    profit: 'Profit',
    sms: 'SMS',
    statement: 'Statement',
    total: 'Total',
    legendPawna: 'they owe you',
    legendDena: 'you owe them',
    smsTitle: 'Send balance SMS',
    smsIntro: 'Each person gets an SMS with their current loan balance.',
    peopleCount: (n: number) => (n === 1 ? '1 person' : `${n} people`),
    sendTo: (n: number) => `Send to ${n}`,
    sending: 'Sending…',
    smsSentTo: (name: string) => `SMS sent to ${name}`,
    smsSentCount: (n: number) => `SMS sent to ${n} people`,
    noPhone: (name: string) => `${name} has no phone number`,
    noPhones: 'None of the listed people have a phone number',

    // Bank / Person
    countPeople: (n: number) => (n === 1 ? '1 bank / person' : `${n} banks / people`),
    activeCount: (n: number) => `${n} active`,
    noAddress: 'No address added',
    openingBalance: 'Opening balance',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    addPerson: 'Add bank / person',
    editPerson: 'Edit bank / person',
    name: 'Name *',
    namePlaceholder: 'Bank or person name',
    welcomeSms: 'Welcome SMS',
    phone: 'Phone *',
    address: 'Address',
    openingTypes: {
      pawna: { label: 'Pawna', sub: 'They owe us' },
      dena: { label: 'Dena', sub: 'We owe them' },
      zero: { label: 'Zero', sub: 'Nothing outstanding' },
    },
    openingTypeLabel: 'Opening balance type',
    amountShort: 'Amount (৳)',
    asOfDate: 'As of date',
    notes: 'Notes',
    activeHint: 'Shows in lists, totals and SMS',
    errName: 'Enter a bank or person name',
    errPhone: 'Enter a valid phone number, e.g. 01712345678',
    errAmountInvalid: 'Enter a valid amount',
    errOpening: 'Enter the opening amount, or choose Zero balance',
    personAdded: (name: string) => `${name} added`,
    personAddedWelcome: (name: string) => `${name} added · welcome SMS sent`,
    personUpdated: (name: string) => `${name} updated`,
    personDeleted: (name: string) => `${name} deleted`,
    personSaved: 'Bank / Person saved',
    edit: 'Edit',
    viewStatement: 'View statement',
    deletePersonTitle: (name: string) => `Delete ${name}?`,
    deletePersonText: 'They will be removed from the loan list. This can’t be undone.',
    linkedLender: 'This bank / person has loan transactions. Delete those transactions first.',

    // Transactions
    allPeople: 'All banks / people',
    allTime: 'All time',
    allMonths: 'All months',
    filtersLabel: 'Filters',
    filterPerson: 'Bank or person',
    filterMonth: 'Month',
    received: 'Received',
    paid: 'Paid',
    moneyCameIn: 'Money came in',
    moneyWentOut: 'Money went out',
    countTxns: (n: number) => (n === 1 ? '1 transaction' : `${n} transactions`),
    clearFilters: 'Clear filters',
    emptyFiltered: 'No transactions match these filters.',
    emptyAll: 'No loan transactions yet.',
    loadOlder: 'Load older',
    newTransaction: 'New transaction',
    formNew: 'New loan transaction',
    formEdit: 'Edit transaction',
    personField: 'Bank / Person *',
    smsReceipt: 'SMS receipt',
    category: 'Category',
    principal: 'Principal',
    movesBalance: 'Moves the balance',
    balanceUnchanged: 'Balance unchanged',
    type: 'Type *',
    expenseCategory: 'Expense category *',
    expenseHelp: 'Recorded as an expense under this category. Your account moves once, from this transaction — not twice.',
    incomeSource: 'Income source',
    incomePlaceholder: 'Bank / person name',
    incomeHelp: 'Recorded as Other Income under this name. Left blank, the bank / person is used.',
    amount: 'Amount (৳) *',
    date: 'Date',
    account: 'Account *',
    intoAccount: 'The account the money comes into.',
    fromAccount: 'The account the money is paid from.',
    errPerson: 'Choose a bank or person',
    errType: 'Choose received or paid',
    errExpense: 'Choose an expense category',
    errAmount: 'Enter an amount more than 0',
    errAccount: 'Choose an account',
    txnSaved: 'Transaction saved',
    txnUpdated: 'Transaction updated',
    txnSavedSms: (name: string) => `Saved · SMS receipt sent to ${name}`,
    txnUpdatedSms: (name: string) => `Updated · SMS receipt sent to ${name}`,
    receiptSent: (name: string) => `SMS receipt sent to ${name}`,
    receiptNoPhone: 'Receipt SMS skipped - this bank/person has no valid phone number',
    txnDeleted: 'Transaction deleted',
    editTxn: 'Edit transaction',
    sendReceipt: 'Send SMS receipt',
    deleteTxn: 'Delete transaction',
    receivedAmount: (amount: string) => `Received · ${amount}`,
    paidAmount: (amount: string) => `Paid · ${amount}`,
    otherIncomeAs: (name: string) => `Other income · ${name}`,
    expenseAs: (name: string) => `Expense · ${name}`,
    notSet: 'Not set',
    deleteTxnTitle: 'Delete this transaction?',
    receiptOf: (amount: string, name: string, date: string) => `Receipt of ${amount} from ${name} on ${date}. `,
    paymentOf: (amount: string, name: string, date: string) => `Payment of ${amount} to ${name} on ${date}. `,
    deleteProfitTail: (account: string, income: boolean) =>
      `The ${account} balance goes back to how it was, and the linked ${income ? 'income' : 'expense'} entry is removed too.`,
    deletePrincipalTail: (name: string, account: string) =>
      `${name}’s loan balance and the ${account} balance go back to how they were.`,
    txnOptions: (received: boolean, name: string, amount: string) =>
      `Options for ${received ? 'received from' : 'paid to'} ${name}, ${amount}`,

    // Statement
    statementIntro: 'Every loan entry with one bank or person, with the balance carried forward.',
    personLabel: 'Bank / Person',
    choosePerson: 'Choose a bank or person',
    periods: { all: 'All time', thisMonth: 'This month', lastMonth: 'Last month', thisYear: 'This year', custom: 'Custom' },
    periodLabel: 'Period',
    from: 'From',
    to: 'To',
    start: 'Start',
    today: 'Today',
    rangeError: 'The start date can’t be after the end date',
    noPersonText: 'Choose a bank or person to see their statement.',
    closing: 'Closing',
    paidDebit: 'Paid (debit)',
    addsToPawna: 'Adds to Pawna',
    receivedCredit: 'Received (credit)',
    takesFromPawna: 'Takes from Pawna',
    profitPaidPart: (amount: string) => `Profit paid ${amount} (expense)`,
    profitReceivedPart: (amount: string) => `Profit received ${amount} (other income)`,
    profitTail: ' — kept out of the loan balance.',
    closingBalance: 'Closing balance',
    into: (account: string) => `Into ${account}`,
    outOf: (account: string) => `From ${account}`,
    bal: (text: string) => `Bal ${text}`,
    noEntries: 'No loan entries in this period.',
    sharePdf: 'Share PDF',
    print: 'Print',
    statementTitle: (name: string) => `Loan statement · ${name}`,
    colDate: 'Date',
    colType: 'Type',
    colAccount: 'Account',
    colDebit: 'Paid',
    colCredit: 'Received',
    colBalance: 'Balance',
  },
  bn: {
    title: 'লোন',
    backToMenu: 'মেনুতে ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'লোনের হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    optional: 'ঐচ্ছিক',
    select: 'বাছাই করুন',
    sections: { overview: 'ওভারভিউ', people: 'ব্যাংক / ব্যক্তি', transactions: 'লেনদেন', statement: 'স্টেটমেন্ট' },
    side: { pawna: 'পাওনা', dena: 'দেনা', balanced: 'সমান' },
    sideLong: { pawna: 'পাওনা · ওরা আমাদের দেবে', dena: 'দেনা · আমরা ওদের দেব', balanced: 'সমান · কিছু বাকি নেই' },
    call: (name: string, phone: string) => `${name}-কে কল করুন, ${phone}`,
    options: (name: string) => `${name}: আরও অপশন`,

    totalDena: 'মোট দেনা',
    youOweThem: 'আমরা ওদের দেব',
    totalPawna: 'মোট পাওনা',
    theyOweYou: 'ওরা আমাদের দেবে',
    totalPaid: 'মোট দিয়েছি',
    paymentMade: 'টাকা দেওয়া হয়েছে',
    totalReceived: 'মোট পেয়েছি',
    cashReceived: 'টাকা পাওয়া গেছে',
    netBalance: 'নিট ব্যালেন্স',
    netSide: { pawna: 'পাওনা (+)', dena: 'দেনা (−)', balanced: 'সমান' },
    activeAccounts: 'সক্রিয় হিসাব',
    totalActive: 'মোট সক্রিয়',
    outstandingTitle: 'ব্যাংক / ব্যক্তি অনুযায়ী বাকি',
    sendSms: 'SMS পাঠান',
    searchLabel: 'নাম বা ফোন দিয়ে খুঁজুন',
    searchPlaceholder: 'নাম বা ফোন',
    sortLabel: 'সাজান',
    sorts: { high: 'ব্যালেন্স ↓', low: 'ব্যালেন্স ↑', name: 'নাম অনুযায়ী' },
    noMatch: (q: string) => `“${q}” নামে কোনো ব্যাংক বা ব্যক্তি নেই।`,
    noPeopleYet: 'এখনো কোনো ব্যাংক বা ব্যক্তি নেই।',
    opening: 'শুরু',
    receive: 'পেয়েছি',
    payment: 'দিয়েছি',
    profit: 'লাভ',
    sms: 'SMS',
    statement: 'স্টেটমেন্ট',
    total: 'মোট',
    legendPawna: 'ওরা আমাদের দেবে',
    legendDena: 'আমরা ওদের দেব',
    smsTitle: 'ব্যালেন্স SMS পাঠান',
    smsIntro: 'প্রত্যেকে তাদের বর্তমান লোন ব্যালেন্স সহ একটা SMS পাবে।',
    peopleCount: (n: number) => `${bnDigits(n)} জন`,
    sendTo: (n: number) => `${bnDigits(n)} জনকে পাঠান`,
    sending: 'পাঠানো হচ্ছে…',
    smsSentTo: (name: string) => `${name}-কে SMS পাঠানো হয়েছে`,
    smsSentCount: (n: number) => `${bnDigits(n)} জনকে SMS পাঠানো হয়েছে`,
    noPhone: (name: string) => `${name}-এর ফোন নম্বর নেই`,
    noPhones: 'তালিকার কারও ফোন নম্বর নেই',

    countPeople: (n: number) => `${bnDigits(n)}টি ব্যাংক / ব্যক্তি`,
    activeCount: (n: number) => `${bnDigits(n)}টি সক্রিয়`,
    noAddress: 'ঠিকানা দেওয়া নেই',
    openingBalance: 'শুরুর ব্যালেন্স',
    status: 'অবস্থা',
    active: 'সক্রিয়',
    inactive: 'নিষ্ক্রিয়',
    addPerson: 'নতুন ব্যাংক / ব্যক্তি',
    editPerson: 'ব্যাংক / ব্যক্তি সম্পাদনা',
    name: 'নাম *',
    namePlaceholder: 'ব্যাংক বা ব্যক্তির নাম',
    welcomeSms: 'স্বাগত SMS',
    phone: 'ফোন *',
    address: 'ঠিকানা',
    openingTypes: {
      pawna: { label: 'পাওনা', sub: 'ওরা আমাদের দেবে' },
      dena: { label: 'দেনা', sub: 'আমরা ওদের দেব' },
      zero: { label: 'শূন্য', sub: 'কিছু বাকি নেই' },
    },
    openingTypeLabel: 'শুরুর ব্যালেন্সের ধরন',
    amountShort: 'পরিমাণ (৳)',
    asOfDate: 'হিসাবের তারিখ',
    notes: 'নোট',
    activeHint: 'তালিকা, মোট হিসাব আর SMS-এ দেখাবে',
    errName: 'ব্যাংক বা ব্যক্তির নাম লিখুন',
    errPhone: 'সঠিক ফোন নম্বর লিখুন, যেমন ০১৭১২৩৪৫৬৭৮',
    errAmountInvalid: 'সঠিক পরিমাণ লিখুন',
    errOpening: 'শুরুর পরিমাণ লিখুন, অথবা শূন্য বাছুন',
    personAdded: (name: string) => `${name} যোগ হয়েছে`,
    personAddedWelcome: (name: string) => `${name} যোগ হয়েছে · স্বাগত SMS পাঠানো হয়েছে`,
    personUpdated: (name: string) => `${name} আপডেট হয়েছে`,
    personDeleted: (name: string) => `${name} মুছে ফেলা হয়েছে`,
    personSaved: 'ব্যাংক / ব্যক্তি সেভ হয়েছে',
    edit: 'সম্পাদনা',
    viewStatement: 'স্টেটমেন্ট দেখুন',
    deletePersonTitle: (name: string) => `${name}-কে মুছবেন?`,
    deletePersonText: 'লোনের তালিকা থেকে বাদ যাবে। এটা আর ফেরানো যাবে না।',
    linkedLender: 'এই ব্যাংক / ব্যক্তির লোন লেনদেন আছে। আগে সেই লেনদেনগুলো মুছুন।',

    allPeople: 'সব ব্যাংক / ব্যক্তি',
    allTime: 'সব সময়',
    allMonths: 'সব মাস',
    filtersLabel: 'ফিল্টার',
    filterPerson: 'ব্যাংক বা ব্যক্তি',
    filterMonth: 'মাস',
    received: 'পেয়েছি',
    paid: 'দিয়েছি',
    moneyCameIn: 'টাকা এসেছে',
    moneyWentOut: 'টাকা গেছে',
    countTxns: (n: number) => `${bnDigits(n)}টি লেনদেন`,
    clearFilters: 'ফিল্টার মুছুন',
    emptyFiltered: 'এই ফিল্টারে কোনো লেনদেন নেই।',
    emptyAll: 'এখনো কোনো লোন লেনদেন নেই।',
    loadOlder: 'আরও পুরোনো দেখুন',
    newTransaction: 'নতুন লেনদেন',
    formNew: 'নতুন লোন লেনদেন',
    formEdit: 'লেনদেন সম্পাদনা',
    personField: 'ব্যাংক / ব্যক্তি *',
    smsReceipt: 'SMS রসিদ',
    category: 'খাত',
    principal: 'মূল টাকা',
    movesBalance: 'ব্যালেন্স বদলায়',
    balanceUnchanged: 'ব্যালেন্স বদলায় না',
    type: 'ধরন *',
    expenseCategory: 'খরচের খাত *',
    expenseHelp: 'এই খাতে খরচ হিসেবে লেখা হবে। অ্যাকাউন্ট থেকে টাকা একবারই কাটবে — এই লেনদেন থেকে, দুবার নয়।',
    incomeSource: 'আয়ের উৎস',
    incomePlaceholder: 'ব্যাংক / ব্যক্তির নাম',
    incomeHelp: 'এই নামে অন্যান্য আয় হিসেবে লেখা হবে। খালি রাখলে ব্যাংক / ব্যক্তির নাম বসবে।',
    amount: 'পরিমাণ (৳) *',
    date: 'তারিখ',
    account: 'অ্যাকাউন্ট *',
    intoAccount: 'যে অ্যাকাউন্টে টাকা এসেছে।',
    fromAccount: 'যে অ্যাকাউন্ট থেকে টাকা দেওয়া হয়েছে।',
    errPerson: 'ব্যাংক বা ব্যক্তি বেছে নিন',
    errType: 'পেয়েছি না দিয়েছি, বেছে নিন',
    errExpense: 'খরচের খাত বেছে নিন',
    errAmount: '০-এর বেশি পরিমাণ লিখুন',
    errAccount: 'অ্যাকাউন্ট বেছে নিন',
    txnSaved: 'লেনদেন সেভ হয়েছে',
    txnUpdated: 'লেনদেন আপডেট হয়েছে',
    txnSavedSms: (name: string) => `সেভ হয়েছে · ${name}-কে SMS রসিদ পাঠানো হয়েছে`,
    txnUpdatedSms: (name: string) => `আপডেট হয়েছে · ${name}-কে SMS রসিদ পাঠানো হয়েছে`,
    receiptSent: (name: string) => `${name}-কে SMS রসিদ পাঠানো হয়েছে`,
    receiptNoPhone: 'SMS রসিদ পাঠানো হয়নি — এই ব্যাংক / ব্যক্তির সঠিক ফোন নম্বর নেই',
    txnDeleted: 'লেনদেন মুছে ফেলা হয়েছে',
    editTxn: 'লেনদেন সম্পাদনা',
    sendReceipt: 'SMS রসিদ পাঠান',
    deleteTxn: 'লেনদেন মুছুন',
    receivedAmount: (amount: string) => `পেয়েছি · ${amount}`,
    paidAmount: (amount: string) => `দিয়েছি · ${amount}`,
    otherIncomeAs: (name: string) => `অন্যান্য আয় · ${name}`,
    expenseAs: (name: string) => `খরচ · ${name}`,
    notSet: 'দেওয়া নেই',
    deleteTxnTitle: 'এই লেনদেন মুছবেন?',
    receiptOf: (amount: string, name: string, date: string) => `${date}-এ ${name}-এর কাছ থেকে ${amount} পাওয়া। `,
    paymentOf: (amount: string, name: string, date: string) => `${date}-এ ${name}-কে ${amount} দেওয়া। `,
    deleteProfitTail: (account: string, income: boolean) =>
      `${account}-এর ব্যালেন্স আগের মতো হয়ে যাবে, আর এর সাথে যুক্ত ${income ? 'আয়ের' : 'খরচের'} এন্ট্রিও মুছে যাবে।`,
    deletePrincipalTail: (name: string, account: string) =>
      `${name}-এর লোন ব্যালেন্স আর ${account}-এর ব্যালেন্স আগের মতো হয়ে যাবে।`,
    txnOptions: (received: boolean, name: string, amount: string) =>
      `${name}, ${amount} ${received ? 'পেয়েছি' : 'দিয়েছি'}: আরও অপশন`,

    statementIntro: 'একজন ব্যাংক বা ব্যক্তির সাথে সব লোন লেনদেন, প্রতিটার পর ব্যালেন্স সহ।',
    personLabel: 'ব্যাংক / ব্যক্তি',
    choosePerson: 'ব্যাংক বা ব্যক্তি বেছে নিন',
    periods: { all: 'সব সময়', thisMonth: 'এই মাস', lastMonth: 'গত মাস', thisYear: 'এই বছর', custom: 'নিজে বাছুন' },
    periodLabel: 'সময়',
    from: 'থেকে',
    to: 'পর্যন্ত',
    start: 'শুরু',
    today: 'আজ',
    rangeError: 'শুরুর তারিখ শেষের তারিখের পরে হতে পারে না',
    noPersonText: 'স্টেটমেন্ট দেখতে একজন ব্যাংক বা ব্যক্তি বেছে নিন।',
    closing: 'শেষ ব্যালেন্স',
    paidDebit: 'দিয়েছি (ডেবিট)',
    addsToPawna: 'পাওনায় যোগ হয়',
    receivedCredit: 'পেয়েছি (ক্রেডিট)',
    takesFromPawna: 'পাওনা থেকে কমে',
    profitPaidPart: (amount: string) => `লাভ দিয়েছি ${amount} (খরচ)`,
    profitReceivedPart: (amount: string) => `লাভ পেয়েছি ${amount} (অন্যান্য আয়)`,
    profitTail: ' — লোনের ব্যালেন্সে ধরা হয়নি।',
    closingBalance: 'শেষ ব্যালেন্স',
    into: (account: string) => `${account}-এ এসেছে`,
    outOf: (account: string) => `${account} থেকে গেছে`,
    bal: (text: string) => `ব্যালেন্স ${text}`,
    noEntries: 'এই সময়ে কোনো লোন লেনদেন নেই।',
    sharePdf: 'PDF শেয়ার',
    print: 'প্রিন্ট',
    statementTitle: (name: string) => `লোন স্টেটমেন্ট · ${name}`,
    colDate: 'তারিখ',
    colType: 'ধরন',
    colAccount: 'অ্যাকাউন্ট',
    colDebit: 'দিয়েছি',
    colCredit: 'পেয়েছি',
    colBalance: 'ব্যালেন্স',
  },
};
