// Strings for the quick tools - the Cash counter and the day's history - in
// the website's own words (cash_*, history_*).

export const TOOLS_COPY = {
  en: {
    back: 'Back',
    close: 'Close',
    cancel: 'Cancel',
    retry: 'Try again',
    sharePdf: 'Share PDF',
    print: 'Print',

    cashTitle: 'Cash Counter',
    cashIntro: 'Count the drawer: how many of each note. The count stays on this phone until you clear it.',
    date: 'Date',
    countedBy: 'Counted by',
    countedByPlaceholder: 'Type the name',
    note: 'Currency',
    qty: 'Qty',
    amount: 'Amount',
    totalNotes: 'Total notes',
    total: 'Total',
    clear: 'Clear',
    clearTitle: 'Clear the count?',
    clearText: 'Every quantity typed here will be cleared. This cannot be undone.',
    clearConfirm: 'Yes, Clear',
    sendReport: 'Email to owner',
    sending: 'Sending…',
    sent: (email: string) => `Report sent to ${email}`,
    nothingToSend: 'Count something first',
    countedLine: (date: string, who: string) => (who ? `${date} - Counted by ${who}` : date),

    historyTitle: "Today's history",
    entries: 'Entries',
    moneyIn: 'Money in',
    moneyOut: 'Money out',
    empty: 'Nothing was entered on this day.',
    loadError: 'Could not load the day.',
    historyNote: 'Dated by when each entry was made, not by the date on it - so it can differ from that day\'s ledger.',
    colTime: 'Time',
    colWhat: 'What',
    colWho: 'Who / Detail',
    kinds: {
      Sale: 'Sale',
      'Purchase order': 'Purchase order',
      'Stock received': 'Stock received',
      Expense: 'Expense',
      'Due collected': 'Due collected',
      'Supplier paid': 'Supplier paid',
      'Loan received': 'Loan received',
      'Loan repaid': 'Loan repaid',
      'Other income': 'Other income',
    } as Record<string, string>,
  },
  bn: {
    back: 'ফিরুন',
    close: 'বন্ধ করুন',
    cancel: 'বাতিল',
    retry: 'আবার চেষ্টা করুন',
    sharePdf: 'PDF শেয়ার',
    print: 'প্রিন্ট',

    cashTitle: 'ক্যাশ কাউন্টার',
    cashIntro: 'ক্যাশ গুনুন: কোন নোট কয়টা। মুছে না ফেলা পর্যন্ত গণনা এই ফোনে থেকে যাবে।',
    date: 'তারিখ',
    countedBy: 'গুনেছেন',
    countedByPlaceholder: 'নাম লিখুন',
    note: 'নোট',
    qty: 'সংখ্যা',
    amount: 'পরিমাণ',
    totalNotes: 'মোট নোট',
    total: 'সর্বমোট',
    clear: 'মুছুন',
    clearTitle: 'হিসাব মুছে ফেলবেন?',
    clearText: 'এখানে লেখা প্রতিটি সংখ্যা মুছে যাবে। এটি আর ফেরানো যাবে না।',
    clearConfirm: 'হ্যাঁ, মুছুন',
    sendReport: 'মালিককে ইমেইল',
    sending: 'পাঠানো হচ্ছে…',
    sent: (email: string) => `রিপোর্ট পাঠানো হয়েছে ${email}-এ`,
    nothingToSend: 'আগে কিছু গুনুন',
    countedLine: (date: string, who: string) => (who ? `${date} - গুনেছেন ${who}` : date),

    historyTitle: 'আজকের হিসাব',
    entries: 'এন্ট্রি',
    moneyIn: 'জমা',
    moneyOut: 'খরচ',
    empty: 'এই দিনে কিছু এন্ট্রি হয়নি।',
    loadError: 'দিনের হিসাব আনা যায়নি।',
    historyNote: 'প্রতিটা এন্ট্রি যখন লেখা হয়েছে সেই সময় ধরে দেখানো হয়, তার গায়ের তারিখ ধরে নয় - তাই সেদিনের খাতার সাথে না-ও মিলতে পারে।',
    colTime: 'সময়',
    colWhat: 'কী',
    colWho: 'কে / বিবরণ',
    kinds: {
      Sale: 'বিক্রি',
      'Purchase order': 'ক্রয় অর্ডার',
      'Stock received': 'পণ্য গ্রহণ',
      Expense: 'খরচ',
      'Due collected': 'বাকি আদায়',
      'Supplier paid': 'সাপ্লায়ারকে পরিশোধ',
      'Loan received': 'লোন গ্রহণ',
      'Loan repaid': 'লোন পরিশোধ',
      'Other income': 'অন্যান্য আয়',
    } as Record<string, string>,
  },
};
