import { bnDigits } from '@/context/LanguageContext';

// The Dashboard's strings. The Bangla is the Figma file's own where it draws a
// Bangla dashboard (DashboardHiddenBn) and follows its voice elsewhere.

export const DASHBOARD_COPY = {
  en: {
    welcome: (name: string) => `Welcome back, ${name}`,
    sub: 'Everything you need to manage your business.',
    showAmounts: 'Show amounts',
    hideAmounts: 'Hide amounts',
    notifications: 'Notifications',
    account: (name: string) => `Account: ${name}`,
    netProfit: 'Net Profit',
    withdraw: 'Withdraw',
    savings: 'Savings',
    totalPurchase: 'Total Purchase',
    totalSales: 'Total Sales',
    totalProfit: 'Total Profit',
    totalExpenses: 'Total Expenses',
    cashflow: 'Cashflow',
    cashflowSub: 'Money in against money out, last 7 days',
    moneyIn: 'In',
    moneyOut: 'Out',
    cashflowHint: 'Total for the last 7 days · tap a day',
    dayAria: (date: string, inText: string, outText: string) => `${date}: in ${inText}, out ${outText}`,
    purchaseSales: 'Purchase & Sales',
    monthByMonth: (year: number) => `${year}, month by month`,
    sales: 'Sales',
    profit: 'Profit',
    expense: 'Expense',
    show: 'Show',
    monthlySpendings: 'Monthly Spendings',
    income: 'Income',
    expenses: 'Expenses',
    noExpenses: (month: string) => `No expenses in ${month}`,
    noIncome: (month: string) => `No income in ${month}`,
    totalIncome: (month: string) => `Total income · ${month}`,
    chooseMonth: 'Choose month',
    topCustomers: 'Top Customers',
    bySales: 'By sales this period',
    viewAll: 'View all',
    customerSales: (amount: string) => `Sales ${amount}`,
    due: 'Due',
    noCustomers: 'No sales in this period yet.',
    selectPeriod: 'Select period',
    close: 'Close',
    periods: { today: 'Today', week: 'This Week', month: 'This Month', last: 'Last Month', year: 'This Year' },
    denied: 'Some figures are not shown because your account cannot open those sections.',
    error: 'Could not load the dashboard.',
    retry: 'Try again',
    incomeNames: { Sales: 'Sales', 'Other Income': 'Other Income' } as Record<string, string>,
    uncategorised: 'Uncategorised',
  },
  bn: {
    welcome: (name: string) => `আবার স্বাগতম, ${name}`,
    sub: 'ব্যবসা চালাতে যা লাগে, সব এক জায়গায়।',
    showAmounts: 'টাকার অঙ্ক দেখান',
    hideAmounts: 'টাকার অঙ্ক লুকান',
    notifications: 'নোটিফিকেশন',
    account: (name: string) => `অ্যাকাউন্ট: ${name}`,
    netProfit: 'নিট লাভ',
    withdraw: 'টাকা তুলুন',
    savings: 'সঞ্চয়',
    totalPurchase: 'মোট ক্রয়',
    totalSales: 'মোট বিক্রি',
    totalProfit: 'মোট লাভ',
    totalExpenses: 'মোট খরচ',
    cashflow: 'ক্যাশফ্লো',
    cashflowSub: 'গত ৭ দিনে টাকা আসা বনাম যাওয়া',
    moneyIn: 'আয়',
    moneyOut: 'ব্যয়',
    cashflowHint: 'গত ৭ দিনের মোট · একটা দিনে ট্যাপ করুন',
    dayAria: (date: string, inText: string, outText: string) => `${date}: আয় ${inText}, ব্যয় ${outText}`,
    purchaseSales: 'ক্রয় ও বিক্রি',
    monthByMonth: (year: number) => `${bnDigits(year)}, মাস অনুযায়ী`,
    sales: 'বিক্রি',
    profit: 'লাভ',
    expense: 'খরচ',
    show: 'দেখান',
    monthlySpendings: 'মাসিক আয়-ব্যয়',
    income: 'আয়',
    expenses: 'খরচ',
    noExpenses: (month: string) => `${month}-এ কোনো খরচ নেই`,
    noIncome: (month: string) => `${month}-এ কোনো আয় নেই`,
    totalIncome: (month: string) => `মোট আয় · ${month}`,
    chooseMonth: 'মাস বাছাই করুন',
    topCustomers: 'সেরা কাস্টমার',
    bySales: 'এই সময়ের বিক্রি অনুযায়ী',
    viewAll: 'সব দেখুন',
    customerSales: (amount: string) => `বিক্রি ${amount}`,
    due: 'বাকি',
    noCustomers: 'এই সময়ে এখনো কোনো বিক্রি নেই।',
    selectPeriod: 'সময় বাছাই করুন',
    close: 'বন্ধ করুন',
    periods: { today: 'আজ', week: 'এই সপ্তাহ', month: 'এই মাস', last: 'গত মাস', year: 'এই বছর' },
    denied: 'আপনার অ্যাকাউন্টে কিছু অংশ খোলার অনুমতি নেই, তাই সেই হিসাবগুলো দেখানো হচ্ছে না।',
    error: 'ড্যাশবোর্ড লোড করা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    incomeNames: { Sales: 'বিক্রি', 'Other Income': 'অন্যান্য আয়' } as Record<string, string>,
    uncategorised: 'শ্রেণিহীন',
  },
};
