import { bnDigits } from '@/context/LanguageContext';

// Strings for the two Expense screens. The Bangla is the Figma file's own
// where it draws a Bangla version (ExpOverviewBn, ExpNewBn, ExpCategoryNewBn).

export const EXPENSE_COPY = {
  en: {
    title: 'Expenses',
    backToMenu: 'Back to menu',
    close: 'Close',
    loadError: 'Could not load the expenses.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    ok: 'OK',
    optional: 'Optional',
    select: 'Select',
    sections: { overview: 'Overview', transactions: 'Transactions' },

    // Overview
    budget: 'Budget',
    spentThisMonth: 'Spent this month',
    spentThisYear: 'Spent this year',
    monthBudgetUsed: 'Monthly budget used',
    yearBudgetUsed: 'Yearly budget used',
    usedOf: (pct: number, budget: string) => `${pct}% of ${budget} budget`,
    noMonthBudget: 'No monthly budget set',
    noYearBudget: 'No yearly budget set',
    left: (amount: string) => `${amount} left`,
    over: (amount: string) => `${amount} over`,
    allTimeSpend: 'All-time spend',
    categories: 'Categories',
    catCount: (n: number) => String(n),
    byCategory: 'Spending by category',
    allTime: 'All time',
    top: 'Top',
    pct: (value: number) => `${(Math.round(value * 10) / 10).toFixed(1)}%`,
    budgetLine: (budget: string, pct: number) => `Budget ${budget}/month · ${pct}% used this month`,
    moreCategories: (n: number) => (n === 1 ? '1 more category' : `${n} more categories`),
    noSpendingYet: 'No spending yet',
    rowLabel: (name: string, amount: string, share: string) => `${name}, ${amount}, ${share} of all expenses`,
    newCategory: 'New category',
    editCategory: 'Edit category',
    topExpense: 'Top expense',
    totalSpentShare: (share: string) => `Total spent · ${share} of all expenses`,
    thisMonth: 'This month',
    thisYear: 'This year',
    monthlyBudget: 'Monthly budget',
    yearlyBudget: 'Yearly budget',
    monthUsedLabel: 'This month’s budget used',
    usedText: (pct: number, left: string) => `${pct}% of this month’s budget used · ${left} left`,
    setBudget: 'Set a monthly budget',
    setBudgetHint: 'Track how much of it is used each month',
    viewTransactions: 'View transactions',
    deleteCategory: 'Delete category',
    blockedTitle: (name: string) => `${name} can’t be deleted`,
    blockedText: (amount: string) => `It has ${amount} of expenses. Move them to another category first, then delete it.`,
    deleteCategoryTitle: (name: string) => `Delete ${name}?`,
    deleteCategoryText: 'It has no expenses yet. This can’t be undone.',
    categoryName: 'Category name *',
    namePlaceholder: 'e.g. Transport',
    color: 'Color',
    colors: ['Red', 'Amber', 'Blue', 'Green', 'Purple', 'Pink', 'Gray', 'Teal', 'Orange', 'Cyan'],
    monthlyBudgetField: 'Monthly budget (৳)',
    yearlyHelp: (amount: string) => `Yearly budget ${amount} · 12 × monthly`,
    noBudgetHelp: 'Leave empty if you don’t budget this category.',
    errName: 'Enter a category name',
    errNameTaken: (name: string) => `“${name}” already exists`,
    errBudget: 'Enter a valid amount',
    categoryAdded: (name: string) => `${name} added`,
    categoryUpdated: (name: string) => `${name} updated`,
    categoryDeleted: (name: string) => `${name} deleted`,
    linkedCategory: 'This category has expenses. Delete or move them first.',

    // Transactions
    printList: 'Print this list',
    searchLabel: 'Search expenses',
    searchPlaceholder: 'Search category, account or note',
    filtersLabel: 'Filters',
    filterMonth: 'Month',
    allMonths: 'All months',
    filterCategory: 'Category',
    allCategories: 'All categories',
    totalSpent: 'Total spent',
    catMonth: (cat: string, month: string) => `${cat} · ${month}`,
    catAllTime: (cat: string) => `${cat} · all time`,
    spentIn: (month: string) => `Spent in ${month}`,
    matching: (q: string) => `Matching “${q}”`,
    clearFilters: 'Clear filters',
    countExpenses: (n: number) => (n === 1 ? '1 expense' : `${n} expenses`),
    emptyFiltered: 'No expenses match these filters.',
    emptyAll: 'No expenses yet.',
    noAccount: 'No account · not paid out',
    noAccountShort: 'No account',
    sources: { payroll: 'Payroll', discount: 'Sales', damage: 'Damage' },
    payrollLine: (payment: string, who: string, period: string) => [payment, who, period].filter(Boolean).join(' · '),
    dueDiscount: (who: string) => ['Customer due discount', who].filter(Boolean).join(' · '),
    payrollFrom: (payment: string, who: string, period: string) =>
      `Created automatically from payroll — ${payment.toLowerCase()} for ${who}${period ? `, ${period}` : ''}.`,
    discountFrom: (who: string) => `Created automatically from a customer due discount${who ? ` — ${who}` : ''}.`,
    damageFrom: 'Created from a damage entry.',
    loadOlder: 'Load older',
    newExpense: 'New expense',
    editExpense: 'Edit expense',
    deleteExpense: 'Delete expense',
    options: (cat: string, amount: string, date: string) => `Options for ${cat}, ${amount}, ${date}`,
    deleteTitle: 'Delete this expense?',
    deleteWhat: (amount: string, cat: string, date: string) => `${amount} for ${cat} on ${date}.`,
    goesBack: (amount: string, account: string) => ` ${amount} goes back to ${account}.`,
    payrollStays: ' The payroll record stays, so check it too.',
    category: 'Category *',
    amount: 'Amount (৳) *',
    date: 'Date',
    paymentAccount: 'Payment account *',
    accountHelp: 'The account the money was paid from.',
    notes: 'Notes',
    errCategory: 'Choose a category',
    errAmount: 'Enter an amount more than 0',
    errAccount: 'Choose the account it was paid from',
    expenseSaved: (amount: string, cat: string) => `Saved · ${amount} for ${cat}`,
    expenseUpdated: 'Expense updated',
    expenseDeleted: 'Expense deleted',
    printTitle: 'Expense transactions',
    colNo: '#',
    colDate: 'Date',
    colCategory: 'Category',
    colAmount: 'Amount',
    colAccount: 'Account',
    colNotes: 'Notes',
    total: 'Total',
  },
  bn: {
    title: 'খরচ',
    backToMenu: 'মেনুতে ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'খরচের হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    ok: 'ঠিক আছে',
    optional: 'ঐচ্ছিক',
    select: 'বাছাই করুন',
    sections: { overview: 'ওভারভিউ', transactions: 'লেনদেন' },

    budget: 'বাজেট',
    spentThisMonth: 'এই মাসে খরচ',
    spentThisYear: 'এই বছরে খরচ',
    monthBudgetUsed: 'মাসিক বাজেটের কত খরচ হয়েছে',
    yearBudgetUsed: 'বাৎসরিক বাজেটের কত খরচ হয়েছে',
    usedOf: (pct: number, budget: string) => `বাজেট ${budget}-এর ${bnDigits(pct)}%`,
    noMonthBudget: 'মাসিক বাজেট ঠিক করা নেই',
    noYearBudget: 'বাৎসরিক বাজেট ঠিক করা নেই',
    left: (amount: string) => `বাকি ${amount}`,
    over: (amount: string) => `${amount} বেশি`,
    allTimeSpend: 'সব মিলিয়ে খরচ',
    categories: 'খাত',
    catCount: (n: number) => `${bnDigits(n)}টি`,
    byCategory: 'খাত অনুযায়ী খরচ',
    allTime: 'সব সময়',
    top: 'শীর্ষ',
    pct: (value: number) => `${bnDigits((Math.round(value * 10) / 10).toFixed(1))}%`,
    budgetLine: (budget: string, pct: number) => `বাজেট ${budget}/মাস · এ মাসে ${bnDigits(pct)}% খরচ হয়েছে`,
    moreCategories: (n: number) => `আরও ${bnDigits(n)}টি খাত`,
    noSpendingYet: 'এখনো খরচ হয়নি',
    rowLabel: (name: string, amount: string, share: string) => `${name}, ${amount}, সব খরচের ${share}`,
    newCategory: 'নতুন খাত',
    editCategory: 'খাত সম্পাদনা',
    topExpense: 'সবচেয়ে বেশি খরচ',
    totalSpentShare: (share: string) => `মোট খরচ · সব খরচের ${share}`,
    thisMonth: 'এই মাস',
    thisYear: 'এই বছর',
    monthlyBudget: 'মাসিক বাজেট',
    yearlyBudget: 'বাৎসরিক বাজেট',
    monthUsedLabel: 'এ মাসের বাজেটের কত খরচ হয়েছে',
    usedText: (pct: number, left: string) => `এ মাসের বাজেটের ${bnDigits(pct)}% খরচ হয়েছে · বাকি ${left}`,
    setBudget: 'মাসিক বাজেট ঠিক করুন',
    setBudgetHint: 'প্রতি মাসে কতটা খরচ হলো দেখুন',
    viewTransactions: 'লেনদেন দেখুন',
    deleteCategory: 'খাত মুছুন',
    blockedTitle: (name: string) => `${name} মোছা যাবে না`,
    blockedText: (amount: string) => `এতে ${amount} খরচ আছে। আগে সেগুলো অন্য খাতে সরান, তারপর মুছুন।`,
    deleteCategoryTitle: (name: string) => `${name} মুছবেন?`,
    deleteCategoryText: 'এতে এখনো কোনো খরচ নেই। এটা আর ফেরানো যাবে না।',
    categoryName: 'খাতের নাম *',
    namePlaceholder: 'যেমন: যাতায়াত',
    color: 'রং',
    colors: ['লাল', 'হলুদ', 'নীল', 'সবুজ', 'বেগুনি', 'গোলাপি', 'ধূসর', 'টিল', 'কমলা', 'আকাশি'],
    monthlyBudgetField: 'মাসিক বাজেট (৳)',
    yearlyHelp: (amount: string) => `বছরে বাজেট ${amount} · মাসিক × ১২`,
    noBudgetHelp: 'এই খাতে বাজেট না রাখলে খালি রাখুন।',
    errName: 'খাতের নাম লিখুন',
    errNameTaken: (name: string) => `“${name}” নামে একটা খাত আগে থেকেই আছে`,
    errBudget: 'সঠিক পরিমাণ লিখুন',
    categoryAdded: (name: string) => `${name} যোগ হয়েছে`,
    categoryUpdated: (name: string) => `${name} আপডেট হয়েছে`,
    categoryDeleted: (name: string) => `${name} মুছে ফেলা হয়েছে`,
    linkedCategory: 'এই খাতে খরচ আছে। আগে সেগুলো মুছুন বা সরান।',

    printList: 'তালিকা প্রিন্ট করুন',
    searchLabel: 'খরচ খুঁজুন',
    searchPlaceholder: 'খাত, অ্যাকাউন্ট বা নোট খুঁজুন',
    filtersLabel: 'ফিল্টার',
    filterMonth: 'মাস',
    allMonths: 'সব মাস',
    filterCategory: 'খাত',
    allCategories: 'সব খাত',
    totalSpent: 'মোট খরচ',
    catMonth: (cat: string, month: string) => `${cat} · ${month}`,
    catAllTime: (cat: string) => `${cat} · সব সময়`,
    spentIn: (month: string) => `${month}-এ খরচ`,
    matching: (q: string) => `“${q}” মিলেছে`,
    clearFilters: 'ফিল্টার মুছুন',
    countExpenses: (n: number) => `${bnDigits(n)}টি খরচ`,
    emptyFiltered: 'এই ফিল্টারে কোনো খরচ নেই।',
    emptyAll: 'এখনো কোনো খরচ নেই।',
    noAccount: 'অ্যাকাউন্ট নেই · টাকা দেওয়া হয়নি',
    noAccountShort: 'অ্যাকাউন্ট নেই',
    sources: { payroll: 'বেতন', discount: 'বিক্রি', damage: 'ড্যামেজ' },
    payrollLine: (payment: string, who: string, period: string) => [payment, who, period].filter(Boolean).join(' · '),
    dueDiscount: (who: string) => ['কাস্টমারের বাকিতে ছাড়', who].filter(Boolean).join(' · '),
    payrollFrom: (payment: string, who: string, period: string) =>
      `বেতন থেকে নিজে থেকে তৈরি — ${who}${period ? `, ${period}` : ''}-এর ${payment}।`,
    discountFrom: (who: string) => `কাস্টমারের বাকিতে ছাড় থেকে নিজে থেকে তৈরি${who ? ` — ${who}` : ''}।`,
    damageFrom: 'ড্যামেজ এন্ট্রি থেকে তৈরি।',
    loadOlder: 'আরও পুরোনো দেখুন',
    newExpense: 'নতুন খরচ',
    editExpense: 'খরচ সম্পাদনা',
    deleteExpense: 'খরচ মুছুন',
    options: (cat: string, amount: string, date: string) => `${cat}, ${amount}, ${date}: আরও অপশন`,
    deleteTitle: 'এই খরচ মুছবেন?',
    deleteWhat: (amount: string, cat: string, date: string) => `${date}-এ ${cat}-এ ${amount}।`,
    goesBack: (amount: string, account: string) => ` ${amount} আবার ${account}-এ ফিরে যাবে।`,
    payrollStays: ' বেতনের রেকর্ডটা থেকে যাবে, সেটাও দেখে নিন।',
    category: 'খাত *',
    amount: 'পরিমাণ (৳) *',
    date: 'তারিখ',
    paymentAccount: 'পেমেন্ট অ্যাকাউন্ট *',
    accountHelp: 'এই অ্যাকাউন্টের ব্যালেন্স থেকে টাকা কাটা হবে।',
    notes: 'নোট',
    errCategory: 'খাত বেছে নিন',
    errAmount: '০-এর বেশি পরিমাণ লিখুন',
    errAccount: 'কোন অ্যাকাউন্ট থেকে টাকা দিয়েছেন, বেছে নিন',
    expenseSaved: (amount: string, cat: string) => `সেভ হয়েছে · ${cat}-এ ${amount}`,
    expenseUpdated: 'খরচ আপডেট হয়েছে',
    expenseDeleted: 'খরচ মুছে ফেলা হয়েছে',
    printTitle: 'খরচের লেনদেন',
    colNo: '#',
    colDate: 'তারিখ',
    colCategory: 'খাত',
    colAmount: 'পরিমাণ',
    colAccount: 'অ্যাকাউন্ট',
    colNotes: 'নোট',
    total: 'মোট',
  },
};
