// Strings for the Purchase screens, their sheets and the order form. The
// words follow the website's locales (purchase_*, purchaseLedger_*) and its
// Purchase Orders, Ledger and Product Received pages, with the app's সাপ্লায়ার.

export const PURCHASE_COPY = {
  en: {
    title: 'Purchase',
    backToMenu: 'Back to menu',
    back: 'Back',
    close: 'Close',
    loadError: 'Could not load purchases.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    optional: 'Optional',
    date: 'Date',
    notes: 'Notes',
    showMore: 'Show more',
    searchLabel: 'Search',
    sections: { ledger: 'Invoices', receive: 'Receive' },
    periods: { all: 'All time', thisMonth: 'This month', lastMonth: 'Last month', thisYear: 'This year' },
    periodLabel: 'Period',
    statuses: { pending: 'Pending', partial: 'Partly received', received: 'Received' },
    statusLabel: 'Status',
    allStatuses: 'All',
    pcs: (shown: string) => `${shown} pcs`,

    searchInvoices: 'Invoice no or supplier',
    countInvoices: (n: number, shown: string) => (n === 1 ? '1 invoice' : `${shown} invoices`),
    totalShown: 'Grand total',
    allSuppliers: 'All suppliers',
    filterSupplier: 'Supplier',
    noInvoices: 'No purchase invoices here.',
    newOrder: 'New purchase',
    invoice: 'Invoice',
    lineMath: (qty: string, each: string, total: string) => `${qty} × ${each} = ${total}`,
    lineMeta: (dp: string, pct: string, sp: string) => `DP ${dp} − ${pct}% · SP ${sp}`,
    receivedOf: (back: string, qty: string) => `${back} of ${qty} received`,
    totalDp: 'Total DP amount',
    regularDiscount: 'Regular discount',
    specialDiscount: 'Special discount (SP)',
    grandTotal: 'Grand total',
    receiveAll: 'Receive everything still due',
    receiveAllTitle: 'Receive the whole order?',
    receiveAllText: (n: string) => `${n} piece(s) still due go into stock now, dated today.`,
    receiveAllConfirm: 'Receive',
    receivedAll: 'Received into stock',
    sharePdf: 'Share PDF',
    print: 'Print',
    deleteInvoice: 'Delete invoice',
    deleteTitle: (si: string) => `Delete ${si}?`,
    deleteText: 'It moves to the recycle bin. Stock received against it is taken back out and the supplier balance is recalculated. This is refused if any of those goods have already been sold.',
    deleted: 'Purchase invoice deleted',
    colNo: '#',
    colCode: 'Code',
    colProduct: 'Product',
    colDp: 'DP',
    colDiscount: 'Disc %',
    colActual: 'Actual DP',
    colQty: 'Qty',
    colTotal: 'Total',
    colSp: 'SP',
    colDeposit: 'Deposit',
    voucherTitle: (si: string) => `Purchase invoice ${si}`,

    searchLines: 'Product, code, invoice or supplier',
    countLines: (n: number, shown: string) => (n === 1 ? '1 line' : `${shown} lines`),
    stillDue: (shown: string) => `${shown} still due`,
    noLines: 'Nothing here.',
    ordered: 'Ordered',
    receivedLabel: 'Received',
    due: 'Due',
    actualDp: 'Actual DP',
    receiveTitle: 'Receive',
    howMany: 'How many arrived *',
    receivedBy: 'Received by',
    receivedByPlaceholder: 'Who took delivery',
    errReceive: (n: string) => `Enter 1 to ${n}`,
    received: 'Received into stock',

    formTitle: 'New purchase order',
    siNo: 'SI no *',
    supplierField: 'Supplier *',
    chooseSupplier: 'Choose supplier',
    searchSuppliers: 'Search suppliers',
    noSuppliers: 'No supplier matches.',
    previousDue: (amount: string) => `Owed to this supplier before this order: ${amount}`,
    previousAdvance: (amount: string) => `This supplier holds ${amount} of ours in advance.`,
    status: 'Status',
    statusPendingSub: 'Goods not here yet',
    statusReceivedSub: 'Adds to stock now',
    products: 'Products',
    addProduct: 'Add product',
    chooseProduct: 'Choose product',
    removeLine: 'Remove',
    qty: 'Qty *',
    dp: 'DP (৳) *',
    discountPct: 'Disc %',
    spPercent: 'SP % for the whole order',
    spHint: 'The incentive the supplier gives back, worked out on every line.',
    errSupplier: 'Choose a supplier',
    errSiNo: 'Enter an SI no',
    errItems: 'Add at least one product',
    errQty: 'Qty: a whole number above 0',
    errDp: 'DP: more than 0',
    errDiscount: 'Disc %: 0 to 100',
    errPercent: 'Enter 0 to 100',
    gross: 'DP amount',
    discount: 'Discount',
    totalBill: 'Total',
    spTotal: 'SP',
    deposit: 'Deposit (owed)',
    owedAfter: (amount: string) => `Owed to this supplier after this order: ${amount}`,
    advanceAfter: (amount: string) => `Advance left with this supplier after this order: ${amount}`,
    pendingNote: 'It waits under Receive; stock goes up only as the goods arrive.',
    receiveNowTitle: 'Receive this order into stock?',
    receiveNowText: (n: string) => `Saving as Received adds ${n} item(s) to your stock right away. Choose Pending if the goods have not arrived yet.`,
    receiveNowConfirm: 'Yes, receive into stock',
    saved: 'Purchase order saved',
    savedReceived: 'Purchase order saved and received into stock',
    savedNotReceived: (error: string) => `Purchase order saved, but not received into stock (${error}). Receive it from the Receive tab.`,
    editInvoice: 'Edit invoice',
    editTitle: 'Edit purchase invoice',
    notFound: 'This invoice is no longer here.',
    spEditHint: 'Lines you change are priced at this percentage; the others keep what they were saved at.',
    errBelowReceived: (n: string) => `Qty: not below the ${n} already received`,
    receivedCost: 'Some of it is already in stock, at the price it came in at - changing the price here does not change that.',
    paidSoFar: 'Paid on this bill so far',
    dueOnBill: 'Still due on this bill',
    updated: (si: string) => `${si} updated`,
    partlySaved: (error: string) => `Part of the change was saved before this failed (${error}). Open the invoice again to check it.`,
  },
  bn: {
    title: 'ক্রয়',
    backToMenu: 'মেনুতে ফিরুন',
    back: 'ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'ক্রয়ের হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    optional: 'ঐচ্ছিক',
    date: 'তারিখ',
    notes: 'নোট',
    showMore: 'আরও দেখুন',
    searchLabel: 'খুঁজুন',
    sections: { ledger: 'ইনভয়েস', receive: 'পণ্য গ্রহণ' },
    periods: { all: 'সব সময়', thisMonth: 'এই মাস', lastMonth: 'গত মাস', thisYear: 'এই বছর' },
    periodLabel: 'সময়',
    statuses: { pending: 'অপেক্ষমান', partial: 'আংশিক গৃহীত', received: 'গৃহীত' },
    statusLabel: 'স্ট্যাটাস',
    allStatuses: 'সব',
    pcs: (shown: string) => `${shown} পিস`,

    searchInvoices: 'ইনভয়েস নং বা সাপ্লায়ার',
    countInvoices: (_n: number, shown: string) => `${shown}টি ইনভয়েস`,
    totalShown: 'সর্বমোট',
    allSuppliers: 'সব সাপ্লায়ার',
    filterSupplier: 'সাপ্লায়ার',
    noInvoices: 'এখানে কোনো ক্রয় ইনভয়েস নেই।',
    newOrder: 'নতুন ক্রয়',
    invoice: 'ইনভয়েস',
    lineMath: (qty: string, each: string, total: string) => `${qty} × ${each} = ${total}`,
    lineMeta: (dp: string, pct: string, sp: string) => `DP ${dp} − ${pct}% · SP ${sp}`,
    receivedOf: (back: string, qty: string) => `${qty}টির মধ্যে ${back}টি গৃহীত`,
    totalDp: 'মোট DP পরিমাণ',
    regularDiscount: 'সাধারণ ছাড়',
    specialDiscount: 'স্পেশাল ছাড় (SP)',
    grandTotal: 'সর্বমোট',
    receiveAll: 'বাকি সব গ্রহণ করুন',
    receiveAllTitle: 'পুরো অর্ডার গ্রহণ করবেন?',
    receiveAllText: (n: string) => `বাকি ${n}টি পিস আজকের তারিখে এখনই স্টকে যোগ হবে।`,
    receiveAllConfirm: 'গ্রহণ করুন',
    receivedAll: 'স্টকে যোগ হয়েছে',
    sharePdf: 'PDF শেয়ার',
    print: 'প্রিন্ট',
    deleteInvoice: 'ইনভয়েস মুছুন',
    deleteTitle: (si: string) => `${si} মুছবেন?`,
    deleteText: 'এটা রিসাইকেল বিনে যাবে। এর বিপরীতে গৃহীত স্টক আবার বাদ যাবে আর সাপ্লায়ারের ব্যালেন্স নতুন করে হিসাব হবে। ওই মালের কিছু বিক্রি হয়ে গেলে মোছা যাবে না।',
    deleted: 'ক্রয় ইনভয়েস মুছে ফেলা হয়েছে',
    colNo: '#',
    colCode: 'কোড',
    colProduct: 'পণ্য',
    colDp: 'DP',
    colDiscount: 'ছাড়%',
    colActual: 'প্রকৃত DP',
    colQty: 'পরিমাণ',
    colTotal: 'মোট',
    colSp: 'SP',
    colDeposit: 'জমা',
    voucherTitle: (si: string) => `ক্রয় ইনভয়েস ${si}`,

    searchLines: 'পণ্য, কোড, ইনভয়েস বা সাপ্লায়ার',
    countLines: (_n: number, shown: string) => `${shown}টি লাইন`,
    stillDue: (shown: string) => `${shown}টি বাকি`,
    noLines: 'এখানে কিছু নেই।',
    ordered: 'অর্ডার',
    receivedLabel: 'গৃহীত',
    due: 'বাকি',
    actualDp: 'প্রকৃত DP',
    receiveTitle: 'পণ্য গ্রহণ',
    howMany: 'কতগুলো এসেছে *',
    receivedBy: 'কে বুঝে নিয়েছেন',
    receivedByPlaceholder: 'যিনি মাল বুঝে নিয়েছেন',
    errReceive: (n: string) => `১ থেকে ${n} লিখুন`,
    received: 'স্টকে যোগ হয়েছে',

    formTitle: 'নতুন ক্রয় অর্ডার',
    siNo: 'SI নং *',
    supplierField: 'সাপ্লায়ার *',
    chooseSupplier: 'সাপ্লায়ার বাছুন',
    searchSuppliers: 'সাপ্লায়ার খুঁজুন',
    noSuppliers: 'কোনো সাপ্লায়ার মেলেনি।',
    previousDue: (amount: string) => `এই অর্ডারের আগে এই সাপ্লায়ারের দেনা: ${amount}`,
    previousAdvance: (amount: string) => `এই সাপ্লায়ারের কাছে আমাদের ${amount} অগ্রিম আছে।`,
    status: 'স্ট্যাটাস',
    statusPendingSub: 'মাল এখনো আসেনি',
    statusReceivedSub: 'এখনই স্টকে যোগ হবে',
    products: 'পণ্য',
    addProduct: 'পণ্য যোগ করুন',
    chooseProduct: 'পণ্য বাছুন',
    removeLine: 'সরান',
    qty: 'পরিমাণ *',
    dp: 'DP (৳) *',
    discountPct: 'ছাড়%',
    spPercent: 'পুরো অর্ডারের SP %',
    spHint: 'সাপ্লায়ার যে ইনসেনটিভ ফেরত দেয়, প্রতিটা লাইনে হিসাব হবে।',
    errSupplier: 'সাপ্লায়ার বাছুন',
    errSiNo: 'SI নং দিন',
    errItems: 'অন্তত একটা পণ্য যোগ করুন',
    errQty: 'পরিমাণ: ০-এর বেশি পূর্ণ সংখ্যা',
    errDp: 'DP: ০-এর বেশি',
    errDiscount: 'ছাড়%: ০ থেকে ১০০',
    errPercent: '০ থেকে ১০০ লিখুন',
    gross: 'DP পরিমাণ',
    discount: 'ছাড়',
    totalBill: 'মোট',
    spTotal: 'SP',
    deposit: 'জমা (দেনা)',
    owedAfter: (amount: string) => `এই অর্ডারের পর এই সাপ্লায়ারের দেনা: ${amount}`,
    advanceAfter: (amount: string) => `এই অর্ডারের পর সাপ্লায়ারের কাছে অগ্রিম থাকবে: ${amount}`,
    pendingNote: 'এটা পণ্য গ্রহণ ট্যাবে অপেক্ষা করবে; মাল এলে তবেই স্টক বাড়বে।',
    receiveNowTitle: 'এই অর্ডার স্টকে নেবেন?',
    receiveNowText: (n: string) => `গৃহীত হিসেবে সেভ করলে ${n}টি পণ্য এখনই স্টকে যোগ হবে। মাল না এলে অপেক্ষমান বাছুন।`,
    receiveNowConfirm: 'হ্যাঁ, স্টকে নিন',
    saved: 'ক্রয় অর্ডার সেভ হয়েছে',
    savedReceived: 'ক্রয় অর্ডার সেভ হয়েছে, স্টকে যোগ হয়েছে',
    savedNotReceived: (error: string) => `ক্রয় অর্ডার সেভ হয়েছে, কিন্তু স্টকে নেওয়া যায়নি (${error})। পণ্য গ্রহণ ট্যাব থেকে নিন।`,
    editInvoice: 'ইনভয়েস এডিট করুন',
    editTitle: 'ক্রয় ইনভয়েস সম্পাদনা',
    notFound: 'এই ইনভয়েসটি আর নেই।',
    spEditHint: 'যে লাইন বদলাবেন সেগুলোর দাম এই হারে হবে; বাকিগুলো সেভ করা হিসাবেই থাকবে।',
    errBelowReceived: (n: string) => `পরিমাণ: আগেই পাওয়া ${n}টির কম নয়`,
    receivedCost: 'এর কিছু আগেই স্টকে এসেছে, তখনকার দামে - এখানে দাম বদলালে সেটা বদলায় না।',
    paidSoFar: 'এই বিলে এ পর্যন্ত পরিশোধ',
    dueOnBill: 'এই বিলে এখনো বাকি',
    updated: (si: string) => `${si} আপডেট হয়েছে`,
    partlySaved: (error: string) => `ব্যর্থ হওয়ার আগে কিছু পরিবর্তন সেভ হয়ে গেছে (${error})। ইনভয়েসটি আবার খুলে দেখে নিন।`,
  },
};
