// Strings for parked sales and purchase orders - the drafts lists and the
// forms that park and reopen them. The words follow the website's Draft Sales
// and Draft Purchase pages and the toasts of its two forms.

export const DRAFT_COPY = {
  en: {
    close: 'Close',
    cancel: 'Cancel',
    delete: 'Delete',
    intro: {
      sale: 'Invoices saved part-way, waiting to be finished. The website shows the same list.',
      purchase_order: 'Purchase orders saved part-way, waiting to be finished. The website shows the same list.',
    },
    noDrafts: 'Nothing parked here. Anything saved as a draft shows up in this list.',
    untitled: { sale: 'Walk-in customer', purchase_order: 'No supplier' },
    amount: { sale: 'Payable today', purchase_order: 'Total' },
    edited: (who: string, when: string) => (who ? `Last edited by ${who} · ${when}` : `Last edited ${when}`),
    open: 'Open and carry on',
    deleteDraft: 'Delete draft',
    deleteTitle: 'Delete this draft?',
    deleteText: (title: string) => `${title} will be thrown away. Nothing ordered or sold is affected - a draft has never reached your stock or accounts.`,
    deleted: 'Draft deleted',
    save: 'Save as draft',
    update: 'Update draft',
    saved: 'Saved to drafts',
    dropped: (n: string) => `${n} line(s) typed in rather than picked from the products could not be brought back.`,
    stale: 'This draft was saved by an older version of the app and can no longer be opened. Please enter it again.',
    gone: 'This draft is no longer here.',
    notCleared: 'The draft could not be removed - delete it from Drafts.',
    needSupplier: 'Choose a supplier before saving this as a draft',
    supplierGone: "This draft's supplier no longer exists - please pick another.",
  },
  bn: {
    close: 'বন্ধ করুন',
    cancel: 'বাতিল',
    delete: 'মুছুন',
    intro: {
      sale: 'অর্ধেক করা ইনভয়েস, শেষ করার অপেক্ষায়। ওয়েবসাইটেও একই তালিকা দেখায়।',
      purchase_order: 'অর্ধেক করা ক্রয় অর্ডার, শেষ করার অপেক্ষায়। ওয়েবসাইটেও একই তালিকা দেখায়।',
    },
    noDrafts: 'এখানে কিছু রাখা নেই। ড্রাফট হিসেবে রাখা সবকিছু এই তালিকায় দেখাবে।',
    untitled: { sale: 'ওয়াক-ইন কাস্টমার', purchase_order: 'সাপ্লায়ার নেই' },
    amount: { sale: 'আজ পরিশোধযোগ্য', purchase_order: 'মোট' },
    edited: (who: string, when: string) => (who ? `শেষ এডিট ${who} · ${when}` : `শেষ এডিট ${when}`),
    open: 'খুলে কাজ চালিয়ে যান',
    deleteDraft: 'ড্রাফট মুছুন',
    deleteTitle: 'এই ড্রাফট মুছবেন?',
    deleteText: (title: string) => `${title} বাদ দেওয়া হবে। কোনো অর্ডার বা বিক্রিতে প্রভাব পড়বে না - ড্রাফট কখনো স্টক বা অ্যাকাউন্টে যায়নি।`,
    deleted: 'ড্রাফট মুছে ফেলা হয়েছে',
    save: 'ড্রাফট হিসেবে রাখুন',
    update: 'ড্রাফট আপডেট করুন',
    saved: 'ড্রাফটে রাখা হয়েছে',
    dropped: (n: string) => `পণ্যের তালিকা থেকে না বেছে হাতে লেখা ${n}টি লাইন ফিরিয়ে আনা যায়নি।`,
    stale: 'এই ড্রাফটটি অ্যাপের পুরনো সংস্করণে রাখা, তাই আর খোলা যাবে না। আবার লিখে নিন।',
    gone: 'এই ড্রাফটটি আর নেই।',
    notCleared: 'ড্রাফটটি মোছা যায়নি - ড্রাফট থেকে মুছে দিন।',
    needSupplier: 'ড্রাফট হিসেবে রাখার আগে সাপ্লায়ার বাছুন',
    supplierGone: 'এই ড্রাফটের সাপ্লায়ার আর নেই - অন্য একজন বাছুন।',
  },
};
