// Strings for Marketing - the SMS composer, its recipient sheet, the figures
// and the failures. The website's Marketing page writes its words inline, in
// English; these follow them, with the Bangla written for the app.

export const MARKETING_COPY = {
  en: {
    title: 'Marketing',
    backToMenu: 'Back to menu',
    close: 'Close',
    cancel: 'Cancel',
    retry: 'Try again',
    ownerOnly: 'SMS is sent from the owner’s credits, so only the owner can send it.',
    balance: 'SMS credits',
    sentToday: 'Sent today',
    campaigns: 'This month',
    deliveryRate: 'Delivered',
    composer: 'Write an SMS',
    message: 'Message *',
    messagePlaceholder: 'What do you want to tell them?',
    counter: (chars: string, segments: string, unicode: boolean) => `${chars} characters · ${segments} SMS each${unicode ? ' · Bangla' : ''}`,
    recipients: 'Recipients *',
    chooseRecipients: 'Choose recipients',
    chosen: (n: string, phones: string) => `${n} chosen · ${phones} with a phone`,
    cost: (credits: string) => `About ${credits} credits`,
    notEnough: (need: string, have: string) => `This needs ${need} credits; you have ${have}.`,
    send: 'Send SMS',
    confirmTitle: 'Send this SMS?',
    confirmText: (people: string, credits: string) => `It goes to ${people} number(s) and uses about ${credits} credits.`,
    sent: (people: string, credits: string) => `SMS sent to ${people} (${credits} credits used)`,
    errMessage: 'Write an SMS message',
    errRecipients: 'Choose at least one recipient with a phone',
    failures: 'Not delivered',
    failuresHint: 'The gateway refused these; no credits were used.',
    pickTitle: 'Recipients',
    search: 'Name, phone or detail',
    types: { customer: 'Customers', supplier: 'Suppliers', employee: 'Employees', contact: 'Contact list', lead: 'Leads' },
    selectShown: 'Select all shown',
    clearShown: 'Clear all shown',
    noPhone: 'No phone',
    noContacts: 'No contacts match.',
    done: 'Done',
    loadError: 'Could not load contacts.',
  },
  bn: {
    title: 'মার্কেটিং',
    backToMenu: 'মেনুতে ফিরুন',
    close: 'বন্ধ করুন',
    cancel: 'বাতিল',
    retry: 'আবার চেষ্টা করুন',
    ownerOnly: 'SMS মালিকের ক্রেডিট থেকে যায়, তাই শুধু মালিক পাঠাতে পারেন।',
    balance: 'SMS ক্রেডিট',
    sentToday: 'আজ পাঠানো',
    campaigns: 'এই মাসে',
    deliveryRate: 'পৌঁছেছে',
    composer: 'SMS লিখুন',
    message: 'মেসেজ *',
    messagePlaceholder: 'কী জানাতে চান?',
    counter: (chars: string, segments: string, unicode: boolean) => `${chars} অক্ষর · প্রতিজনে ${segments}টি SMS${unicode ? ' · বাংলা' : ''}`,
    recipients: 'প্রাপক *',
    chooseRecipients: 'প্রাপক বাছুন',
    chosen: (n: string, phones: string) => `${n} জন বাছা হয়েছে · ${phones} জনের ফোন আছে`,
    cost: (credits: string) => `প্রায় ${credits}টি ক্রেডিট`,
    notEnough: (need: string, have: string) => `এতে ${need}টি ক্রেডিট লাগবে; আছে ${have}টি।`,
    send: 'SMS পাঠান',
    confirmTitle: 'এই SMS পাঠাবেন?',
    confirmText: (people: string, credits: string) => `এটা ${people}টি নম্বরে যাবে, প্রায় ${credits}টি ক্রেডিট লাগবে।`,
    sent: (people: string, credits: string) => `${people} জনকে SMS পাঠানো হয়েছে (${credits}টি ক্রেডিট খরচ)`,
    errMessage: 'SMS-এর মেসেজ লিখুন',
    errRecipients: 'ফোন আছে এমন অন্তত একজন প্রাপক বাছুন',
    failures: 'পৌঁছায়নি',
    failuresHint: 'গেটওয়ে এগুলো নেয়নি; কোনো ক্রেডিট খরচ হয়নি।',
    pickTitle: 'প্রাপক',
    search: 'নাম, ফোন বা বিবরণ',
    types: { customer: 'কাস্টমার', supplier: 'সাপ্লায়ার', employee: 'কর্মচারী', contact: 'কন্টাক্ট লিস্ট', lead: 'লিড' },
    selectShown: 'দেখানো সবাইকে বাছুন',
    clearShown: 'দেখানো সবাইকে বাদ দিন',
    noPhone: 'ফোন নেই',
    noContacts: 'কোনো কন্টাক্ট মেলেনি।',
    done: 'ঠিক আছে',
    loadError: 'কন্টাক্ট আনা যায়নি।',
  },
};
