// Strings for Billing & Plan - the current plan and the billing history - in
// the website's CurrentPlan and BillingHistory words. There is deliberately no
// wording for buying or renewing: the app never offers it.

export const BILLING_COPY = {
  en: {
    title: 'Billing & Plan',
    backToMenu: 'Back to menu',
    retry: 'Try again',
    currentPlan: 'Current plan',
    plans: { free_trial: 'Free Trial', monthly: 'Monthly', yearly: 'Yearly' },
    statuses: { active: 'Active', pending: 'Pending', expired: 'Expired', suspended: 'Suspended', blocked: 'Blocked', none: 'No plan', trial: 'Active' } as Record<string, string>,
    expires: 'Expires',
    daysLeft: 'Days left',
    days: (n: number, shown: string) => (n === 1 ? '1 day' : `${shown} days`),
    expired: 'Expired',
    includes: 'Your plan includes',
    smsBalance: 'SMS balance',
    spentPlans: 'Spent on plans',
    spentSms: 'Spent on SMS',
    history: 'All purchases',
    kinds: { all: 'All', plan: 'Plans', sms: 'SMS packages' },
    kindLabel: 'Type',
    planItem: (plan: string) => (plan === 'yearly' ? 'Yearly plan' : plan === 'monthly' ? 'Monthly plan' : 'Plan'),
    smsItem: 'SMS package',
    smsDetail: (n: string) => `${n} SMS credits`,
    paymentStatuses: { paid: 'Paid', pending: 'Pending', rejected: 'Rejected' } as Record<string, string>,
    trx: (id: string) => `TrxID ${id}`,
    noHistory: 'No purchases yet.',
    loadError: 'Could not load the billing history.',
  },
  bn: {
    title: 'বিল ও প্ল্যান',
    backToMenu: 'মেনুতে ফিরুন',
    retry: 'আবার চেষ্টা করুন',
    currentPlan: 'বর্তমান প্ল্যান',
    plans: { free_trial: 'ফ্রি ট্রায়াল', monthly: 'মাসিক', yearly: 'বার্ষিক' },
    statuses: { active: 'অ্যাক্টিভ', pending: 'অপেক্ষমান', expired: 'মেয়াদ শেষ', suspended: 'স্থগিত', blocked: 'বন্ধ', none: 'প্ল্যান নেই', trial: 'অ্যাক্টিভ' } as Record<string, string>,
    expires: 'মেয়াদ শেষ',
    daysLeft: 'বাকি দিন',
    days: (_n: number, shown: string) => `${shown} দিন`,
    expired: 'শেষ',
    includes: 'আপনার প্ল্যানে যা আছে',
    smsBalance: 'এসএমএস ব্যালেন্স',
    spentPlans: 'প্ল্যানে মোট খরচ',
    spentSms: 'এসএমএসে মোট খরচ',
    history: 'সব কেনাকাটা',
    kinds: { all: 'সব', plan: 'প্ল্যান', sms: 'এসএমএস প্যাকেজ' },
    kindLabel: 'ধরন',
    planItem: (plan: string) => (plan === 'yearly' ? 'বার্ষিক প্ল্যান' : plan === 'monthly' ? 'মাসিক প্ল্যান' : 'প্ল্যান'),
    smsItem: 'এসএমএস প্যাকেজ',
    smsDetail: (n: string) => `${n} এসএমএস ক্রেডিট`,
    paymentStatuses: { paid: 'পরিশোধিত', pending: 'অপেক্ষমান', rejected: 'বাতিল' } as Record<string, string>,
    trx: (id: string) => `TrxID ${id}`,
    noHistory: 'এখনো কোনো কেনাকাটা নেই।',
    loadError: 'বিলের ইতিহাস আনা যায়নি।',
  },
};
