// Strings for the four Customers screens, their sheets and the Receive due
// form. The words follow the website's locales (customerDash_*, customers_*,
// ledger_*) and its Due Received page, with the app's own কাস্টমার.

export const CUSTOMER_COPY = {
  en: {
    title: 'Customers',
    close: 'Close',
    loadError: 'Could not load customers.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    edit: 'Edit',
    optional: 'Optional',
    back: 'Back',
    date: 'Date',
    notes: 'Notes',
    showMore: 'Show more',
    searchLabel: 'Search',
    sections: { overview: 'Overview', receipts: 'Due received', ledger: 'Ledger', list: 'Customers' },
    periods: { all: 'All time', thisMonth: 'This month', lastMonth: 'Last month', thisYear: 'This year' },
    periodLabel: 'Period',
    side: { pawna: 'Pawna', dena: 'Dena', balanced: 'Settled' },
    call: (name: string, phone: string) => `Call ${name}, ${phone}`,
    smsNotSent: (reason: string) => `SMS not sent - ${reason}.`,

    currentDue: 'Current due',
    oweCount: (n: number, shown: string) => (n === 1 ? '1 customer owes' : `${shown} customers owe`),
    customersCount: 'Customers',
    openingDue: 'Opening due',
    totalPurchase: 'Total purchase',
    discount: 'Discount',
    collections: 'Collected',
    extraDiscount: 'Discount on due collections',
    balances: 'Due by customer',
    searchAccounts: 'Name, phone or address',
    dueLabel: 'Due',
    dueFilters: { all: 'All', due: 'Owe', clear: 'Clear' },
    sortLabel: 'Sort',
    sorts: {
      due_desc: 'Most due first',
      due_asc: 'Least due first',
      purchase_desc: 'Most bought',
      collections_desc: 'Most collected',
      name_asc: 'Name A–Z',
    },
    noCustomers: 'No customers yet.',
    noMatch: 'No customer matches.',
    receiveDue: 'Receive due',
    viewLedger: 'View ledger',
    sendReminder: 'Send due reminder',
    reminderTitle: 'Send a due reminder?',
    reminderText: (phone: string, credits: string) => `This text goes to ${phone} and uses about ${credits} SMS credit(s).`,
    reminderConfirm: 'Send',
    reminderSent: 'Due reminder sent',

    totalReceived: 'Total received',
    countReceipts: (n: number, shown: string) => (n === 1 ? '1 collection' : `${shown} collections`),
    searchReceipts: 'Name, phone, receiver or amount',
    noReceipts: 'No due collections here.',
    previousDue: 'Previous due',
    received: 'Received',
    dueAfter: 'Due after',
    receivedBy: 'Received by',
    bookedUnder: 'Discount booked under',
    sharePdf: 'Share PDF',
    print: 'Print',
    deleteReceipt: 'Delete collection',
    deleteReceiptTitle: 'Delete this due collection?',
    deleteReceiptText: (amount: string) =>
      `${amount} comes off the accounts it went into and back onto the customer's due. A discount booked with it stays in Expenses - delete it there.`,
    receiptDeleted: 'Due collection deleted',
    receiptTitle: 'Money receipt',
    colAccount: 'Account',
    colAmount: 'Amount',

    formTitle: 'Receive due',
    customerField: 'Customer *',
    chooseCustomer: 'Choose customer',
    searchCustomers: 'Name or phone',
    noCustomerMatch: 'No customer matches.',
    owes: (amount: string) => `Owes ${amount}`,
    owesNothing: 'Owes nothing now.',
    paidInto: 'Paid into',
    account: 'Account *',
    chooseAccount: 'Choose account',
    amount: 'Amount (৳) *',
    removeRow: 'Remove',
    addAccount: 'Split across another account',
    discountField: 'Discount (৳)',
    discountHint: 'Written off the due and booked as an expense - no money leaves an account.',
    oneAccountWithDiscount: 'A collection with a discount goes into one account.',
    category: 'Booked under *',
    chooseCategory: 'Choose expense category',
    receiverField: 'Received by *',
    receiverPlaceholder: 'Who took the money',
    smsReceipt: 'Text the customer a receipt',
    smsReceiptSub: 'Uses your SMS credits',
    receivingNow: 'Receiving now',
    errCustomer: 'Choose a customer',
    errAccount: 'Choose an account',
    errAmount: 'Enter an amount more than 0',
    errDiscount: 'Enter 0 or more',
    errCategory: 'Choose where the discount is booked',
    errReceiver: 'Enter who took the money',
    errTooMuch: (due: string, total: string, excess: string) =>
      `The customer owes ${due}, but this adds up to ${total} - ${excess} too much. Lower it to ${due} or less.`,
    saved: 'Due collection saved',
    partSaved: (saved: string, total: string, error: string) =>
      `${saved} of ${total} payments saved; the rest were not (${error}). Check Due received before trying again.`,
    discountFailed: (error: string) => `Due collection saved, but not its discount expense (${error}). Add it in Expenses.`,
    editReceipt: 'Edit collection',
    editTitle: 'Edit due received',
    receiptGone: 'This collection is no longer here.',
    splitNoEdit: 'A collection split across accounts cannot be edited - delete it and take it again.',
    discountKept: (amount: string) => `The ${amount} discount stays as it was. To change it, delete this collection and take it again.`,
    customerLocked: 'Collected against an invoice, so its customer stays.',
    owesBesides: (amount: string) => `Owes ${amount} besides this collection`,
    updated: 'Due received updated',
    discountNotRemoved: 'Due received deleted, but its discount expense could not be removed - delete it from Expenses.',
    bulkSms: 'Due SMS to many',
    bulkTitle: 'Due SMS',
    bulkIntro: 'Everyone here owes and has a mobile number. Each gets a text with their own due.',
    bulkNoPhone: (n: string) => `${n} more owe but have no usable mobile number, so they are not listed.`,
    bulkNone: 'No customer who owes has a mobile number.',
    bulkSearch: 'Name or phone',
    selectShown: 'Select all shown',
    clearShown: 'Clear all shown',
    bulkSample: 'What the first one will read',
    bulkBalance: (n: string) => `SMS balance: ${n}`,
    bulkPick: 'Choose who to text',
    bulkSend: (n: string, credits: string) => `Send to ${n} · about ${credits} credits`,
    bulkShort: (credits: string, balance: string) => `This needs about ${credits} credits; ${balance} are left.`,
    bulkConfirmTitle: 'Send due reminders?',
    bulkConfirmText: (n: string, credits: string) => `Text ${n} customer(s) about their due? This uses about ${credits} SMS credits.`,
    bulkSending: (done: string, n: string) => `Sending ${done} of ${n}…`,
    bulkSent: (n: string) => `Due reminder sent to ${n} customer(s).`,
    bulkFailed: (n: string, reason: string) => `${n} reminder(s) not sent - ${reason}.`,
    smsOwnerOnly: 'Only the owner can send SMS.',
    smsSkipped: 'Receipt SMS skipped - the customer has no valid phone number.',
    smsSent: 'Receipt sent by SMS',

    ledgerIntro: 'Every sale and due collection for one customer, oldest first, with the due after each.',
    noPersonText: 'Choose a customer to see their ledger.',
    totalDiscount: 'Discount given',
    totalPaid: 'Paid',
    sale: 'Sale',
    collection: 'Due received',
    invoiceSale: 'Invoice sale',
    itemQty: (name: string, qty: string) => `${name} × ${qty}`,
    purchasePlus: 'Purchase (+)',
    paidMinus: 'Paid (−)',
    noTx: 'No sales or due collections yet.',
    showEarlier: 'Show earlier entries',
    ledgerTitle: (name: string) => `Customer ledger - ${name}`,
    colDate: 'Date',
    colRef: 'Reference',
    colDetails: 'Details',
    colDue: 'Due',

    searchList: 'Name, phone, email or address',
    countCustomers: (n: number, shown: string) => (n === 1 ? '1 customer' : `${shown} customers`),
    newCustomer: 'New customer',
    editCustomer: 'Edit customer',
    deleteCustomer: 'Delete customer',
    name: 'Name *',
    phone: 'Phone *',
    email: 'Email',
    address: 'Address',
    openingField: 'Opening due (৳)',
    openingHint: 'What they owed before you started with Furnify.',
    errName: 'Enter a name',
    errPhoneRequired: 'Enter a phone number',
    errPhone: 'Enter a valid 11-digit number (e.g. 01XXXXXXXXX)',
    errPhoneTaken: 'This number already belongs to another customer',
    errOpening: 'Enter 0 or more',
    errEmail: 'Enter a valid email',
    customerSaved: 'Customer saved',
    customerUpdated: 'Customer updated',
    customerDeleted: 'Customer deleted',
    linkedCustomer: 'This customer has sales or due collections, so they stay. Delete those first.',
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteText: 'It moves to the recycle bin. A customer with any sale or due collection cannot be deleted - delete those first.',
  },
  bn: {
    title: 'কাস্টমার',
    close: 'বন্ধ করুন',
    loadError: 'কাস্টমারের হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    edit: 'এডিট',
    optional: 'ঐচ্ছিক',
    back: 'ফিরুন',
    date: 'তারিখ',
    notes: 'নোট',
    showMore: 'আরও দেখুন',
    searchLabel: 'খুঁজুন',
    sections: { overview: 'সারসংক্ষেপ', receipts: 'বাকি আদায়', ledger: 'খাতা', list: 'কাস্টমার তালিকা' },
    periods: { all: 'সব সময়', thisMonth: 'এই মাস', lastMonth: 'গত মাস', thisYear: 'এই বছর' },
    periodLabel: 'সময়',
    side: { pawna: 'পাওনা', dena: 'দেনা', balanced: 'সমান' },
    call: (name: string, phone: string) => `${name}-কে কল করুন, ${phone}`,
    smsNotSent: (reason: string) => `SMS যায়নি - ${reason}।`,

    currentDue: 'বর্তমান বাকি',
    oweCount: (_n: number, shown: string) => `${shown} জন কাস্টমারের বাকি আছে`,
    customersCount: 'মোট কাস্টমার',
    openingDue: 'প্রারম্ভিক বাকি',
    totalPurchase: 'মোট ক্রয়',
    discount: 'ছাড়',
    collections: 'আদায়',
    extraDiscount: 'বাকি আদায়ে ছাড়',
    balances: 'কাস্টমার অনুযায়ী বাকি',
    searchAccounts: 'নাম, ফোন বা ঠিকানা',
    dueLabel: 'বাকি',
    dueFilters: { all: 'সব', due: 'বাকি আছে', clear: 'বাকি নেই' },
    sortLabel: 'সাজান',
    sorts: {
      due_desc: 'বেশি বাকি আগে',
      due_asc: 'কম বাকি আগে',
      purchase_desc: 'বেশি ক্রয়',
      collections_desc: 'বেশি আদায়',
      name_asc: 'নাম অনুযায়ী',
    },
    noCustomers: 'এখনো কোনো কাস্টমার নেই।',
    noMatch: 'কোনো কাস্টমার মেলেনি।',
    receiveDue: 'বাকি আদায় করুন',
    viewLedger: 'খাতা দেখুন',
    sendReminder: 'বাকির SMS পাঠান',
    reminderTitle: 'বাকির রিমাইন্ডার পাঠাবেন?',
    reminderText: (phone: string, credits: string) => `এই মেসেজ ${phone}-এ যাবে, প্রায় ${credits}টি SMS ক্রেডিট লাগবে।`,
    reminderConfirm: 'পাঠান',
    reminderSent: 'বাকির রিমাইন্ডার পাঠানো হয়েছে',

    totalReceived: 'মোট আদায়',
    countReceipts: (_n: number, shown: string) => `${shown}টি আদায়`,
    searchReceipts: 'নাম, ফোন, গ্রহণকারী বা টাকা',
    noReceipts: 'এখানে কোনো বাকি আদায় নেই।',
    previousDue: 'আগের বাকি',
    received: 'আদায়',
    dueAfter: 'বাকি রইল',
    receivedBy: 'গ্রহণকারী',
    bookedUnder: 'ছাড়ের খাত',
    sharePdf: 'PDF শেয়ার',
    print: 'প্রিন্ট',
    deleteReceipt: 'আদায় মুছুন',
    deleteReceiptTitle: 'এই বাকি আদায় মুছবেন?',
    deleteReceiptText: (amount: string) =>
      `${amount} যে অ্যাকাউন্টে গিয়েছিল সেখান থেকে বাদ যাবে, আর কাস্টমারের বাকিতে আবার যোগ হবে। এর সাথে লেখা ছাড় খরচের তালিকায় থেকে যাবে - সেটা খরচ থেকে মুছুন।`,
    receiptDeleted: 'বাকি আদায় মুছে ফেলা হয়েছে',
    receiptTitle: 'টাকা প্রাপ্তির রসিদ',
    colAccount: 'অ্যাকাউন্ট',
    colAmount: 'পরিমাণ',

    formTitle: 'বাকি আদায়',
    customerField: 'কাস্টমার *',
    chooseCustomer: 'কাস্টমার বাছুন',
    searchCustomers: 'নাম বা ফোন',
    noCustomerMatch: 'কোনো কাস্টমার মেলেনি।',
    owes: (amount: string) => `বাকি ${amount}`,
    owesNothing: 'এখন কোনো বাকি নেই।',
    paidInto: 'যে অ্যাকাউন্টে জমা',
    account: 'অ্যাকাউন্ট *',
    chooseAccount: 'অ্যাকাউন্ট বাছুন',
    amount: 'পরিমাণ (৳) *',
    removeRow: 'সরান',
    addAccount: 'আরেকটা অ্যাকাউন্টে ভাগ করুন',
    discountField: 'ছাড় (৳)',
    discountHint: 'বাকি থেকে মাফ হবে আর খরচ হিসেবে লেখা হবে - কোনো অ্যাকাউন্ট থেকে টাকা কমবে না।',
    oneAccountWithDiscount: 'ছাড় থাকলে আদায় একটা অ্যাকাউন্টেই নিতে হবে।',
    category: 'খরচের খাত *',
    chooseCategory: 'খরচের খাত বাছুন',
    receiverField: 'গ্রহণকারী *',
    receiverPlaceholder: 'যিনি টাকা নিয়েছেন',
    smsReceipt: 'কাস্টমারকে রসিদ SMS পাঠান',
    smsReceiptSub: 'আপনার SMS ক্রেডিট খরচ হবে',
    receivingNow: 'এখন আদায়',
    errCustomer: 'কাস্টমার বাছুন',
    errAccount: 'অ্যাকাউন্ট বাছুন',
    errAmount: '০-এর বেশি পরিমাণ দিন',
    errDiscount: '০ বা তার বেশি দিন',
    errCategory: 'ছাড় কোন খাতে যাবে বাছুন',
    errReceiver: 'কে টাকা নিয়েছেন লিখুন',
    errTooMuch: (due: string, total: string, excess: string) =>
      `কাস্টমারের বাকি ${due}, কিন্তু এখানে মোট ${total} - ${excess} বেশি। ${due} বা তার কম করুন।`,
    saved: 'বাকি আদায় সেভ হয়েছে',
    partSaved: (saved: string, total: string, error: string) =>
      `${total}টির মধ্যে ${saved}টি পেমেন্ট সেভ হয়েছে; বাকিগুলো হয়নি (${error})। আবার চেষ্টার আগে বাকি আদায় তালিকা দেখে নিন।`,
    discountFailed: (error: string) => `বাকি আদায় সেভ হয়েছে, কিন্তু ছাড়ের খরচ লেখা যায়নি (${error})। খরচ থেকে যোগ করুন।`,
    editReceipt: 'আদায় এডিট করুন',
    editTitle: 'বাকি আদায় সম্পাদনা',
    receiptGone: 'এই আদায়টি আর নেই।',
    splitNoEdit: 'একাধিক অ্যাকাউন্টে ভাগ করা আদায় এডিট করা যায় না - মুছে আবার নিন।',
    discountKept: (amount: string) => `${amount} ছাড় যেমন ছিল তেমনই থাকবে। বদলাতে হলে আদায়টি মুছে আবার নিন।`,
    customerLocked: 'ইনভয়েসের বিপরীতে আদায়, তাই কাস্টমার বদলানো যাবে না।',
    owesBesides: (amount: string) => `এই আদায় ছাড়া বাকি ${amount}`,
    updated: 'বাকি আদায় আপডেট হয়েছে',
    discountNotRemoved: 'বাকি আদায় মুছে ফেলা হয়েছে, কিন্তু ছাড়ের খরচটি মোছা যায়নি - খরচ থেকে মুছে দিন।',
    bulkSms: 'একসাথে বাকির SMS',
    bulkTitle: 'বাকির SMS',
    bulkIntro: 'এখানে সবার বাকি আছে আর মোবাইল নম্বর আছে। প্রত্যেকে নিজের বাকির পরিমাণসহ একটি SMS পাবেন।',
    bulkNoPhone: (n: string) => `আরও ${n} জনের বাকি আছে কিন্তু ব্যবহারযোগ্য মোবাইল নম্বর নেই, তাই তালিকায় নেই।`,
    bulkNone: 'বাকি থাকা কোনো কাস্টমারের মোবাইল নম্বর নেই।',
    bulkSearch: 'নাম বা ফোন',
    selectShown: 'দেখানো সবাইকে বাছুন',
    clearShown: 'দেখানো সবাইকে বাদ দিন',
    bulkSample: 'প্রথমজন যা পড়বেন',
    bulkBalance: (n: string) => `SMS ব্যালেন্স: ${n}`,
    bulkPick: 'কাকে পাঠাবেন বাছুন',
    bulkSend: (n: string, credits: string) => `${n} জনকে পাঠান · প্রায় ${credits} ক্রেডিট`,
    bulkShort: (credits: string, balance: string) => `প্রায় ${credits} ক্রেডিট লাগবে; আছে ${balance}।`,
    bulkConfirmTitle: 'বাকির SMS পাঠাবেন?',
    bulkConfirmText: (n: string, credits: string) => `${n} জন কাস্টমারকে তাঁদের বাকি জানিয়ে SMS পাঠাবেন? প্রায় ${credits} SMS ক্রেডিট খরচ হবে।`,
    bulkSending: (done: string, n: string) => `${n}টির মধ্যে ${done}টি পাঠানো হচ্ছে…`,
    bulkSent: (n: string) => `${n} জন কাস্টমারকে বাকির SMS পাঠানো হয়েছে।`,
    bulkFailed: (n: string, reason: string) => `${n}টি SMS যায়নি - ${reason}।`,
    smsOwnerOnly: 'শুধু মালিক SMS পাঠাতে পারেন।',
    smsSkipped: 'রসিদ SMS যায়নি - কাস্টমারের সঠিক ফোন নম্বর নেই।',
    smsSent: 'রসিদ SMS পাঠানো হয়েছে',

    ledgerIntro: 'একজন কাস্টমারের সব বিক্রি আর বাকি আদায়, পুরনো থেকে নতুন, প্রতিটার পর বাকি সহ।',
    noPersonText: 'খাতা দেখতে একজন কাস্টমার বাছুন।',
    totalDiscount: 'মোট ছাড়',
    totalPaid: 'মোট পরিশোধ',
    sale: 'বিক্রি',
    collection: 'বাকি আদায়',
    invoiceSale: 'ইনভয়েস বিক্রি',
    itemQty: (name: string, qty: string) => `${name} × ${qty}`,
    purchasePlus: 'ক্রয় (+)',
    paidMinus: 'পরিশোধ (−)',
    noTx: 'এখনো কোনো বিক্রি বা বাকি আদায় নেই।',
    showEarlier: 'আগের লেনদেন দেখুন',
    ledgerTitle: (name: string) => `কাস্টমার খাতা - ${name}`,
    colDate: 'তারিখ',
    colRef: 'রেফারেন্স',
    colDetails: 'বিবরণ',
    colDue: 'বাকি',

    searchList: 'নাম, ফোন, ইমেইল বা ঠিকানা',
    countCustomers: (_n: number, shown: string) => `${shown} জন কাস্টমার`,
    newCustomer: 'নতুন কাস্টমার',
    editCustomer: 'কাস্টমার এডিট',
    deleteCustomer: 'কাস্টমার মুছুন',
    name: 'নাম *',
    phone: 'ফোন *',
    email: 'ইমেইল',
    address: 'ঠিকানা',
    openingField: 'প্রারম্ভিক বাকি (৳)',
    openingHint: 'Furnify ব্যবহারের আগে যা বাকি ছিল।',
    errName: 'নাম দিন',
    errPhoneRequired: 'ফোন নম্বর দিন',
    errPhone: 'সঠিক ১১ সংখ্যার নম্বর দিন (যেমন 01XXXXXXXXX)',
    errPhoneTaken: 'এই নম্বর আরেকজন কাস্টমারের',
    errOpening: '০ বা তার বেশি দিন',
    errEmail: 'সঠিক ইমেইল দিন',
    customerSaved: 'কাস্টমার সেভ হয়েছে',
    customerUpdated: 'কাস্টমার আপডেট হয়েছে',
    customerDeleted: 'কাস্টমার মুছে ফেলা হয়েছে',
    linkedCustomer: 'এই কাস্টমারের বিক্রি বা বাকি আদায় আছে, তাই মোছা যাবে না। আগে সেগুলো মুছুন।',
    deleteTitle: (name: string) => `${name}-কে মুছবেন?`,
    deleteText: 'এটা রিসাইকেল বিনে যাবে। কোনো বিক্রি বা বাকি আদায় থাকলে কাস্টমার মোছা যাবে না - আগে সেগুলো মুছুন।',
  },
};
