import { bnDigits } from '@/context/LanguageContext';

// Strings for the four Shareholder screens. The Bangla is the Figma file's own
// where it draws a Bangla version (ShAddBn, ShInvestNewBn, ShProfitNewBn).

export const SHAREHOLDER_COPY = {
  en: {
    title: 'Shareholders',
    backToMenu: 'Back to menu',
    close: 'Close',
    loadError: 'Could not load the shareholders.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    optional: 'Optional',
    select: 'Select',
    sections: { overview: 'Overview', invest: 'Invest / Withdraw', profit: 'Profit withdraw', list: 'Shareholders' },

    periods: { month: 'This month', year: 'Year', custom: 'Custom range' },
    periodLabel: 'Period',
    chooseYear: 'Choose year',
    pickRange: 'Pick a date range',
    from: 'From',
    to: 'To',
    openingCapital: 'Opening capital',
    investmentIn: (p: string) => `Investment · ${p}`,
    withdrawIn: (p: string) => `Withdraw · ${p}`,
    profitLossIn: (p: string) => `Profit / loss · ${p}`,
    retainedProfit: 'Retained profit',
    netCapital: 'Net capital',
    ownership: 'Ownership by net capital',
    summaryTitle: 'Shareholder summary',
    netCapitalOf: (x: string) => `Net capital ${x}`,
    openingAmount: 'Opening amount',
    profitShare: 'Profit / loss share',
    profitWithdraw: 'Profit withdraw',
    noShareholders: 'No shareholders yet.',

    investIntro: 'Shareholder capital in & out',
    totalInvestment: 'Total investment',
    totalWithdrawal: 'Total withdrawal',
    netInvestment: 'Net investment',
    transactions: 'Transactions',
    noTransactions: 'No transactions yet.',
    investment: 'Investment',
    withdrawal: 'Withdrawal',
    newEntry: 'New entry',
    newInvestment: 'New investment / withdrawal',
    editEntry: 'Edit entry',
    deleteEntry: 'Delete entry',
    deleteEntryTitle: 'Delete this entry?',
    entryType: 'Type',
    date: 'Date',
    amount: 'Amount (৳) *',
    shareholder: 'Shareholder *',
    account: 'Account *',
    notes: 'Notes',
    intoAccount: 'The account the money comes into.',
    fromAccount: 'The account the money is paid from.',
    errShareholder: 'Choose a shareholder',
    errAmount: 'Enter an amount more than 0',
    errAccount: 'Choose an account',
    investmentSaved: 'Investment saved',
    withdrawalSaved: 'Withdrawal saved',
    entryUpdated: 'Entry updated',
    entryDeleted: 'Entry deleted',
    entryOptions: (name: string, type: string) => `Options for ${name} ${type.toLowerCase()}`,
    entryTitle: (type: string, amount: string) => `${type} · ${amount}`,
    deleteInvestText: (type: string, amount: string, name: string, date: string, account: string) =>
      `${type} of ${amount} by ${name} on ${date}. Capital and the ${account} balance go back to how they were.`,
    printTransactions: 'Print transaction list',

    profitTitle: 'Profit withdrawals',
    noRecords: 'No records',
    withdrawalsSummary: (n: number, total: string) => `${n} ${n === 1 ? 'withdrawal' : 'withdrawals'} · ${total}`,
    noProfitTitle: 'No profit withdrawals yet',
    noProfitBody: 'When an owner takes profit out of the business, record it here.',
    newProfit: 'New profit withdrawal',
    editProfit: 'Edit profit withdrawal',
    owner: 'Owner *',
    whichMonths: 'Profit for which months',
    fromMonth: 'From month',
    toMonth: 'To month',
    fromYear: 'From year',
    toYear: 'To year',
    errOwner: 'Choose an owner',
    errYear: 'Enter a 4-digit year, e.g. 2026',
    errRange: 'The end month can’t be before the start month',
    profitFor: (range: string) => `Profit for ${range}`,
    profitSaved: 'Profit withdrawal saved',
    profitUpdated: 'Profit withdrawal updated',
    profitOptions: (name: string) => `Options for ${name} profit withdrawal`,
    deleteProfitText: (amount: string, name: string, date: string, account: string) =>
      `${amount} taken by ${name} on ${date}. The ${account} balance and their retained profit go back to how they were.`,

    countText: (n: number) => (n === 1 ? '1 shareholder' : `${n} shareholders`),
    totalShare: (pct: string) => `Total share: ${pct}%`,
    call: (name: string, phone: string) => `Call ${name}, ${phone}`,
    noAddress: 'No address added',
    totalInvestmentOf: 'Total investment',
    addShareholder: 'Add shareholder',
    newShareholder: 'New shareholder',
    editShareholder: 'Edit shareholder',
    deleteShareholder: 'Delete shareholder',
    deleteShareholderTitle: 'Delete this shareholder?',
    deleteShareholderText: (name: string) => `${name} will be removed from the shareholder list. This can’t be undone.`,
    name: 'Name *',
    phone: 'Phone *',
    address: 'Address',
    openingAmountField: 'Opening amount (৳)',
    openingHint: 'Capital this person had put in before you started using Furnify.',
    errName: 'Enter a name',
    errPhone: 'Enter a valid phone number, e.g. 01712345678',
    errOpening: 'Enter a valid amount',
    shareholderAdded: 'Shareholder added',
    shareholderUpdated: 'Shareholder updated',
    shareholderDeleted: 'Shareholder deleted',
    shareholderOptions: (name: string) => `Options for ${name}`,
    linkedShareholder: 'This shareholder has investments or withdrawals and cannot be deleted.',
  },
  bn: {
    title: 'শেয়ারহোল্ডার',
    backToMenu: 'মেনুতে ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'শেয়ারহোল্ডারের তথ্য লোড করা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    optional: 'ঐচ্ছিক',
    select: 'বেছে নিন',
    sections: { overview: 'ওভারভিউ', invest: 'বিনিয়োগ / উত্তোলন', profit: 'লাভ উত্তোলন', list: 'শেয়ারহোল্ডার' },

    periods: { month: 'এই মাস', year: 'বছর', custom: 'নিজের পছন্দের সময়' },
    periodLabel: 'সময়',
    chooseYear: 'বছর বাছাই করুন',
    pickRange: 'তারিখের সীমা বাছাই করুন',
    from: 'শুরু',
    to: 'শেষ',
    openingCapital: 'শুরুর মূলধন',
    investmentIn: (p: string) => `বিনিয়োগ · ${p}`,
    withdrawIn: (p: string) => `উত্তোলন · ${p}`,
    profitLossIn: (p: string) => `লাভ / ক্ষতি · ${p}`,
    retainedProfit: 'জমা থাকা লাভ',
    netCapital: 'নিট মূলধন',
    ownership: 'নিট মূলধন অনুযায়ী মালিকানা',
    summaryTitle: 'শেয়ারহোল্ডারদের হিসাব',
    netCapitalOf: (x: string) => `নিট মূলধন ${x}`,
    openingAmount: 'শুরুর মূলধন',
    profitShare: 'লাভ / ক্ষতির ভাগ',
    profitWithdraw: 'লাভ উত্তোলন',
    noShareholders: 'এখনো কোনো শেয়ারহোল্ডার নেই।',

    investIntro: 'শেয়ারহোল্ডারদের মূলধন আসা-যাওয়া',
    totalInvestment: 'মোট বিনিয়োগ',
    totalWithdrawal: 'মোট উত্তোলন',
    netInvestment: 'নিট বিনিয়োগ',
    transactions: 'লেনদেন',
    noTransactions: 'এখনো কোনো লেনদেন নেই।',
    investment: 'বিনিয়োগ',
    withdrawal: 'উত্তোলন',
    newEntry: 'নতুন এন্ট্রি',
    newInvestment: 'নতুন বিনিয়োগ / উত্তোলন',
    editEntry: 'এন্ট্রি সম্পাদনা',
    deleteEntry: 'এন্ট্রি মুছুন',
    deleteEntryTitle: 'এই এন্ট্রি মুছবেন?',
    entryType: 'ধরন',
    date: 'তারিখ',
    amount: 'টাকার পরিমাণ (৳) *',
    shareholder: 'শেয়ারহোল্ডার *',
    account: 'অ্যাকাউন্ট *',
    notes: 'নোট',
    intoAccount: 'যে অ্যাকাউন্টে টাকা আসবে।',
    fromAccount: 'যে অ্যাকাউন্ট থেকে টাকা দেওয়া হবে।',
    errShareholder: 'একজন শেয়ারহোল্ডার বেছে নিন',
    errAmount: '০-এর বেশি টাকা লিখুন',
    errAccount: 'একটা অ্যাকাউন্ট বেছে নিন',
    investmentSaved: 'বিনিয়োগ সেভ হয়েছে',
    withdrawalSaved: 'উত্তোলন সেভ হয়েছে',
    entryUpdated: 'এন্ট্রি আপডেট হয়েছে',
    entryDeleted: 'এন্ট্রি মুছে ফেলা হয়েছে',
    entryOptions: (name: string, type: string) => `${name}-এর ${type}: আরও অপশন`,
    entryTitle: (type: string, amount: string) => `${type} · ${amount}`,
    deleteInvestText: (type: string, amount: string, name: string, date: string, account: string) =>
      `${date} তারিখে ${name}-এর ${amount} ${type}। মূলধন আর ${account}-এর ব্যালেন্স আগের অবস্থায় ফিরে যাবে।`,
    printTransactions: 'লেনদেনের তালিকা প্রিন্ট করুন',

    profitTitle: 'লাভ উত্তোলন',
    noRecords: 'কোনো রেকর্ড নেই',
    withdrawalsSummary: (n: number, total: string) => `${bnDigits(n)}টা উত্তোলন · ${total}`,
    noProfitTitle: 'এখনো কোনো লাভ উত্তোলন নেই',
    noProfitBody: 'মালিক ব্যবসা থেকে লাভের টাকা তুললে এখানে লিখে রাখুন।',
    newProfit: 'নতুন লাভ উত্তোলন',
    editProfit: 'লাভ উত্তোলন সম্পাদনা',
    owner: 'মালিক *',
    whichMonths: 'কোন মাসের লাভ',
    fromMonth: 'শুরুর মাস',
    toMonth: 'শেষ মাস',
    fromYear: 'শুরুর বছর',
    toYear: 'শেষ বছর',
    errOwner: 'একজন মালিক বেছে নিন',
    errYear: '৪ সংখ্যার বছর লিখুন, যেমন 2026',
    errRange: 'শেষ মাস শুরুর মাসের আগে হতে পারে না',
    profitFor: (range: string) => `${range}-এর লাভ`,
    profitSaved: 'লাভ উত্তোলন সেভ হয়েছে',
    profitUpdated: 'লাভ উত্তোলন আপডেট হয়েছে',
    profitOptions: (name: string) => `${name}-এর লাভ উত্তোলন: আরও অপশন`,
    deleteProfitText: (amount: string, name: string, date: string, account: string) =>
      `${date} তারিখে ${name} ${amount} তুলেছেন। ${account}-এর ব্যালেন্স আর তাঁর জমা থাকা লাভ আগের অবস্থায় ফিরে যাবে।`,

    countText: (n: number) => `${bnDigits(n)} জন শেয়ারহোল্ডার`,
    totalShare: (pct: string) => `মোট শেয়ার: ${bnDigits(pct)}%`,
    call: (name: string, phone: string) => `${name}-কে কল করুন, ${phone}`,
    noAddress: 'ঠিকানা দেওয়া হয়নি',
    totalInvestmentOf: 'মোট বিনিয়োগ',
    addShareholder: 'শেয়ারহোল্ডার যোগ করুন',
    newShareholder: 'নতুন শেয়ারহোল্ডার',
    editShareholder: 'শেয়ারহোল্ডার সম্পাদনা',
    deleteShareholder: 'শেয়ারহোল্ডার মুছুন',
    deleteShareholderTitle: 'এই শেয়ারহোল্ডার মুছবেন?',
    deleteShareholderText: (name: string) => `${name} শেয়ারহোল্ডারের তালিকা থেকে মুছে যাবে। এটা আর ফেরানো যাবে না।`,
    name: 'নাম *',
    phone: 'ফোন *',
    address: 'ঠিকানা',
    openingAmountField: 'শুরুর মূলধন (৳)',
    openingHint: 'Furnify ব্যবহার শুরুর আগে এই ব্যক্তি যত মূলধন দিয়েছিলেন।',
    errName: 'নাম দিন',
    errPhone: 'সঠিক মোবাইল নম্বর দিন, যেমন 01712345678',
    errOpening: 'সঠিক টাকার পরিমাণ দিন',
    shareholderAdded: 'শেয়ারহোল্ডার যোগ হয়েছে',
    shareholderUpdated: 'শেয়ারহোল্ডার আপডেট হয়েছে',
    shareholderDeleted: 'শেয়ারহোল্ডার মুছে ফেলা হয়েছে',
    shareholderOptions: (name: string) => `${name}: আরও অপশন`,
    linkedShareholder: 'এই শেয়ারহোল্ডারের বিনিয়োগ বা উত্তোলন আছে, তাই মোছা যাবে না।',
  },
};
