// Strings for the Sales tab - the invoices, the items sold, their sheets and
// the New sale form. The words follow the website's Sales page, its printed
// invoice labels and its locales (sales_*), with the app's own কাস্টমার.

export const SALES_COPY = {
  en: {
    title: 'Sales',
    close: 'Close',
    loadError: 'Could not load sales.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    optional: 'Optional',
    back: 'Back',
    date: 'Date',
    notes: 'Notes',
    showMore: 'Show more',
    searchLabel: 'Search',
    sections: { invoices: 'Invoices', items: 'Items sold' },
    periods: { all: 'All', today: 'Today', yesterday: 'Yesterday', thisMonth: 'This month', thisYear: 'This year' },
    periodLabel: 'Period',
    deliveryLabel: 'Delivery',
    allDeliveries: 'Any delivery',
    deliveryStates: { pending: 'Not delivered', partial: 'Partly delivered', delivered: 'Delivered' },
    walkIn: 'Walk-in customer',
    smsNotSent: (reason: string) => `SMS not sent - ${reason}.`,

    totalShown: 'Sales total',
    countInvoices: (n: number, shown: string) => (n === 1 ? '1 invoice' : `${shown} invoices`),
    searchInvoices: 'Customer, invoice, phone or account',
    noInvoices: 'No sales here.',
    newSale: 'New sale',
    paidDue: (paid: string, due: string) => `Paid ${paid} · Due ${due}`,

    lineMath: (qty: string, each: string, total: string) => `${qty} × ${each} = ${total}`,
    deliveredOf: (done: string, qty: string) => `${done} of ${qty} delivered`,
    deliver: 'Deliver',
    subtotal: 'Subtotal',
    discount: 'Discount',
    deliveryCharge: 'Delivery charge',
    invoiceTotal: 'Invoice total',
    previousDue: 'Previous due',
    paid: 'Paid',
    due: 'Due',
    currentDue: 'Current due',
    paidInto: 'Paid into',
    cost: 'Cost',
    profit: 'Profit',
    profitPending: 'A line has no cost yet, so its profit is not counted.',
    sharePdf: 'Share PDF',
    print: 'Print',
    deleteSale: 'Delete sale',
    deleteTitle: (no: string) => `Delete ${no}?`,
    deleteText: 'It moves to the recycle bin, its stock goes back at the cost it went out at, and the payments on the invoice go with it. A previous due collected with it stays in Customers › Due received.',
    deleted: 'Sale deleted',
    invoiceTitle: (no: string) => `Invoice ${no}`,
    colProduct: 'Product',
    colCode: 'Code',
    colQty: 'Qty',
    colUnitPrice: 'Unit price',
    colTotal: 'Total',

    deliveryTitle: 'Deliver',
    howMany: 'How many go out *',
    deliveredBy: 'Delivered by',
    deliveredByPlaceholder: 'Who took it out',
    errDeliver: (n: string) => `Enter 1 to ${n}`,
    deliveredDone: 'Delivery recorded',
    stillToGo: (n: string) => `${n} still to deliver`,

    searchItems: 'Product, code, invoice or customer',
    countItems: (n: number, shown: string) => (n === 1 ? '1 line' : `${shown} lines`),
    itemsTotal: 'Sold',
    sortLabel: 'Sort',
    sorts: {
      date_desc: 'Newest first',
      date_asc: 'Oldest first',
      name_asc: 'Customer A–Z',
      amount_desc: 'Highest amount',
      amount_asc: 'Lowest amount',
    },
    noItems: 'Nothing sold here.',

    formTitle: 'New sale',
    invoiceNo: 'Invoice no *',
    customer: 'Customer',
    chooseCustomer: 'Choose a saved customer',
    searchCustomers: 'Name or phone',
    noCustomerMatch: 'No customer matches.',
    newCustomer: 'New customer',
    walkInHint: 'Or type a walk-in customer below.',
    customerName: 'Name',
    customerPhone: 'Phone',
    customerAddress: 'Address',
    owesBefore: (amount: string) => `Owes ${amount} from before - added to what is payable today.`,
    owesBeforeInfo: (amount: string) => `Owes ${amount} from before.`,
    products: 'Products',
    addProduct: 'Add product',
    chooseProduct: 'Choose product',
    removeLine: 'Remove',
    qty: 'Qty *',
    price: 'Price (৳) *',
    discountField: 'Discount',
    inTaka: '৳',
    inPercent: '%',
    discountUnit: 'Discount in',
    eachAfter: 'Each',
    lineTotal: 'Total',
    deliveredNow: 'Delivered now',
    deliveredLater: 'Delivered later - the stock still goes out now',
    payment: 'Payment',
    account: 'Account *',
    chooseAccount: 'Choose account',
    amount: 'Amount (৳) *',
    addAccount: 'Split across another account',
    payInFull: 'Paid in full',
    smsInvoice: 'Text the customer the invoice',
    smsInvoiceSub: 'Uses your SMS credits',
    payable: 'Payable today',
    dueAfter: 'Due after',
    errCustomer: 'Enter a customer name or phone, or choose one',
    errPhone: 'Enter a valid 11-digit number (e.g. 01XXXXXXXXX)',
    errInvoice: 'Enter an invoice number',
    errItems: 'Add at least one product',
    errQty: 'Qty: a whole number above 0',
    errPrice: 'Price: 0 or more',
    errDiscount: 'Discount: from 0 up to the price',
    errAccount: 'Choose an account',
    errAmount: 'Enter an amount more than 0',
    errOverpaid: 'What is paid is more than is payable today.',
    saved: (no: string) => `Sale ${no} saved`,
    editTitle: 'Edit invoice',
    editSale: 'Edit sale',
    editBlocked: 'This invoice cannot be edited: one of its lines is not a product from the list, or a product is on it twice.',
    updated: (no: string) => `Sale ${no} updated`,
    notFound: 'This sale is no longer here.',
    owesOnEdit: (amount: string) => `Owes ${amount} besides this invoice. Take that as a due collection.`,
    alreadyDelivered: (done: string, qty: string) => `${done} of ${qty} already delivered - that stays`,
    dueFailed: (error: string) => `The previous due collected with it was not saved (${error}). Record it in Customers › Due received.`,
    smsSkipped: 'Invoice SMS skipped - no valid phone number.',
    smsSent: 'Invoice sent by SMS.',
  },
  bn: {
    title: 'বিক্রি',
    close: 'বন্ধ করুন',
    loadError: 'বিক্রির হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    optional: 'ঐচ্ছিক',
    back: 'ফিরুন',
    date: 'তারিখ',
    notes: 'নোট',
    showMore: 'আরও দেখুন',
    searchLabel: 'খুঁজুন',
    sections: { invoices: 'ইনভয়েস', items: 'বিক্রিত পণ্য' },
    periods: { all: 'সব', today: 'আজ', yesterday: 'গতকাল', thisMonth: 'এই মাস', thisYear: 'এই বছর' },
    periodLabel: 'সময়',
    deliveryLabel: 'ডেলিভারি',
    allDeliveries: 'সব ডেলিভারি',
    deliveryStates: { pending: 'ডেলিভারি হয়নি', partial: 'আংশিক ডেলিভারি', delivered: 'ডেলিভারি হয়েছে' },
    walkIn: 'ওয়াক-ইন কাস্টমার',
    smsNotSent: (reason: string) => `SMS যায়নি - ${reason}।`,

    totalShown: 'মোট বিক্রি',
    countInvoices: (_n: number, shown: string) => `${shown}টি ইনভয়েস`,
    searchInvoices: 'কাস্টমার, ইনভয়েস, ফোন বা অ্যাকাউন্ট',
    noInvoices: 'এখানে কোনো বিক্রি নেই।',
    newSale: 'নতুন বিক্রি',
    paidDue: (paid: string, due: string) => `পরিশোধ ${paid} · বাকি ${due}`,

    lineMath: (qty: string, each: string, total: string) => `${qty} × ${each} = ${total}`,
    deliveredOf: (done: string, qty: string) => `${qty}টির মধ্যে ${done}টি ডেলিভারি হয়েছে`,
    deliver: 'ডেলিভারি দিন',
    subtotal: 'সাব টোটাল',
    discount: 'ছাড়',
    deliveryCharge: 'ডেলিভারি চার্জ',
    invoiceTotal: 'ইনভয়েসের মোট',
    previousDue: 'পূর্বের বাকি',
    paid: 'পরিশোধিত',
    due: 'বাকি',
    currentDue: 'বর্তমান বাকি',
    paidInto: 'যে অ্যাকাউন্টে জমা',
    cost: 'ক্রয়মূল্য',
    profit: 'লাভ',
    profitPending: 'একটা লাইনের ক্রয়মূল্য এখনো নেই, তাই তার লাভ ধরা হয়নি।',
    sharePdf: 'PDF শেয়ার',
    print: 'প্রিন্ট',
    deleteSale: 'বিক্রি মুছুন',
    deleteTitle: (no: string) => `${no} মুছবেন?`,
    deleteText: 'এটা রিসাইকেল বিনে যাবে, এর স্টক যে দামে বের হয়েছিল সেই দামে ফেরত আসবে, আর ইনভয়েসের পেমেন্টও বাদ যাবে। এর সাথে আদায় করা আগের বাকি কাস্টমার › বাকি আদায়-এ থেকে যাবে।',
    deleted: 'বিক্রি মুছে ফেলা হয়েছে',
    invoiceTitle: (no: string) => `ইনভয়েস ${no}`,
    colProduct: 'পণ্যের নাম',
    colCode: 'প্রোডাক্ট কোড',
    colQty: 'পরিমাণ',
    colUnitPrice: 'ইউনিট মূল্য',
    colTotal: 'মোট',

    deliveryTitle: 'ডেলিভারি দিন',
    howMany: 'কতগুলো যাচ্ছে *',
    deliveredBy: 'কে ডেলিভারি দিলেন',
    deliveredByPlaceholder: 'যিনি মাল নিয়ে গেছেন',
    errDeliver: (n: string) => `১ থেকে ${n} লিখুন`,
    deliveredDone: 'ডেলিভারি লেখা হয়েছে',
    stillToGo: (n: string) => `আরও ${n}টি ডেলিভারি বাকি`,

    searchItems: 'পণ্য, কোড, ইনভয়েস বা কাস্টমার',
    countItems: (_n: number, shown: string) => `${shown}টি লাইন`,
    itemsTotal: 'বিক্রি',
    sortLabel: 'সাজান',
    sorts: {
      date_desc: 'নতুন আগে',
      date_asc: 'পুরনো আগে',
      name_asc: 'কাস্টমারের নাম অনুযায়ী',
      amount_desc: 'বেশি টাকা আগে',
      amount_asc: 'কম টাকা আগে',
    },
    noItems: 'এখানে কোনো বিক্রি নেই।',

    formTitle: 'নতুন বিক্রি',
    invoiceNo: 'ইনভয়েস নং *',
    customer: 'কাস্টমার',
    chooseCustomer: 'সেভ করা কাস্টমার বাছুন',
    searchCustomers: 'নাম বা ফোন',
    noCustomerMatch: 'কোনো কাস্টমার মেলেনি।',
    newCustomer: 'নতুন কাস্টমার',
    walkInHint: 'অথবা নিচে ওয়াক-ইন কাস্টমারের তথ্য লিখুন।',
    customerName: 'নাম',
    customerPhone: 'ফোন',
    customerAddress: 'ঠিকানা',
    owesBefore: (amount: string) => `আগের বাকি ${amount} - আজকের পরিশোধযোগ্য টাকায় যোগ হয়েছে।`,
    owesBeforeInfo: (amount: string) => `আগের বাকি ${amount}।`,
    products: 'পণ্য',
    addProduct: 'পণ্য যোগ করুন',
    chooseProduct: 'পণ্য বাছুন',
    removeLine: 'সরান',
    qty: 'পরিমাণ *',
    price: 'দাম (৳) *',
    discountField: 'ছাড়',
    inTaka: '৳',
    inPercent: '%',
    discountUnit: 'ছাড়ের একক',
    eachAfter: 'প্রতিটি',
    lineTotal: 'মোট',
    deliveredNow: 'এখনই ডেলিভারি',
    deliveredLater: 'পরে ডেলিভারি - তবে স্টক এখনই কমবে',
    payment: 'পেমেন্ট',
    account: 'অ্যাকাউন্ট *',
    chooseAccount: 'অ্যাকাউন্ট বাছুন',
    amount: 'পরিমাণ (৳) *',
    addAccount: 'আরেকটা অ্যাকাউন্টে ভাগ করুন',
    payInFull: 'পুরো টাকা পরিশোধ',
    smsInvoice: 'কাস্টমারকে ইনভয়েস SMS পাঠান',
    smsInvoiceSub: 'আপনার SMS ক্রেডিট খরচ হবে',
    payable: 'আজ পরিশোধযোগ্য',
    dueAfter: 'বাকি রইল',
    errCustomer: 'কাস্টমারের নাম বা ফোন দিন, অথবা বাছুন',
    errPhone: 'সঠিক ১১ সংখ্যার নম্বর দিন (যেমন 01XXXXXXXXX)',
    errInvoice: 'ইনভয়েস নং দিন',
    errItems: 'অন্তত একটা পণ্য যোগ করুন',
    errQty: 'পরিমাণ: ০-এর বেশি পূর্ণ সংখ্যা',
    errPrice: 'দাম: ০ বা তার বেশি',
    errDiscount: 'ছাড়: ০ থেকে দাম পর্যন্ত',
    errAccount: 'অ্যাকাউন্ট বাছুন',
    errAmount: '০-এর বেশি পরিমাণ দিন',
    errOverpaid: 'আজ যা পরিশোধযোগ্য, তার চেয়ে বেশি টাকা দেওয়া হয়েছে।',
    saved: (no: string) => `বিক্রি ${no} সেভ হয়েছে`,
    editTitle: 'ইনভয়েস সম্পাদনা',
    editSale: 'বিক্রি এডিট করুন',
    editBlocked: 'এই ইনভয়েস এডিট করা যাবে না: এর কোনো লাইন তালিকার পণ্য নয়, অথবা একই পণ্য দুবার আছে।',
    updated: (no: string) => `বিক্রি ${no} আপডেট হয়েছে`,
    notFound: 'এই বিক্রিটি আর নেই।',
    owesOnEdit: (amount: string) => `এই ইনভয়েস ছাড়াও বাকি ${amount}। সেটা বাকি আদায় হিসেবে নিন।`,
    alreadyDelivered: (done: string, qty: string) => `${qty}টির মধ্যে ${done}টি আগেই ডেলিভারি হয়েছে - সেটা থাকবে`,
    dueFailed: (error: string) => `এর সাথে আদায় করা আগের বাকি সেভ হয়নি (${error})। কাস্টমার › বাকি আদায় থেকে লিখুন।`,
    smsSkipped: 'ইনভয়েস SMS যায়নি - সঠিক ফোন নম্বর নেই।',
    smsSent: 'ইনভয়েস SMS পাঠানো হয়েছে।',
  },
};
