import { bnDigits } from '@/context/LanguageContext';

// Strings for the four Balance screens. The Bangla is the Figma file's own where
// it draws a Bangla version (LedgerIslamiBn, TransferNewBn, WalletAddBn).

export const BALANCE_COPY = {
  en: {
    title: 'Balance',
    backToMenu: 'Back to menu',
    showAmounts: 'Show amounts',
    hideAmounts: 'Hide amounts',
    close: 'Close',
    loadError: 'Could not load the balance.',
    retry: 'Try again',
    cancel: 'Cancel',
    saving: 'Saving…',
    delete: 'Delete',
    optional: 'Optional',
    sections: { overview: 'Overview', transfers: 'Transfers', ledger: 'Ledger', wallet: 'Wallet' },

    totalAccounts: 'Total accounts',
    totalBalance: 'Total balance',
    inactiveAmount: 'Inactive amount',
    availableBalance: 'Available balance',
    accountDetails: 'Account details',
    nAccounts: (n: number) => `${n} accounts`,
    inactive: 'Inactive',
    openLedger: (name: string, balance: string) => `${name}, current balance ${balance}. Open ledger`,
    totalLine: (label: string) => `Total · ${label}`,
    tabs: { glance: 'At a Glance', owner: 'Owner Funds', loans: 'Loans', trade: 'Sales & Buying', others: 'Others' } as Record<string, string>,
    columns: {
      balance_openingBalance: 'Opening',
      balance_totalIn: 'In',
      balance_totalOut: 'Out',
      balance_currentBalance: 'current balance',
      balance_investment: 'Investment',
      balance_withdrawal: 'Withdrawal',
      balance_profitWithdrawal: 'Profit taken',
      balance_net: 'net',
      balance_loanReceived: 'Received',
      balance_loanPaid: 'Paid',
      balance_netLoan: 'net loan',
      balance_cashSales: 'Cash sales',
      balance_customerCollection: 'Collected',
      balance_supplierPayment: 'Supplier paid',
      balance_netTrade: 'net trade',
      balance_otherIncome: 'Other income',
      balance_expensePaid: 'Expenses',
      balance_transferIn: 'Transfer in',
      balance_transferOut: 'Transfer out',
    } as Record<string, string>,

    totalTransfer: 'Total transfer',
    totalTransactions: 'Total transactions',
    transferNote: 'Total balance stays the same on a transfer. Money only moves between accounts.',
    transferList: 'Transfer list',
    printTransfers: 'Print transfer list',
    listPeriods: { all: 'All time', thisMonth: 'This month', lastMonth: 'Last month', thisYear: 'This year' },
    choosePeriod: 'Choose period',
    showingLatest: (n: number, total: number) => `Showing the latest ${n} of ${total} transfers`,
    showingAll: (n: number) => `Showing all ${n} transfers`,
    noTransfers: 'No transfers in this period.',
    newTransfer: 'New transfer',
    editTransfer: 'Edit transfer',
    fromAccount: 'From account *',
    toAccount: 'To account *',
    chooseAccount: 'Choose account',
    swap: 'Swap from and to',
    amount: 'Amount (৳) *',
    date: 'Date',
    notes: 'Notes',
    saveTransfer: 'Save transfer',
    saveChanges: 'Save changes',
    errFrom: 'Choose the account the money leaves',
    errTo: 'Choose the account the money goes to',
    errSame: 'From and To must be different accounts',
    errAmount: 'Enter an amount more than 0',
    transferOptions: (amount: string, from: string, to: string) => `Options for ${amount} from ${from} to ${to}`,
    deleteTransfer: 'Delete transfer',
    deleteTransferTitle: 'Delete this transfer?',
    deleteTransferText: (amount: string, from: string, to: string, date: string) =>
      `${amount} from ${from} to ${to} on ${date}. Both account balances go back to how they were before this transfer.`,
    transferSaved: 'Transfer saved',
    transferUpdated: 'Transfer updated',
    transferDeleted: 'Transfer deleted',

    ledgerIntro: 'One account, every movement through it, with the balance carried forward.',
    account: 'Account',
    selectAccount: 'Select an account',
    chooseLedger: 'Choose an account to see its ledger.',
    opening: 'Opening',
    closing: 'Closing',
    moneyIn: 'Money in',
    moneyOut: 'Money out',
    broughtForward: 'Balance brought forward',
    bal: (x: string) => `Bal ${x}`,
    noMovements: 'No movements in this period.',
    printLedger: 'Print or save as PDF',
    period: 'Period',
    transferFrom: (name: string) => `From ${name}`,
    transferTo: (name: string) => `To ${name}`,
    kinds: {
      'Transfer in': 'Transfer in',
      'Transfer out': 'Transfer out',
      Sale: 'Sale',
      'Sale payment': 'Sale payment',
      'Due collected': 'Due collected',
      Expense: 'Expense',
      'Supplier paid': 'Supplier paid',
      'Other income': 'Other income',
      Investment: 'Investment',
      'Profit withdrawal': 'Profit withdrawal',
      'Loan received': 'Loan received',
      'Loan paid': 'Loan paid',
    } as Record<string, string>,

    accounts: 'Accounts',
    walletCount: (n: number, active: number) => `${n} accounts · ${active} active`,
    openingOf: (x: string) => `Opening ${x}`,
    activeSwitch: (name: string) => `Active: ${name}`,
    accountOptions: (name: string) => `Options for ${name}`,
    addAccount: 'Add account',
    editAccount: 'Edit account',
    name: 'Name *',
    namePh: 'e.g. BRAC bank',
    openingBalance: 'Opening balance (৳)',
    openingHint: 'Money already in this account on the day you start.',
    save: 'Save',
    errName: 'Enter an account name',
    errDuplicate: 'An account with this name already exists',
    errOpening: 'Enter a valid amount',
    deleteAccount: 'Delete account',
    deleteAccountTitle: 'Delete this account?',
    deleteAccountText: (name: string) => `${name} will be removed from your wallet. This can’t be undone.`,
    linked: 'This account has linked transactions and cannot be deleted.',
    accountAdded: 'Account added',
    accountUpdated: 'Account updated',
    accountDeleted: 'Account deleted',
    turnedOn: (name: string) => `${name} turned on`,
    turnedOff: (name: string) => `${name} turned off`,
  },
  bn: {
    title: 'ব্যালেন্স',
    backToMenu: 'মেনুতে ফিরুন',
    showAmounts: 'টাকার অঙ্ক দেখান',
    hideAmounts: 'টাকার অঙ্ক লুকান',
    close: 'বন্ধ করুন',
    loadError: 'ব্যালেন্স লোড করা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    optional: 'ঐচ্ছিক',
    sections: { overview: 'ওভারভিউ', transfers: 'ট্রান্সফার', ledger: 'লেজার', wallet: 'ওয়ালেট' },

    totalAccounts: 'মোট অ্যাকাউন্ট',
    totalBalance: 'মোট ব্যালেন্স',
    inactiveAmount: 'বন্ধ অ্যাকাউন্টের টাকা',
    availableBalance: 'ব্যবহারযোগ্য ব্যালেন্স',
    accountDetails: 'অ্যাকাউন্টের বিবরণ',
    nAccounts: (n: number) => `${bnDigits(n)}টা অ্যাকাউন্ট`,
    inactive: 'বন্ধ',
    openLedger: (name: string, balance: string) => `${name}, বর্তমান ব্যালেন্স ${balance}। লেজার খুলুন`,
    totalLine: (label: string) => `মোট · ${label}`,
    tabs: { glance: 'এক নজরে', owner: 'মালিকের টাকা', loans: 'লোন', trade: 'বিক্রি ও ক্রয়', others: 'অন্যান্য' } as Record<string, string>,
    columns: {
      balance_openingBalance: 'শুরু',
      balance_totalIn: 'এসেছে',
      balance_totalOut: 'গেছে',
      balance_currentBalance: 'বর্তমান ব্যালেন্স',
      balance_investment: 'বিনিয়োগ',
      balance_withdrawal: 'উত্তোলন',
      balance_profitWithdrawal: 'লাভ তোলা',
      balance_net: 'নিট',
      balance_loanReceived: 'এসেছে',
      balance_loanPaid: 'শোধ',
      balance_netLoan: 'নিট লোন',
      balance_cashSales: 'নগদ বিক্রি',
      balance_customerCollection: 'বাকি আদায়',
      balance_supplierPayment: 'সাপ্লায়ার পেমেন্ট',
      balance_netTrade: 'নিট কেনা-বেচা',
      balance_otherIncome: 'অন্যান্য আয়',
      balance_expensePaid: 'খরচ',
      balance_transferIn: 'ট্রান্সফার এসেছে',
      balance_transferOut: 'ট্রান্সফার গেছে',
    } as Record<string, string>,

    totalTransfer: 'মোট ট্রান্সফার',
    totalTransactions: 'মোট লেনদেন',
    transferNote: 'ট্রান্সফারে মোট ব্যালেন্স বদলায় না, টাকা শুধু এক অ্যাকাউন্ট থেকে আরেকটায় যায়।',
    transferList: 'ট্রান্সফারের তালিকা',
    printTransfers: 'ট্রান্সফারের তালিকা প্রিন্ট করুন',
    listPeriods: { all: 'সব সময়', thisMonth: 'এই মাস', lastMonth: 'গত মাস', thisYear: 'এই বছর' },
    choosePeriod: 'সময় বাছাই করুন',
    showingLatest: (n: number, total: number) => `সর্বশেষ ${bnDigits(n)}টা দেখানো হচ্ছে, মোট ${bnDigits(total)}টা ট্রান্সফার`,
    showingAll: (n: number) => `সব ${bnDigits(n)}টা ট্রান্সফার দেখানো হচ্ছে`,
    noTransfers: 'এই সময়ে কোনো ট্রান্সফার নেই।',
    newTransfer: 'নতুন ট্রান্সফার',
    editTransfer: 'ট্রান্সফার সম্পাদনা',
    fromAccount: 'যে অ্যাকাউন্ট থেকে *',
    toAccount: 'যে অ্যাকাউন্টে *',
    chooseAccount: 'অ্যাকাউন্ট বাছাই করুন',
    swap: 'অ্যাকাউন্ট অদলবদল করুন',
    amount: 'টাকার পরিমাণ (৳) *',
    date: 'তারিখ',
    notes: 'নোট',
    saveTransfer: 'ট্রান্সফার সেভ করুন',
    saveChanges: 'পরিবর্তন সেভ করুন',
    errFrom: 'কোন অ্যাকাউন্ট থেকে টাকা যাবে বাছাই করুন',
    errTo: 'কোন অ্যাকাউন্টে টাকা যাবে বাছাই করুন',
    errSame: 'দুটো অ্যাকাউন্ট আলাদা হতে হবে',
    errAmount: '০-এর বেশি টাকার পরিমাণ দিন',
    transferOptions: (amount: string, from: string, to: string) => `${from} থেকে ${to}-এ ${amount}: আরও অপশন`,
    deleteTransfer: 'ট্রান্সফার মুছুন',
    deleteTransferTitle: 'এই ট্রান্সফার মুছবেন?',
    deleteTransferText: (amount: string, from: string, to: string, date: string) =>
      `${date} তারিখে ${from} থেকে ${to}-এ ${amount}। দুটো অ্যাকাউন্টের ব্যালেন্স এই ট্রান্সফারের আগের অবস্থায় ফিরে যাবে।`,
    transferSaved: 'ট্রান্সফার সেভ হয়েছে',
    transferUpdated: 'ট্রান্সফার আপডেট হয়েছে',
    transferDeleted: 'ট্রান্সফার মুছে ফেলা হয়েছে',

    ledgerIntro: 'একটা অ্যাকাউন্টের সব আসা-যাওয়া, প্রতিটার পর কত ব্যালেন্স থাকল সহ।',
    account: 'অ্যাকাউন্ট',
    selectAccount: 'অ্যাকাউন্ট বাছাই করুন',
    chooseLedger: 'লেজার দেখতে একটা অ্যাকাউন্ট বাছাই করুন।',
    opening: 'শুরুর ব্যালেন্স',
    closing: 'শেষ ব্যালেন্স',
    moneyIn: 'টাকা এসেছে',
    moneyOut: 'টাকা গেছে',
    broughtForward: 'আগের জের',
    bal: (x: string) => `ব্যালেন্স ${x}`,
    noMovements: 'এই সময়ে কোনো আসা-যাওয়া নেই।',
    printLedger: 'প্রিন্ট বা PDF সেভ করুন',
    period: 'সময়',
    transferFrom: (name: string) => `${name} থেকে`,
    transferTo: (name: string) => `${name} অ্যাকাউন্টে`,
    kinds: {
      'Transfer in': 'ট্রান্সফার এসেছে',
      'Transfer out': 'ট্রান্সফার গেছে',
      Sale: 'বিক্রি',
      'Sale payment': 'বিক্রির পেমেন্ট',
      'Due collected': 'বাকি আদায়',
      Expense: 'খরচ',
      'Supplier paid': 'সাপ্লায়ার পেমেন্ট',
      'Other income': 'অন্যান্য আয়',
      Investment: 'বিনিয়োগ',
      'Profit withdrawal': 'লাভ উত্তোলন',
      'Loan received': 'লোন এসেছে',
      'Loan paid': 'লোন শোধ',
    } as Record<string, string>,

    accounts: 'অ্যাকাউন্ট',
    walletCount: (n: number, active: number) => `${bnDigits(n)}টা অ্যাকাউন্ট · ${bnDigits(active)}টা চালু`,
    openingOf: (x: string) => `শুরুর ব্যালেন্স ${x}`,
    activeSwitch: (name: string) => `চালু: ${name}`,
    accountOptions: (name: string) => `${name}: আরও অপশন`,
    addAccount: 'নতুন অ্যাকাউন্ট',
    editAccount: 'অ্যাকাউন্ট সম্পাদনা',
    name: 'নাম *',
    namePh: 'যেমন BRAC bank',
    openingBalance: 'শুরুর ব্যালেন্স (৳)',
    openingHint: 'যেদিন শুরু করছেন, সেদিন এই অ্যাকাউন্টে যত টাকা আছে।',
    save: 'সেভ করুন',
    errName: 'অ্যাকাউন্টের নাম দিন',
    errDuplicate: 'এই নামে একটা অ্যাকাউন্ট আগে থেকেই আছে',
    errOpening: 'সঠিক টাকার পরিমাণ দিন',
    deleteAccount: 'অ্যাকাউন্ট মুছুন',
    deleteAccountTitle: 'এই অ্যাকাউন্ট মুছবেন?',
    deleteAccountText: (name: string) => `${name} ওয়ালেট থেকে মুছে যাবে। এটা আর ফেরানো যাবে না।`,
    linked: 'এই অ্যাকাউন্টে লেনদেন আছে, তাই মোছা যাবে না।',
    accountAdded: 'অ্যাকাউন্ট যোগ হয়েছে',
    accountUpdated: 'অ্যাকাউন্ট আপডেট হয়েছে',
    accountDeleted: 'অ্যাকাউন্ট মুছে ফেলা হয়েছে',
    turnedOn: (name: string) => `${name} চালু হয়েছে`,
    turnedOff: (name: string) => `${name} বন্ধ হয়েছে`,
  },
};
