// Strings for Target & Report - the Report Summary, sales targets and buying
// targets with their sheets. The words follow the website's report pages and
// locales (report_*, nav_salesTarget, purchase target).

export const REPORT_COPY = {
  en: {
    title: 'Target & Report',
    backToMenu: 'Back to menu',
    close: 'Close',
    loadError: 'Could not load the report.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    edit: 'Edit',
    showMore: 'Show more',
    sections: { summary: 'Summary', yearly: 'Yearly', sales: 'Sales target', purchase: 'Purchase target' },
    periods: { today: 'Today', week: 'This week', month: 'This month', year: 'This year', all: 'All time' },
    periodLabel: 'Period',
    ofTarget: (pct: string, target: string) => `${pct}% of ${target}`,
    noTarget: 'No target set',

    totalSales: 'Sales',
    grossProfit: 'Gross profit',
    profitLoss: 'Profit / loss',
    available: (amount: string, withdrawn: string) => `${amount} left after ${withdrawn} withdrawn`,
    expenses: 'Expenses',
    otherIncome: 'Other income',
    purchases: 'Purchases',
    purchaseDetail: (sp: string, deposit: string) => `SP ${sp} · owed ${deposit}`,
    supplierPaid: 'Paid to suppliers',
    uncosted: (amount: string) => `${amount} of sales has no purchase rate yet, so its profit is not counted.`,

    today: 'Today',
    todayTarget: "Today's target",
    soldToday: 'Sold today',
    leftThisMonth: 'Left this month',
    tomorrow: 'Tomorrow',
    daily: 'Day by day',
    target: 'Target',
    sold: 'Sold',
    profit: 'Profit',
    noDays: 'No days in this period.',

    breakdown: 'Breakdown',
    tabs: { sales: 'Sales', purchases: 'Purchases', expenses: 'Expenses', supplier: 'Suppliers', otherIncome: 'Other income' },
    qtyCount: (qty: string) => `${qty} pcs`,
    entries: (n: string) => `${n} entries`,
    owedPaidDue: (owed: string, paid: string, due: string) => `Owed ${owed} · paid ${paid} · due ${due}`,
    noRows: 'Nothing in this period.',
    companies: 'By company',
    companyFigures: (purchase: string, sales: string) => `Bought ${purchase} · sold ${sales}`,
    buyingTargets: (month: string) => `Buying targets · ${month}`,
    buyingFigures: (achieved: string, target: string) => `${achieved} of ${target}`,
    nextMonth: (amount: string) => `Next month ${amount}`,
    extra: (amount: string) => `${amount} over`,

    salesTargetsTitle: 'Sales and profit targets by month',
    salesTargetLabel: 'Sales target',
    profitTargetLabel: 'Profit target',
    noSalesTargets: 'No monthly targets yet.',
    newSalesTarget: 'Set a target',
    salesTargetTitle: 'Monthly target',
    month: 'Month *',
    year: 'Year *',
    salesTargetField: 'Sales target (৳)',
    profitTargetField: 'Profit target (৳)',
    replaceNote: 'A month has one target; saving a month already set replaces it.',
    errYear: 'Enter a year from 2000 to 2100',
    errAmount: 'Enter 0 or more',
    targetSaved: 'Target saved',
    deleteTargetTitle: (month: string) => `Delete the ${month} target?`,
    deleteTargetText: 'The reports for that month will have no target to measure against.',
    targetDeleted: 'Target deleted',

    purchaseTargetsTitle: 'Buying targets by supplier',
    noPurchaseTargets: 'No buying targets yet.',
    newPurchaseTarget: 'Set a buying target',
    purchaseTargetTitle: 'Buying target',
    supplierField: 'Supplier *',
    chooseSupplier: 'Choose supplier',
    searchSuppliers: 'Search suppliers',
    noSuppliers: 'No supplier matches.',
    fromMonth: 'From *',
    toMonth: 'To *',
    totalField: 'Total to buy (৳) *',
    perMonth: (amount: string, months: string) => `${amount} a month over ${months} months`,
    monthsSpan: (from: string, to: string) => `${from} – ${to}`,
    achievedOf: (achieved: string, total: string) => `${achieved} of ${total} bought`,
    remaining: (amount: string) => `${amount} still to buy`,
    finished: 'Finished',
    totalLabel: 'Total',
    perMonthLabel: 'Per month',
    boughtLabel: (pct: string) => `Bought · ${pct}%`,
    errSupplier: 'Choose a supplier',
    errRange: 'The end month cannot come before the start',
    errTotal: 'Enter 0 or more',
    deletePurchaseTargetTitle: (company: string) => `Delete the ${company} buying target?`,
    deletePurchaseTargetText: 'The purchases stay; only the target goes.',

    yearLabel: 'Year',
    noYearData: (year: string) => `Nothing was recorded in ${year}. Targets set for it still show.`,
    profitAchieved: 'Profit earned',
    margin: (pct: string) => `${pct}% net margin`,
    ofSales: (pct: string) => `${pct}% of sales`,
    incentiveOther: 'Incentive + other income',
    incentiveParts: (incentive: string, other: string) => `Incentive ${incentive} · other ${other}`,
    monthByMonth: 'Month by month',
    bestMonth: (month: string, amount: string) => `Best month: ${month}, ${amount}`,
    monthSales: (sales: string) => `Sales ${sales}`,
    monthAria: (month: string, sales: string, result: string) => `${month}: sales ${sales}, profit / loss ${result}`,
    boughtAgainst: 'Bought against targets',
    salesBeforeDiscount: 'Sales before discount',
    discount: 'Discount',
    actualSales: 'Actual sales',
    salesProfit: 'Sales profit',
    incentive: 'Incentive (SP)',
    withdrawn: 'Profit withdrawn',
    availableProfit: 'Available profit',
    owedSuppliers: 'Owed to suppliers',
    piecesBought: 'Pieces bought',
  },
  bn: {
    title: 'টার্গেট ও রিপোর্ট',
    backToMenu: 'মেনুতে ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'রিপোর্ট আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    edit: 'এডিট',
    showMore: 'আরও দেখুন',
    sections: { summary: 'সারসংক্ষেপ', yearly: 'বার্ষিক', sales: 'বিক্রির টার্গেট', purchase: 'ক্রয় টার্গেট' },
    periods: { today: 'আজ', week: 'এই সপ্তাহ', month: 'এই মাস', year: 'এই বছর', all: 'সব সময়' },
    periodLabel: 'সময়',
    ofTarget: (pct: string, target: string) => `${target}-এর ${pct}%`,
    noTarget: 'টার্গেট দেওয়া নেই',

    totalSales: 'বিক্রি',
    grossProfit: 'মোট লাভ',
    profitLoss: 'লাভ / ক্ষতি',
    available: (amount: string, withdrawn: string) => `${withdrawn} তোলার পর থাকে ${amount}`,
    expenses: 'খরচ',
    otherIncome: 'অন্যান্য আয়',
    purchases: 'ক্রয়',
    purchaseDetail: (sp: string, deposit: string) => `SP ${sp} · দেনা ${deposit}`,
    supplierPaid: 'সাপ্লায়ারকে পরিশোধ',
    uncosted: (amount: string) => `${amount} বিক্রির ক্রয়মূল্য এখনো নেই, তাই তার লাভ ধরা হয়নি।`,

    today: 'আজ',
    todayTarget: 'আজকের টার্গেট',
    soldToday: 'আজ বিক্রি',
    leftThisMonth: 'এই মাসে বাকি',
    tomorrow: 'আগামীকাল',
    daily: 'দিন অনুযায়ী',
    target: 'টার্গেট',
    sold: 'বিক্রি',
    profit: 'লাভ',
    noDays: 'এই সময়ে কোনো দিন নেই।',

    breakdown: 'বিস্তারিত',
    tabs: { sales: 'বিক্রি', purchases: 'ক্রয়', expenses: 'খরচ', supplier: 'সাপ্লায়ার', otherIncome: 'অন্যান্য আয়' },
    qtyCount: (qty: string) => `${qty} পিস`,
    entries: (n: string) => `${n}টি এন্ট্রি`,
    owedPaidDue: (owed: string, paid: string, due: string) => `দেনা ${owed} · পরিশোধ ${paid} · বাকি ${due}`,
    noRows: 'এই সময়ে কিছু নেই।',
    companies: 'কোম্পানি অনুযায়ী',
    companyFigures: (purchase: string, sales: string) => `ক্রয় ${purchase} · বিক্রি ${sales}`,
    buyingTargets: (month: string) => `ক্রয় টার্গেট · ${month}`,
    buyingFigures: (achieved: string, target: string) => `${target}-এর মধ্যে ${achieved}`,
    nextMonth: (amount: string) => `পরের মাসে ${amount}`,
    extra: (amount: string) => `${amount} বেশি`,

    salesTargetsTitle: 'মাস অনুযায়ী বিক্রি ও লাভের টার্গেট',
    salesTargetLabel: 'বিক্রির টার্গেট',
    profitTargetLabel: 'লাভের টার্গেট',
    noSalesTargets: 'এখনো কোনো মাসিক টার্গেট নেই।',
    newSalesTarget: 'টার্গেট দিন',
    salesTargetTitle: 'মাসিক টার্গেট',
    month: 'মাস *',
    year: 'বছর *',
    salesTargetField: 'বিক্রির টার্গেট (৳)',
    profitTargetField: 'লাভের টার্গেট (৳)',
    replaceNote: 'এক মাসের একটাই টার্গেট; আগে দেওয়া মাস আবার সেভ করলে সেটা বদলে যাবে।',
    errYear: '২০০০ থেকে ২১০০-এর মধ্যে বছর দিন',
    errAmount: '০ বা তার বেশি দিন',
    targetSaved: 'টার্গেট সেভ হয়েছে',
    deleteTargetTitle: (month: string) => `${month}-এর টার্গেট মুছবেন?`,
    deleteTargetText: 'ওই মাসের রিপোর্টে মেলানোর মতো কোনো টার্গেট থাকবে না।',
    targetDeleted: 'টার্গেট মুছে ফেলা হয়েছে',

    purchaseTargetsTitle: 'সাপ্লায়ার অনুযায়ী ক্রয় টার্গেট',
    noPurchaseTargets: 'এখনো কোনো ক্রয় টার্গেট নেই।',
    newPurchaseTarget: 'ক্রয় টার্গেট দিন',
    purchaseTargetTitle: 'ক্রয় টার্গেট',
    supplierField: 'সাপ্লায়ার *',
    chooseSupplier: 'সাপ্লায়ার বাছুন',
    searchSuppliers: 'সাপ্লায়ার খুঁজুন',
    noSuppliers: 'কোনো সাপ্লায়ার মেলেনি।',
    fromMonth: 'শুরু *',
    toMonth: 'শেষ *',
    totalField: 'মোট কিনতে হবে (৳) *',
    perMonth: (amount: string, months: string) => `${months} মাসে প্রতি মাসে ${amount}`,
    monthsSpan: (from: string, to: string) => `${from} – ${to}`,
    achievedOf: (achieved: string, total: string) => `${total}-এর মধ্যে ${achieved} কেনা হয়েছে`,
    remaining: (amount: string) => `আরও ${amount} কিনতে বাকি`,
    finished: 'শেষ হয়েছে',
    totalLabel: 'মোট',
    perMonthLabel: 'প্রতি মাসে',
    boughtLabel: (pct: string) => `কেনা · ${pct}%`,
    errSupplier: 'সাপ্লায়ার বাছুন',
    errRange: 'শেষ মাস শুরুর আগে হতে পারবে না',
    errTotal: '০ বা তার বেশি দিন',
    deletePurchaseTargetTitle: (company: string) => `${company}-এর ক্রয় টার্গেট মুছবেন?`,
    deletePurchaseTargetText: 'কেনাকাটা থেকে যাবে; শুধু টার্গেটটা মুছবে।',

    yearLabel: 'বছর',
    noYearData: (year: string) => `${year}-এ কোনো লেনদেন নেই। এই বছরের টার্গেট দেওয়া থাকলে তা দেখাবে।`,
    profitAchieved: 'অর্জিত লাভ',
    margin: (pct: string) => `নিট মার্জিন ${pct}%`,
    ofSales: (pct: string) => `বিক্রির ${pct}%`,
    incentiveOther: 'ইনসেনটিভ + অন্যান্য আয়',
    incentiveParts: (incentive: string, other: string) => `ইনসেনটিভ ${incentive} · অন্যান্য ${other}`,
    monthByMonth: 'মাস অনুযায়ী',
    bestMonth: (month: string, amount: string) => `সেরা মাস: ${month}, ${amount}`,
    monthSales: (sales: string) => `বিক্রি ${sales}`,
    monthAria: (month: string, sales: string, result: string) => `${month}: বিক্রি ${sales}, লাভ / ক্ষতি ${result}`,
    boughtAgainst: 'টার্গেটের বিপরীতে কেনা',
    salesBeforeDiscount: 'ছাড়ের আগে বিক্রি',
    discount: 'ছাড়',
    actualSales: 'প্রকৃত বিক্রি',
    salesProfit: 'বিক্রির লাভ',
    incentive: 'ইনসেনটিভ (SP)',
    withdrawn: 'লাভ উত্তোলন',
    availableProfit: 'অবশিষ্ট লাভ',
    owedSuppliers: 'সাপ্লায়ারের দেনা',
    piecesBought: 'কেনা পিস',
  },
};
