// Strings for the four Supplier screens and their sheets. The words follow
// the website's locales (supplier_*, supplierPayments_*, settings_*), with the
// app's own সাপ্লায়ার for the supplier.

export const SUPPLIER_COPY = {
  en: {
    title: 'Supplier',
    backToMenu: 'Back to menu',
    close: 'Close',
    loadError: 'Could not load suppliers.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    edit: 'Edit',
    optional: 'Optional',
    select: 'Select',
    date: 'Date',
    notes: 'Notes',
    showMore: 'Show more',
    searchLabel: 'Search',
    sections: { overview: 'Overview', payments: 'Payments', income: 'Other income', list: 'Suppliers', report: 'Report' },
    periods: { all: 'All time', thisMonth: 'This month', lastMonth: 'Last month', thisYear: 'This year' },
    periodLabel: 'Period',
    side: { pawna: 'Pawna', dena: 'Dena', balanced: 'Settled' },
    call: (name: string, phone: string) => `Call ${name}, ${phone}`,

    totalPurchase: 'Total purchase',
    purchaseHint: 'ordered, less SP',
    totalPaid: 'Total paid',
    paidHint: 'on bills and after',
    totalPayable: 'Total payable',
    payableHint: 'owed to suppliers',
    balances: 'Balance by supplier',
    searchSuppliers: 'Supplier or phone',
    noSuppliers: 'No suppliers yet.',
    noMatch: 'No supplier matches.',
    opening: 'Opening',
    orderAmount: 'Order amount',
    specialDiscount: 'Special discount (SP)',
    actual: 'Actual',
    payment: 'Payment',
    available: 'Available balance',
    payThem: 'Pay this supplier',

    totalShown: 'Total paid',
    countPayments: (n: number, shown: string) => (n === 1 ? '1 payment' : `${shown} payments`),
    allSuppliers: 'All suppliers',
    filterSupplier: 'Supplier',
    newPayment: 'New payment',
    editPayment: 'Edit payment',
    deletePayment: 'Delete payment',
    deletePaymentTitle: 'Delete this supplier payment?',
    goesBack: (amount: string, account: string) => `${amount} goes back to ${account}.`,
    supplierField: 'Supplier *',
    chooseSupplier: 'Choose supplier',
    amount: 'Amount (৳) *',
    account: 'Account *',
    chooseAccount: 'Choose account',
    paidFrom: 'The account the money was paid from.',
    owedNow: (amount: string) => `Owed now: ${amount}`,
    errSupplier: 'Choose a supplier',
    errAmount: 'Enter an amount more than 0',
    errAccount: 'Choose an account',
    paymentSaved: 'Payment saved',
    paymentUpdated: 'Payment updated',
    paymentDeleted: 'Payment deleted',
    noPayments: 'No supplier payments here.',
    purchaseRef: (si: string) => `Purchase ${si}`,

    incomeTypes: {
      supplier: { label: 'From a supplier', sub: 'Commission, incentive' },
      other: { label: 'Other source', sub: 'Anything else' },
    },
    kindLabel: 'Kind',
    allKinds: 'All kinds',
    totalIncome: 'Total income',
    countIncomes: (n: number, shown: string) => (n === 1 ? '1 income' : `${shown} incomes`),
    sourceField: 'Source *',
    sourcePlaceholder: 'e.g. Scrap sale',
    newIncome: 'New income',
    editIncome: 'Edit income',
    deleteIncome: 'Delete income',
    deleteIncomeTitle: 'Delete this income?',
    comesOut: (amount: string, account: string) => `${amount} comes out of ${account}.`,
    intoAccount: 'The account the money came into.',
    errSource: 'Enter where it came from',
    incomeSaved: 'Income saved',
    incomeUpdated: 'Income updated',
    incomeDeleted: 'Income deleted',
    noIncome: 'No other income here.',
    noAccount: 'No account',

    countSuppliers: (n: number, shown: string) => (n === 1 ? '1 supplier' : `${shown} suppliers`),
    newSupplier: 'New supplier',
    editSupplier: 'Edit supplier',
    deleteSupplier: 'Delete supplier',
    deleteSupplierTitle: (name: string) => `Delete ${name}?`,
    deleteSupplierText: 'This can’t be undone.',
    linkedSupplier: 'This supplier has purchases or payments and can’t be deleted.',
    inactive: 'Inactive',
    companyField: 'Company name *',
    personField: 'Person name',
    phoneField: 'Phone *',
    emailField: 'Email',
    addressField: 'Address',
    openingField: 'Opening due (৳)',
    openingIs: 'The opening due is',
    dueTypes: {
      dena: { label: 'Dena', sub: 'We owe them' },
      pawna: { label: 'Pawna', sub: 'They owe us' },
    },
    errCompany: 'Enter the company name',
    errPhone: 'Enter a valid phone number, e.g. 01712345678',
    errEmail: 'Enter a valid email',
    errOpening: 'Enter a valid amount',
    supplierAdded: (name: string) => `${name} added`,
    supplierUpdated: (name: string) => `${name} updated`,
    supplierDeleted: (name: string) => `${name} deleted`,

    reportTitle: 'Yearly purchase overview',
    reportIntro: 'What was ordered from suppliers each month, the incentive they gave back, what that left owed, and what was paid.',
    yearLabel: 'Year',
    supplierFilter: 'Supplier',
    noYearData: (who: string, year: string) => `Nothing was bought from ${who} in ${year}.`,
    anybody: 'anybody',
    ordered: 'Ordered',
    incentive: 'Incentive (SP)',
    owed: 'Owed',
    paid: 'Paid',
    paidHintReport: 'on bills and after, by the day it left',
    colMonth: 'Month',
    colOrderValue: 'Total order value',
    colIncentive: '- Incentive',
    colActualDeposit: 'Actual deposit amount',
    colDeposit: 'Deposit amount',
    total: 'Total',
    sharePdf: 'Share PDF',
    print: 'Print',
  },
  bn: {
    title: 'সাপ্লায়ার',
    backToMenu: 'মেনুতে ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'সাপ্লায়ারের হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    optional: 'ঐচ্ছিক',
    select: 'বাছাই করুন',
    date: 'তারিখ',
    notes: 'নোট',
    showMore: 'আরও দেখুন',
    searchLabel: 'খুঁজুন',
    sections: { overview: 'ওভারভিউ', payments: 'পেমেন্ট', income: 'অন্যান্য আয়', list: 'সাপ্লায়ার তালিকা', report: 'রিপোর্ট' },
    periods: { all: 'সব সময়', thisMonth: 'এই মাস', lastMonth: 'গত মাস', thisYear: 'এই বছর' },
    periodLabel: 'সময়',
    side: { pawna: 'পাওনা', dena: 'দেনা', balanced: 'সমান' },
    call: (name: string, phone: string) => `${name}-কে কল করুন, ${phone}`,

    totalPurchase: 'মোট ক্রয়',
    purchaseHint: 'অর্ডার, SP বাদে',
    totalPaid: 'মোট পরিশোধ',
    paidHint: 'বিলে ও পরে',
    totalPayable: 'মোট দেনা',
    payableHint: 'সাপ্লায়ারদের দিতে হবে',
    balances: 'সাপ্লায়ার অনুযায়ী ব্যালেন্স',
    searchSuppliers: 'সাপ্লায়ার বা ফোন',
    noSuppliers: 'এখনো কোনো সাপ্লায়ার নেই।',
    noMatch: 'কোনো সাপ্লায়ার মেলেনি।',
    opening: 'প্রারম্ভিক',
    orderAmount: 'অর্ডারের পরিমাণ',
    specialDiscount: 'স্পেশাল ছাড় (SP)',
    actual: 'প্রকৃত',
    payment: 'পেমেন্ট',
    available: 'বর্তমান ব্যালেন্স',
    payThem: 'এই সাপ্লায়ারকে টাকা দিন',

    totalShown: 'মোট পরিশোধ',
    countPayments: (_n: number, shown: string) => `${shown}টি পেমেন্ট`,
    allSuppliers: 'সব সাপ্লায়ার',
    filterSupplier: 'সাপ্লায়ার',
    newPayment: 'নতুন পেমেন্ট',
    editPayment: 'পেমেন্ট সম্পাদনা',
    deletePayment: 'পেমেন্ট মুছুন',
    deletePaymentTitle: 'এই সাপ্লায়ার পেমেন্ট মুছবেন?',
    goesBack: (amount: string, account: string) => `${amount} আবার ${account}-এ ফিরে যাবে।`,
    supplierField: 'সাপ্লায়ার *',
    chooseSupplier: 'সাপ্লায়ার বাছুন',
    amount: 'পরিমাণ (৳) *',
    account: 'অ্যাকাউন্ট *',
    chooseAccount: 'অ্যাকাউন্ট বাছুন',
    paidFrom: 'যে অ্যাকাউন্ট থেকে টাকা দেওয়া হয়েছে।',
    owedNow: (amount: string) => `এখন দেনা: ${amount}`,
    errSupplier: 'সাপ্লায়ার বাছুন',
    errAmount: '০-এর বেশি পরিমাণ লিখুন',
    errAccount: 'অ্যাকাউন্ট বাছুন',
    paymentSaved: 'পেমেন্ট সেভ হয়েছে',
    paymentUpdated: 'পেমেন্ট আপডেট হয়েছে',
    paymentDeleted: 'পেমেন্ট মুছে ফেলা হয়েছে',
    noPayments: 'এখানে কোনো সাপ্লায়ার পেমেন্ট নেই।',
    purchaseRef: (si: string) => `ক্রয় ${si}`,

    incomeTypes: {
      supplier: { label: 'সাপ্লায়ার থেকে', sub: 'কমিশন, ইনসেনটিভ' },
      other: { label: 'অন্য উৎস', sub: 'অন্য যেকোনো' },
    },
    kindLabel: 'ধরন',
    allKinds: 'সব ধরন',
    totalIncome: 'মোট আয়',
    countIncomes: (_n: number, shown: string) => `${shown}টি আয়`,
    sourceField: 'উৎস *',
    sourcePlaceholder: 'যেমন: ভাঙাড়ি বিক্রি',
    newIncome: 'নতুন আয়',
    editIncome: 'আয় সম্পাদনা',
    deleteIncome: 'আয় মুছুন',
    deleteIncomeTitle: 'এই আয় মুছবেন?',
    comesOut: (amount: string, account: string) => `${amount} ${account} থেকে বাদ যাবে।`,
    intoAccount: 'যে অ্যাকাউন্টে টাকা এসেছে।',
    errSource: 'কোথা থেকে এসেছে লিখুন',
    incomeSaved: 'আয় সেভ হয়েছে',
    incomeUpdated: 'আয় আপডেট হয়েছে',
    incomeDeleted: 'আয় মুছে ফেলা হয়েছে',
    noIncome: 'এখানে কোনো অন্যান্য আয় নেই।',
    noAccount: 'অ্যাকাউন্ট নেই',

    countSuppliers: (_n: number, shown: string) => `${shown}টি সাপ্লায়ার`,
    newSupplier: 'নতুন সাপ্লায়ার',
    editSupplier: 'সাপ্লায়ার সম্পাদনা',
    deleteSupplier: 'সাপ্লায়ার মুছুন',
    deleteSupplierTitle: (name: string) => `${name} মুছবেন?`,
    deleteSupplierText: 'এটা আর ফেরানো যাবে না।',
    linkedSupplier: 'এই সাপ্লায়ারের ক্রয় বা পেমেন্ট আছে, তাই মোছা যাবে না।',
    inactive: 'নিষ্ক্রিয়',
    companyField: 'কোম্পানির নাম *',
    personField: 'ব্যক্তির নাম',
    phoneField: 'ফোন *',
    emailField: 'ইমেইল',
    addressField: 'ঠিকানা',
    openingField: 'প্রারম্ভিক বাকি (৳)',
    openingIs: 'প্রারম্ভিক বাকি',
    dueTypes: {
      dena: { label: 'দেনা', sub: 'আমরা ওদের দেব' },
      pawna: { label: 'পাওনা', sub: 'ওরা আমাদের দেবে' },
    },
    errCompany: 'কোম্পানির নাম দিন',
    errPhone: 'সঠিক ফোন নম্বর লিখুন, যেমন ০১৭১২৩৪৫৬৭৮',
    errEmail: 'সঠিক ইমেইল লিখুন',
    errOpening: 'সঠিক পরিমাণ লিখুন',
    supplierAdded: (name: string) => `${name} যোগ হয়েছে`,
    supplierUpdated: (name: string) => `${name} আপডেট হয়েছে`,
    supplierDeleted: (name: string) => `${name} মুছে ফেলা হয়েছে`,

    reportTitle: 'বার্ষিক ক্রয়ের হিসাব',
    reportIntro: 'প্রতি মাসে সাপ্লায়ারের কাছ থেকে কত অর্ডার হয়েছে, তারা কত ইনসেনটিভ দিয়েছে, তাতে কত দেনা দাঁড়াল, আর কত পরিশোধ হয়েছে।',
    yearLabel: 'বছর',
    supplierFilter: 'সাপ্লায়ার',
    noYearData: (who: string, year: string) => `${year}-এ ${who} থেকে কিছু কেনা হয়নি।`,
    anybody: 'কারো',
    ordered: 'অর্ডার',
    incentive: 'ইনসেনটিভ (SP)',
    owed: 'দেনা',
    paid: 'পরিশোধ',
    paidHintReport: 'বিলে ও পরে, যেদিন টাকা গেছে সেই হিসাবে',
    colMonth: 'মাস',
    colOrderValue: 'মোট অর্ডার',
    colIncentive: '- ইনসেনটিভ',
    colActualDeposit: 'প্রকৃত দেনা',
    colDeposit: 'পরিশোধ',
    total: 'মোট',
    sharePdf: 'PDF শেয়ার করুন',
    print: 'প্রিন্ট',
  },
};
