// Strings for the four Employees screens and their sheets. The words follow
// the website's locales (employee_*) and its Employee pages.

export const EMPLOYEE_COPY = {
  en: {
    title: 'Employees',
    backToMenu: 'Back to menu',
    close: 'Close',
    loadError: 'Could not load employees.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    edit: 'Edit',
    optional: 'Optional',
    date: 'Date',
    notes: 'Notes',
    showMore: 'Show more',
    searchLabel: 'Search',
    sections: { overview: 'Overview', payments: 'Salary / Bonus', attendance: 'Attendance', list: 'Employees' },
    periods: { all: 'All time', thisMonth: 'This month', lastMonth: 'Last month', thisYear: 'This year' },
    periodLabel: 'Period',
    allEmployees: 'All employees',
    filterEmployee: 'Employee',
    call: (name: string, phone: string) => `Call ${name}, ${phone}`,
    duration: (months: string, days: string) => `${months} mo ${days} d`,

    totalPaid: 'Salary and bonus paid',
    counts: (all: string, active: string, resigned: string) => `${all} employees · ${active} active · ${resigned} resigned`,
    totalSalary: 'Total salary',
    totalBonus: 'Total bonus',
    salary: 'Salary',
    bonus: 'Bonus',
    subtotal: 'Subtotal',
    joined: (date: string) => `Joined ${date}`,
    resignedOn: (date: string) => `Resigned ${date}`,
    workingFor: 'Working',
    resignedBadge: 'Resigned',
    noEmployees: 'No employees yet.',
    noMatch: 'No employee matches.',
    searchEmployees: 'Name, phone or address',

    payShown: 'Paid',
    countPayments: (n: number, shown: string) => (n === 1 ? '1 payment' : `${shown} payments`),
    noPayments: 'No salary or bonus paid here.',
    newPayment: 'Pay salary',
    periodDays: (days: string) => `${days} days`,
    deletePayment: 'Delete payment',
    deletePaymentTitle: 'Delete this payment?',
    deletePaymentText: (amount: string, account: string) => `${amount} goes back to ${account}, and the expense booked with it goes too.`,
    paymentDeleted: 'Payment deleted',
    payTitle: 'Pay salary or bonus',
    employeeField: 'Employee *',
    chooseEmployee: 'Choose employee',
    searchPick: 'Name or phone',
    kinds: { Salary: 'Salary', Bonus: 'Bonus' },
    kindLabel: 'Payment',
    category: 'Expense category *',
    chooseCategory: 'Choose category',
    periodFrom: 'Period from *',
    periodTo: 'Period to *',
    account: 'Paid from *',
    chooseAccount: 'Choose account',
    amount: 'Amount (৳) *',
    bookedNote: 'It is booked as an expense from this account.',
    errEmployee: 'Choose an employee',
    errCategory: 'Choose an expense category',
    errAccount: 'Choose an account',
    errAmount: 'Enter an amount more than 0',
    errPeriod: 'The period must end on or after it starts',
    paid: 'Payment saved',

    present: 'Present',
    absent: 'Absent',
    attendanceCounts: (total: string, present: string, absent: string) => `${total} records · ${present} present · ${absent} absent`,
    noAttendance: 'No attendance here.',
    newAttendance: 'Record attendance',
    attendanceTitle: 'Attendance',
    editAttendance: 'Edit attendance',
    status: 'Status',
    presentSub: 'At work that day',
    absentSub: 'Did not come',
    startTime: 'Start',
    endTime: 'End',
    noTime: 'Not set',
    clear: 'Clear',
    hoursLabel: (hours: string, minutes: string) => (minutes === '0' || minutes === '০' ? `${hours} h` : `${hours} h ${minutes} min`),
    hoursTotal: 'Hours',
    attendanceSaved: 'Attendance saved',
    existingDay: 'Already recorded for this day - saving updates it.',
    deleteAttendance: 'Delete attendance',
    deleteAttendanceTitle: 'Delete this attendance?',
    deleteAttendanceText: 'It moves to the recycle bin.',
    attendanceDeleted: 'Attendance deleted',

    countEmployees: (n: number, shown: string) => (n === 1 ? '1 employee' : `${shown} employees`),
    newEmployee: 'Add employee',
    editEmployee: 'Edit employee',
    resign: 'Resign',
    resignTitle: (name: string) => `${name} resigns`,
    resignDate: 'Resign date *',
    deleteEmployee: 'Delete employee',
    deleteEmployeeTitle: (name: string) => `Delete ${name}?`,
    deleteEmployeeText: 'Their salary payments and attendance are deleted with them; the expenses those payments booked stay. To keep the records, mark them resigned instead.',
    name: 'Name *',
    phone: 'Phone *',
    address: 'Address *',
    joinDate: 'Join date *',
    errName: 'Enter a name',
    errPhoneRequired: 'Enter a phone number',
    errPhone: 'Enter a valid 11-digit number (e.g. 01XXXXXXXXX)',
    errAddress: 'Enter an address',
    errResign: 'The resign date cannot be before they joined',
    employeeSaved: 'Employee saved',
    employeeUpdated: 'Employee updated',
    resignedSaved: 'Resignation saved',
    employeeDeleted: 'Employee deleted',
  },
  bn: {
    title: 'কর্মচারী',
    backToMenu: 'মেনুতে ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'কর্মচারীর হিসাব আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    edit: 'এডিট',
    optional: 'ঐচ্ছিক',
    date: 'তারিখ',
    notes: 'নোট',
    showMore: 'আরও দেখুন',
    searchLabel: 'খুঁজুন',
    sections: { overview: 'সারসংক্ষেপ', payments: 'বেতন / বোনাস', attendance: 'উপস্থিতি', list: 'কর্মচারী তালিকা' },
    periods: { all: 'সব সময়', thisMonth: 'এই মাস', lastMonth: 'গত মাস', thisYear: 'এই বছর' },
    periodLabel: 'সময়',
    allEmployees: 'সব কর্মচারী',
    filterEmployee: 'কর্মচারী',
    call: (name: string, phone: string) => `${name}-কে কল করুন, ${phone}`,
    duration: (months: string, days: string) => `${months} মাস ${days} দিন`,

    totalPaid: 'মোট বেতন ও বোনাস',
    counts: (all: string, active: string, resigned: string) => `${all} জন কর্মচারী · ${active} জন সক্রিয় · ${resigned} জন পদত্যাগ`,
    totalSalary: 'মোট বেতন',
    totalBonus: 'মোট বোনাস',
    salary: 'বেতন',
    bonus: 'বোনাস',
    subtotal: 'সাব টোটাল',
    joined: (date: string) => `যোগদান ${date}`,
    resignedOn: (date: string) => `পদত্যাগ ${date}`,
    workingFor: 'কর্মকাল',
    resignedBadge: 'পদত্যাগকারী',
    noEmployees: 'এখনো কোনো কর্মচারী নেই।',
    noMatch: 'কোনো কর্মচারী মেলেনি।',
    searchEmployees: 'নাম, ফোন বা ঠিকানা',

    payShown: 'পরিশোধ',
    countPayments: (_n: number, shown: string) => `${shown}টি পেমেন্ট`,
    noPayments: 'এখানে কোনো বেতন বা বোনাস নেই।',
    newPayment: 'বেতন দিন',
    periodDays: (days: string) => `${days} দিন`,
    deletePayment: 'পেমেন্ট মুছুন',
    deletePaymentTitle: 'এই পেমেন্ট মুছবেন?',
    deletePaymentText: (amount: string, account: string) => `${amount} আবার ${account}-এ ফেরত যাবে, আর এর সাথে লেখা খরচও মুছে যাবে।`,
    paymentDeleted: 'পেমেন্ট মুছে ফেলা হয়েছে',
    payTitle: 'বেতন বা বোনাস দিন',
    employeeField: 'কর্মচারী *',
    chooseEmployee: 'কর্মচারী বাছুন',
    searchPick: 'নাম বা ফোন',
    kinds: { Salary: 'বেতন', Bonus: 'বোনাস' },
    kindLabel: 'পেমেন্ট',
    category: 'খরচের খাত *',
    chooseCategory: 'খাত বাছুন',
    periodFrom: 'মেয়াদ শুরু *',
    periodTo: 'মেয়াদ শেষ *',
    account: 'যে অ্যাকাউন্ট থেকে *',
    chooseAccount: 'অ্যাকাউন্ট বাছুন',
    amount: 'পরিমাণ (৳) *',
    bookedNote: 'এই অ্যাকাউন্ট থেকে খরচ হিসেবে লেখা হবে।',
    errEmployee: 'কর্মচারী বাছুন',
    errCategory: 'খরচের খাত বাছুন',
    errAccount: 'অ্যাকাউন্ট বাছুন',
    errAmount: '০-এর বেশি পরিমাণ দিন',
    errPeriod: 'মেয়াদ শেষ শুরুর আগে হতে পারবে না',
    paid: 'পেমেন্ট সেভ হয়েছে',

    present: 'উপস্থিত',
    absent: 'অনুপস্থিত',
    attendanceCounts: (total: string, present: string, absent: string) => `${total}টি রেকর্ড · ${present}টি উপস্থিত · ${absent}টি অনুপস্থিত`,
    noAttendance: 'এখানে কোনো উপস্থিতি নেই।',
    newAttendance: 'উপস্থিতি লিখুন',
    attendanceTitle: 'উপস্থিতি',
    editAttendance: 'উপস্থিতি এডিট',
    status: 'অবস্থা',
    presentSub: 'সেদিন কাজে ছিলেন',
    absentSub: 'আসেননি',
    startTime: 'শুরু',
    endTime: 'শেষ',
    noTime: 'দেওয়া হয়নি',
    clear: 'মুছুন',
    hoursLabel: (hours: string, minutes: string) => (minutes === '0' || minutes === '০' ? `${hours} ঘণ্টা` : `${hours} ঘণ্টা ${minutes} মিনিট`),
    hoursTotal: 'মোট ঘণ্টা',
    attendanceSaved: 'উপস্থিতি সেভ হয়েছে',
    existingDay: 'এই দিনের উপস্থিতি আগেই লেখা আছে - সেভ করলে সেটাই আপডেট হবে।',
    deleteAttendance: 'উপস্থিতি মুছুন',
    deleteAttendanceTitle: 'এই উপস্থিতি মুছবেন?',
    deleteAttendanceText: 'এটা রিসাইকেল বিনে যাবে।',
    attendanceDeleted: 'উপস্থিতি মুছে ফেলা হয়েছে',

    countEmployees: (_n: number, shown: string) => `${shown} জন কর্মচারী`,
    newEmployee: 'কর্মচারী যোগ করুন',
    editEmployee: 'কর্মচারী এডিট',
    resign: 'পদত্যাগ',
    resignTitle: (name: string) => `${name}-এর পদত্যাগ`,
    resignDate: 'পদত্যাগের তারিখ *',
    deleteEmployee: 'কর্মচারী মুছুন',
    deleteEmployeeTitle: (name: string) => `${name}-কে মুছবেন?`,
    deleteEmployeeText: 'তাঁর বেতন আর উপস্থিতির রেকর্ডও মুছে যাবে; ওই বেতনের খরচগুলো থেকে যাবে। রেকর্ড রাখতে চাইলে মোছার বদলে পদত্যাগ দিন।',
    name: 'নাম *',
    phone: 'ফোন *',
    address: 'ঠিকানা *',
    joinDate: 'যোগদানের তারিখ *',
    errName: 'নাম দিন',
    errPhoneRequired: 'ফোন নম্বর দিন',
    errPhone: 'সঠিক ১১ সংখ্যার নম্বর দিন (যেমন 01XXXXXXXXX)',
    errAddress: 'ঠিকানা দিন',
    errResign: 'পদত্যাগের তারিখ যোগদানের আগে হতে পারবে না',
    employeeSaved: 'কর্মচারী সেভ হয়েছে',
    employeeUpdated: 'কর্মচারী আপডেট হয়েছে',
    resignedSaved: 'পদত্যাগ লেখা হয়েছে',
    employeeDeleted: 'কর্মচারী মুছে ফেলা হয়েছে',
  },
};
