import { bnDigits } from '@/context/LanguageContext';

// Strings for the Product List, its detail sheet and its form. The words
// follow the website's locales (Hatim/src/locales) and the app's own menu,
// which says সাপ্লায়ার and পণ্যের তালিকা.

export const PRODUCT_COPY = {
  en: {
    title: 'Product List',
    backToMenu: 'Back to menu',
    back: 'Back',
    close: 'Close',
    loadError: 'Could not load the products.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    delete: 'Delete',
    edit: 'Edit',
    optional: 'Optional',

    searchLabel: 'Search products',
    searchPlaceholder: 'Name or code',
    count: (n: number, shown: string) => (n === 1 ? '1 product' : `${shown} products`),
    emptyAll: 'No products yet.',
    emptySearch: (q: string) => `No product matches “${q}”.`,
    newProduct: 'New product',
    editProduct: 'Edit product',
    options: (name: string) => `Options for ${name}`,
    noSupplier: 'No supplier',
    dp: 'DP',
    mrp: 'MRP',
    pct: (value: number) => `${value}%`,

    code: 'Code',
    category: 'Category',
    supplier: 'Supplier',
    dpRate: 'DP rate',
    finalDp: 'Final DP',
    finalMrp: 'Final MRP',
    discount: 'Discount',
    openingQty: 'Opening qty',
    size: 'Size',
    weight: 'Weight',
    viewStock: 'View stock',

    codeField: 'Product code *',
    codePlaceholder: 'e.g. SKU-001',
    nameField: 'Product name *',
    namePlaceholder: 'e.g. Wooden chair',
    photo: 'Photo',
    addPhoto: 'Add photo',
    changePhoto: 'Change',
    removePhoto: 'Remove',
    photoHint: 'A square photo looks best. JPG or PNG, up to 5 MB.',
    supplierField: 'Supplier *',
    chooseSupplier: 'Choose supplier',
    searchSuppliers: 'Search suppliers',
    noSuppliers: 'No suppliers yet. Add one on the website first.',
    categoryField: 'Category',
    categoryPlaceholder: 'e.g. Bed, Sofa, Chair',
    prices: 'Prices',
    dpRateField: 'DP rate (৳)',
    mrpField: 'MRP (৳)',
    discountField: 'Discount (%)',
    finalLine: (label: string, amount: string) => `${label} ${amount}`,
    openingQtyField: 'Opening qty',
    openingHint: 'Stock you already had before using Furnify.',
    sizeField: 'Size',
    sizePlaceholder: 'e.g. 45x50cm',
    weightField: 'Weight',
    weightPlaceholder: 'e.g. 5kg',

    errCode: 'Enter a product code',
    errName: 'Enter the product name',
    errSupplier: 'Choose a supplier',
    errAmount: 'Enter a valid amount',
    errPercent: 'Enter 0 to 100',
    errQty: 'Enter a whole number',
    errDuplicate: 'Product code already exists. Use a different code.',

    productAdded: (name: string) => `${name} added`,
    productUpdated: (name: string) => `${name} updated`,
    productDeleted: (name: string) => `${name} deleted`,
    deleteTitle: (name: string) => `Delete ${name}?`,
    deleteText: 'It moves to the recycle bin on the website, where it can be restored.',
    linked: 'This product is in sales or purchases, so it can’t be deleted - that keeps their history intact.',
  },
  bn: {
    title: 'পণ্যের তালিকা',
    backToMenu: 'মেনুতে ফিরুন',
    back: 'ফিরুন',
    close: 'বন্ধ করুন',
    loadError: 'পণ্যের তালিকা আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    optional: 'ঐচ্ছিক',

    searchLabel: 'পণ্য খুঁজুন',
    searchPlaceholder: 'নাম বা কোড',
    count: (_n: number, shown: string) => `${shown}টি পণ্য`,
    emptyAll: 'এখনো কোনো পণ্য নেই।',
    emptySearch: (q: string) => `“${q}” নামে বা কোডে কোনো পণ্য নেই।`,
    newProduct: 'নতুন পণ্য',
    editProduct: 'পণ্য সম্পাদনা',
    options: (name: string) => `${name}: আরও অপশন`,
    noSupplier: 'সাপ্লায়ার নেই',
    dp: 'DP',
    mrp: 'MRP',
    pct: (value: number) => `${bnDigits(value)}%`,

    code: 'কোড',
    category: 'ক্যাটাগরি',
    supplier: 'সাপ্লায়ার',
    dpRate: 'DP রেট',
    finalDp: 'চূড়ান্ত DP',
    finalMrp: 'চূড়ান্ত MRP',
    discount: 'ছাড়',
    openingQty: 'প্রারম্ভিক পরিমাণ',
    size: 'সাইজ',
    weight: 'ওজন',
    viewStock: 'স্টক দেখুন',

    codeField: 'পণ্য কোড *',
    codePlaceholder: 'যেমন: SKU-001',
    nameField: 'পণ্যের নাম *',
    namePlaceholder: 'যেমন: কাঠের চেয়ার',
    photo: 'ছবি',
    addPhoto: 'ছবি যোগ করুন',
    changePhoto: 'বদলান',
    removePhoto: 'সরান',
    photoHint: 'বর্গাকার ছবি সবচেয়ে ভালো দেখায়। JPG বা PNG, ৫ MB পর্যন্ত।',
    supplierField: 'সাপ্লায়ার *',
    chooseSupplier: 'সাপ্লায়ার বাছুন',
    searchSuppliers: 'সাপ্লায়ার খুঁজুন',
    noSuppliers: 'এখনো কোনো সাপ্লায়ার নেই। আগে ওয়েবসাইটে একজন যোগ করুন।',
    categoryField: 'ক্যাটাগরি',
    categoryPlaceholder: 'যেমন: খাট, সোফা, চেয়ার',
    prices: 'দাম',
    dpRateField: 'DP রেট (৳)',
    mrpField: 'MRP (৳)',
    discountField: 'ছাড় (%)',
    finalLine: (label: string, amount: string) => `${label} ${amount}`,
    openingQtyField: 'প্রারম্ভিক পরিমাণ',
    openingHint: 'Furnify ব্যবহারের আগে যে স্টক ছিল।',
    sizeField: 'সাইজ',
    sizePlaceholder: 'যেমন: ৪৫x৫০cm',
    weightField: 'ওজন',
    weightPlaceholder: 'যেমন: ৫kg',

    errCode: 'পণ্য কোড দিন',
    errName: 'পণ্যের নাম দিন',
    errSupplier: 'সাপ্লায়ার বাছুন',
    errAmount: 'সঠিক পরিমাণ লিখুন',
    errPercent: '০ থেকে ১০০ লিখুন',
    errQty: 'পূর্ণ সংখ্যা লিখুন',
    errDuplicate: 'এই কোডের পণ্য আগে থেকেই আছে। অন্য কোড দিন।',

    productAdded: (name: string) => `${name} যোগ হয়েছে`,
    productUpdated: (name: string) => `${name} আপডেট হয়েছে`,
    productDeleted: (name: string) => `${name} মুছে ফেলা হয়েছে`,
    deleteTitle: (name: string) => `${name} মুছবেন?`,
    deleteText: 'এটা ওয়েবসাইটের রিসাইকেল বিনে যাবে, সেখান থেকে ফেরানো যায়।',
    linked: 'এই পণ্য বিক্রি বা ক্রয়ে আছে, তাই মোছা যাবে না — এতে সেগুলোর হিসাব ঠিক থাকে।',
  },
};
