// Strings for Update Price. The words are the website's (locales price_*),
// with the few a phone needs of its own: sharing the files instead of
// downloading them, and the save counting up.

export const PRICE_COPY = {
  en: {
    title: 'Update Price',
    back: 'Back',
    close: 'Close',
    showMore: 'Show more',
    subtitle: 'Raise prices across the catalogue from a spreadsheet',
    entry: 'Update price from a file',
    sample: 'Sample file',
    upload: 'Choose file',
    howTitle: 'How this works',
    how: [
      'Your file needs a Code column and any of the four price columns.',
      'Prices are matched on product code. A code that is not in your catalogue is skipped, never added.',
      'A blank cell leaves that price as it is. Only cells with a number are changed.',
      'You will see exactly what changes before anything is saved, and the old prices are kept as a file you can upload to undo.',
    ],
    reading: 'Reading the file…',
    checking: 'Checking against your products…',
    savingProgress: (done: string, total: string) => `Saving prices · ${done} of ${total}`,
    willChange: 'Will change',
    alreadyCorrect: 'Already correct',
    notFound: 'Not in your catalogue',
    notFoundHint: 'These codes are skipped - nothing is added.',
    apply: 'Apply these prices',
    cancel: 'Choose a different file',
    nothingToChange: 'Every price in this file already matches your catalogue - nothing to update.',
    noRows: 'No usable rows. The file needs a Code column and at least one price column.',
    noHeader: 'Could not find a header row with a Code column and a price column.',
    readFailed: 'Could not read the file.',
    wrongType: 'Choose an .xlsx, .xls or .csv file.',
    fields: { cost_price: 'DP', dp_discount: 'DP %', selling_price: 'MRP', mrp_discount: 'MRP %' },
    now: 'Now',
    next: 'New',
    done: (changed: string, missing: string, same: string) => `${changed} changed · ${missing} not in your catalogue · ${same} already correct`,
    rollbackNote: 'The old prices are kept as a file. Share it to save it elsewhere - uploading it here undoes this update.',
    shareOld: 'Share the old prices file',
    historyTitle: 'Update history',
    historyEmpty: 'No price updates yet. Choose a file to make one.',
    itemsUpdated: (n: string) => `${n} updated`,
    statuses: { completed: 'Completed', partial: 'Partly saved' },
    ownerOnly: 'Only an owner or manager with Update Price can change prices from a file.',
  },
  bn: {
    title: 'দাম আপডেট',
    back: 'ফিরুন',
    close: 'বন্ধ করুন',
    showMore: 'আরও দেখুন',
    subtitle: 'এক্সেল ফাইল থেকে একসাথে অনেক পণ্যের দাম বদলান',
    entry: 'ফাইল থেকে দাম আপডেট',
    sample: 'নমুনা ফাইল',
    upload: 'ফাইল বাছুন',
    howTitle: 'কীভাবে কাজ করে',
    how: [
      'ফাইলে একটি Code কলাম আর চারটি দামের যেকোনো কলাম থাকলেই হবে।',
      'পণ্য কোড মিলিয়ে দাম বসে। আপনার তালিকায় নেই এমন কোড বাদ পড়বে, নতুন পণ্য যোগ হবে না।',
      'ফাঁকা ঘরের দাম আগের মতোই থাকবে। শুধু যেখানে সংখ্যা আছে সেটাই বদলাবে।',
      'সেভ হওয়ার আগে ঠিক কী কী বদলাবে দেখতে পাবেন, আর পুরোনো দামগুলো একটা ফাইলে রাখা থাকবে — সেটা আপলোড করলেই আগের অবস্থায় ফেরত।',
    ],
    reading: 'ফাইল পড়া হচ্ছে…',
    checking: 'আপনার পণ্যের সাথে মেলানো হচ্ছে…',
    savingProgress: (done: string, total: string) => `দাম সংরক্ষণ হচ্ছে · ${total}টির মধ্যে ${done}টি`,
    willChange: 'বদলাবে',
    alreadyCorrect: 'আগে থেকেই ঠিক আছে',
    notFound: 'আপনার তালিকায় নেই',
    notFoundHint: 'এই কোডগুলো বাদ পড়বে — নতুন কিছু যোগ হবে না।',
    apply: 'এই দামগুলো বসান',
    cancel: 'অন্য ফাইল বাছুন',
    nothingToChange: 'এই ফাইলের সব দাম আপনার তালিকার সাথে আগে থেকেই মিলে আছে — বদলানোর কিছু নেই।',
    noRows: 'ব্যবহারযোগ্য কোনো সারি নেই। ফাইলে একটি Code কলাম আর অন্তত একটি দামের কলাম লাগবে।',
    noHeader: 'Code কলাম আর দামের কলামসহ হেডার সারি খুঁজে পাওয়া যায়নি।',
    readFailed: 'ফাইলটি পড়া যায়নি।',
    wrongType: '.xlsx, .xls বা .csv ফাইল বাছুন।',
    fields: { cost_price: 'DP', dp_discount: 'DP %', selling_price: 'MRP', mrp_discount: 'MRP %' },
    now: 'এখন',
    next: 'নতুন',
    done: (changed: string, missing: string, same: string) => `${changed}টি বদলেছে · ${missing}টি তালিকায় নেই · ${same}টি আগে থেকেই ঠিক`,
    rollbackNote: 'পুরোনো দামগুলো একটা ফাইলে রাখা আছে। অন্য কোথাও রাখতে শেয়ার করুন — এখানে আপলোড করলেই এই আপডেট ফেরত যাবে।',
    shareOld: 'পুরোনো দামের ফাইল শেয়ার করুন',
    historyTitle: 'আপডেটের ইতিহাস',
    historyEmpty: 'এখনো কোনো দাম আপডেট হয়নি। ফাইল বেছে শুরু করুন।',
    itemsUpdated: (n: string) => `${n}টি বদলেছে`,
    statuses: { completed: 'সম্পন্ন', partial: 'আংশিক সংরক্ষিত' },
    ownerOnly: 'Update Price অনুমতি থাকা মালিক বা ম্যানেজারই ফাইল থেকে দাম বদলাতে পারেন।',
  },
};
