// Business Info's strings. The Bangla edit labels are the Figma file's own
// (BusinessInfoEditBn); the rest follow its voice.

export const BUSINESS_COPY = {
  en: {
    title: 'Business Info',
    editTitle: 'Edit business info',
    back: 'Back',
    cancelEditing: 'Cancel editing',
    businessName: 'Business name',
    phone1: 'Phone 1',
    phone2: 'Phone 2',
    email: 'Email',
    address: 'Address',
    website: 'Website',
    logoUrl: 'Logo URL',
    notAdded: 'Not added',
    logoAlt: 'Business logo',
    upload: 'Upload logo',
    change: 'Change logo',
    noFile: 'No file chosen',
    optional: 'Optional',
    emailPh: 'shop@example.com',
    websitePh: 'www.example.com',
    logoUrlPh: 'https://',
    edit: 'Edit',
    cancel: 'Cancel',
    save: 'Save changes',
    saving: 'Saving…',
    saved: 'Business info updated',
    errName: 'Enter the business name',
    errPhone: 'Enter a valid phone number, e.g. 01712345678',
    errEmail: 'Enter a valid email address',
    errAddress: 'Enter the business address',
    loadError: 'Could not load the business info.',
    retry: 'Try again',
    photoDenied: 'Allow photo access to choose a logo.',
  },
  bn: {
    title: 'ব্যবসার তথ্য',
    editTitle: 'ব্যবসার তথ্য সম্পাদনা',
    back: 'ফিরে যান',
    cancelEditing: 'সম্পাদনা বাতিল',
    businessName: 'ব্যবসার নাম',
    phone1: 'ফোন ১',
    phone2: 'ফোন ২',
    email: 'ইমেইল',
    address: 'ঠিকানা',
    website: 'ওয়েবসাইট',
    logoUrl: 'লোগোর লিংক (URL)',
    notAdded: 'দেওয়া হয়নি',
    logoAlt: 'ব্যবসার লোগো',
    upload: 'লোগো আপলোড করুন',
    change: 'লোগো বদলান',
    noFile: 'কোনো ফাইল বাছাই করা হয়নি',
    optional: 'ঐচ্ছিক',
    emailPh: 'shop@example.com',
    websitePh: 'www.example.com',
    logoUrlPh: 'https://',
    edit: 'সম্পাদনা',
    cancel: 'বাতিল',
    save: 'পরিবর্তন সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    saved: 'ব্যবসার তথ্য আপডেট হয়েছে',
    errName: 'ব্যবসার নাম দিন',
    errPhone: 'সঠিক মোবাইল নম্বর দিন, যেমন 01712345678',
    errEmail: 'সঠিক ইমেইল দিন',
    errAddress: 'ব্যবসার ঠিকানা দিন',
    loadError: 'ব্যবসার তথ্য লোড করা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    photoDenied: 'লোগো বাছাই করতে ছবির অনুমতি দিন।',
  },
};
