// Strings for the Inventory tab, its stock sheet and the adjustment. Labels
// and the oversold note are the website's own (Hatim/src/locales inventory_*).

export const INVENTORY_COPY = {
  en: {
    title: 'Inventory',
    close: 'Close',
    loadError: 'Could not load the stock.',
    retry: 'Try again',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving…',
    printList: 'Print this list',

    totalValue: 'Total stock value (DP based)',
    oversoldNote:
      'Some products have sold more than was recorded as purchased, so their stock is negative and is subtracting from this total. Record the missing purchases to correct it.',
    searchLabel: 'Search stock',
    searchPlaceholder: 'Name or code',
    statusLabel: 'Status',
    statuses: { all: 'All', available: 'Available', out_of_stock: 'Out of stock', upcoming: 'Upcoming' },
    count: (n: number, shown: string) => (n === 1 ? '1 product' : `${shown} products`),
    emptyAll: 'No stock yet.',
    emptyFiltered: 'No product matches.',
    inStock: 'In stock',
    pcs: (shown: string) => `${shown} pcs`,
    dpEach: (amount: string) => `DP ${amount} each`,
    noSupplier: 'No supplier',

    opening: 'Opening',
    ordered: 'Ordered',
    received: 'Received',
    upcoming: 'Upcoming',
    sold: 'Sold',
    dpPer: 'DP per piece',
    value: 'Total value',
    adjustedBy: (shown: string) => `Includes ${shown} from manual adjustments.`,
    history: 'Stock history',
    noHistory: 'No movements yet.',
    historyError: 'Could not load the history.',
    showMore: 'Show more',
    after: (shown: string) => `Stock ${shown}`,
    moves: {
      opening_stock: 'Opening stock',
      opening_stock_update: 'Opening stock changed',
      manual_adjustment: 'Manual adjustment',
      sale: 'Sold',
      sale_rollback: 'Sale changed',
      sale_restore: 'Sale restored',
      purchase: 'Received from supplier',
      purchase_receive_edit: 'Receipt changed',
      purchase_receive_delete: 'Receipt deleted',
      purchase_delete: 'Purchase deleted',
      purchase_restore: 'Purchase restored',
      damage_out: 'Damaged',
      damage_in: 'Back from damage',
      damage_delete: 'Damage entry deleted',
      damage_restore: 'Damage entry restored',
    } as Record<string, string>,
    otherMove: 'Stock change',

    adjust: 'Adjust stock',
    adjustHint: 'For damage, loss or a stock count. Five chairs damaged: remove 5.',
    add: 'Add',
    remove: 'Remove',
    qtyField: 'How many *',
    reasonField: 'Reason',
    reasonPlaceholder: 'e.g. Damaged in transit',
    defaultReason: 'Manual adjustment',
    errQty: 'Enter a whole number above 0',
    adjusted: (name: string) => `${name} stock adjusted`,
    printTitle: 'Inventory',
    colNo: '#',
    colCode: 'Code',
    colName: 'Product',
    colStock: 'In stock',
    colDp: 'DP',
    colValue: 'Value',
    colStatus: 'Status',
  },
  bn: {
    title: 'ইনভেন্টরি',
    close: 'বন্ধ করুন',
    loadError: 'স্টকের তালিকা আনা যায়নি।',
    retry: 'আবার চেষ্টা করুন',
    cancel: 'বাতিল',
    save: 'সেভ করুন',
    saving: 'সেভ হচ্ছে…',
    printList: 'তালিকা প্রিন্ট করুন',

    totalValue: 'মোট স্টক মূল্য (DP ভিত্তিক)',
    oversoldNote:
      'কিছু পণ্য যত কেনা হয়েছে বলে লেখা আছে তার চেয়ে বেশি বিক্রি হয়েছে, তাই ওগুলোর স্টক ঋণাত্মক এবং এই মোট থেকে বাদ যাচ্ছে। বাকি কেনাগুলো এন্ট্রি দিলে ঠিক হয়ে যাবে।',
    searchLabel: 'স্টক খুঁজুন',
    searchPlaceholder: 'নাম বা কোড',
    statusLabel: 'স্ট্যাটাস',
    statuses: { all: 'সব', available: 'পাওয়া যাচ্ছে', out_of_stock: 'স্টক নেই', upcoming: 'আসছে' },
    count: (_n: number, shown: string) => `${shown}টি পণ্য`,
    emptyAll: 'এখনো কোনো স্টক নেই।',
    emptyFiltered: 'কোনো পণ্য মেলেনি।',
    inStock: 'বর্তমান স্টক',
    pcs: (shown: string) => `${shown} পিস`,
    dpEach: (amount: string) => `প্রতিটি DP ${amount}`,
    noSupplier: 'সাপ্লায়ার নেই',

    opening: 'প্রারম্ভিক',
    ordered: 'অর্ডার',
    received: 'গৃহীত',
    upcoming: 'আসছে',
    sold: 'বিক্রি',
    dpPer: 'প্রতি পণ্য DP',
    value: 'মোট মূল্য',
    adjustedBy: (shown: string) => `এর মধ্যে হাতে সমন্বয় ${shown}।`,
    history: 'স্টকের ইতিহাস',
    noHistory: 'এখনো কোনো আনা-নেওয়া নেই।',
    historyError: 'ইতিহাস আনা যায়নি।',
    showMore: 'আরও দেখুন',
    after: (shown: string) => `স্টক ${shown}`,
    moves: {
      opening_stock: 'প্রারম্ভিক স্টক',
      opening_stock_update: 'প্রারম্ভিক স্টক বদল',
      manual_adjustment: 'হাতে সমন্বয়',
      sale: 'বিক্রি',
      sale_rollback: 'বিক্রি বদল',
      sale_restore: 'বিক্রি ফেরানো',
      purchase: 'সাপ্লায়ার থেকে গৃহীত',
      purchase_receive_edit: 'গ্রহণ বদল',
      purchase_receive_delete: 'গ্রহণ মুছে ফেলা',
      purchase_delete: 'ক্রয় মুছে ফেলা',
      purchase_restore: 'ক্রয় ফেরানো',
      damage_out: 'ড্যামেজ',
      damage_in: 'ড্যামেজ থেকে ফেরত',
      damage_delete: 'ড্যামেজ এন্ট্রি মুছে ফেলা',
      damage_restore: 'ড্যামেজ এন্ট্রি ফেরানো',
    } as Record<string, string>,
    otherMove: 'স্টক বদল',

    adjust: 'স্টক সমন্বয়',
    adjustHint: 'ড্যামেজ, হারানো বা গণনার জন্য। পাঁচটা চেয়ার নষ্ট হলে: ৫ বাদ দিন।',
    add: 'যোগ',
    remove: 'বাদ',
    qtyField: 'কতগুলো *',
    reasonField: 'কারণ',
    reasonPlaceholder: 'যেমন: পথে নষ্ট হয়েছে',
    // Stored in the history, which the website shows as written - so in its words.
    defaultReason: 'Manual adjustment',
    errQty: '০-এর বেশি পূর্ণ সংখ্যা লিখুন',
    adjusted: (name: string) => `${name}-এর স্টক সমন্বয় হয়েছে`,
    printTitle: 'ইনভেন্টরি',
    colNo: '#',
    colCode: 'কোড',
    colName: 'পণ্য',
    colStock: 'বর্তমান স্টক',
    colDp: 'DP',
    colValue: 'মূল্য',
    colStatus: 'স্ট্যাটাস',
  },
};

